/******************************************************************************/
/* Copyright (C) 2023 Texas Instruments Incorporated - http://www.ti.com/
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 ******************************************************************************/

#include "VXLIB_addSquare_idat.h"
/*This file is autogenerated*/
/*Please do not edit*/

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
#include "test_data/staticRefCase1.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
#include "test_data/staticRefCase2.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
#include "test_data/staticRefCase3.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
#include "test_data/staticRefCase4.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
#include "test_data/staticRefCase5.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
#include "test_data/staticRefCase6.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
#include "test_data/staticRefCase7.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
#include "test_data/staticRefCase8.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
#include "test_data/staticRefCase9.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
#include "test_data/staticRefCase10.h"
#endif

static VXLIB_addSquare_testParams_t testParams[] = {
#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case1,                                // Input vector 0
    VXLIB_UINT8,                                      // data type in0
    staticRefIn1Case1,                                // Input vector 1
    VXLIB_INT16,                                      // data type in1
    staticRefOutCase1,                                // Output vector
    VXLIB_INT16,                                      // data type out
    128,                                              // width of image
    128,                                              // height of image
    128 * sizeof (uint8_t),                           // strideIn0
    128 * sizeof (int16_t),                           // strideIn1
    128 * sizeof (int16_t),                           // strideOut
    12,                                               // shift
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    1,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case2,                                // Input vector 0
    VXLIB_UINT8,                                      // data type in0
    staticRefIn1Case2,                                // Input vector 1
    VXLIB_INT16,                                      // data type in1
    staticRefOutCase2,                                // Output vector
    VXLIB_INT16,                                      // data type out
    128,                                              // width of image
    128,                                              // height of image
    128 * sizeof (uint8_t),                           // strideIn0
    128 * sizeof (int16_t),                           // strideIn1
    128 * sizeof (int16_t),                           // strideOut
    13,                                               // shift
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    2,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case3,                                // Input vector 0
    VXLIB_UINT8,                                      // data type in0
    staticRefIn1Case3,                                // Input vector 1
    VXLIB_INT16,                                      // data type in1
    staticRefOutCase3,                                // Output vector
    VXLIB_INT16,                                      // data type out
    128,                                              // width of image
    128,                                              // height of image
    128 * sizeof (uint8_t),                           // strideIn0
    128 * sizeof (int16_t),                           // strideIn1
    128 * sizeof (int16_t),                           // strideOut
    14,                                               // shift
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    3,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case4,                                // Input vector 0
    VXLIB_UINT8,                                      // data type in0
    staticRefIn1Case4,                                // Input vector 1
    VXLIB_INT16,                                      // data type in1
    staticRefOutCase4,                                // Output vector
    VXLIB_INT16,                                      // data type out
    128,                                              // width of image
    128,                                              // height of image
    128 * sizeof (uint8_t),                           // strideIn0
    128 * sizeof (int16_t),                           // strideIn1
    128 * sizeof (int16_t),                           // strideOut
    10,                                               // shift
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    4,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case5,                                // Input vector 0
    VXLIB_UINT8,                                      // data type in0
    staticRefIn1Case5,                                // Input vector 1
    VXLIB_INT16,                                      // data type in1
    staticRefOutCase5,                                // Output vector
    VXLIB_INT16,                                      // data type out
    256,                                              // width of image
    256,                                              // height of image
    256 * sizeof (uint8_t),                           // strideIn0
    256 * sizeof (int16_t),                           // strideIn1
    256 * sizeof (int16_t),                           // strideOut
    12,                                               // shift
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    5,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case6,                                // Input vector 0
    VXLIB_UINT8,                                      // data type in0
    staticRefIn1Case6,                                // Input vector 1
    VXLIB_INT16,                                      // data type in1
    staticRefOutCase6,                                // Output vector
    VXLIB_INT16,                                      // data type out
    129,                                              // width of image
    129,                                              // height of image
    256 * sizeof (uint8_t),                           // strideIn0
    256 * sizeof (int16_t),                           // strideIn1
    256 * sizeof (int16_t),                           // strideOut
    13,                                               // shift
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    6,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case7,                                // Input vector 0
    VXLIB_UINT8,                                      // data type in0
    staticRefIn1Case7,                                // Input vector 1
    VXLIB_INT16,                                      // data type in1
    staticRefOutCase7,                                // Output vector
    VXLIB_INT16,                                      // data type out
    31,                                               // width of image
    31,                                               // height of image
    31 * sizeof (uint8_t),                            // strideIn0
    128 * sizeof (int16_t),                           // strideIn1
    128 * sizeof (int16_t),                           // strideOut
    14,                                               // shift
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    7,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case8,                                // Input vector 0
    VXLIB_UINT8,                                      // data type in0
    staticRefIn1Case8,                                // Input vector 1
    VXLIB_INT16,                                      // data type in1
    staticRefOutCase8,                                // Output vector
    VXLIB_INT16,                                      // data type out
    128,                                              // width of image
    128,                                              // height of image
    192 * sizeof (uint8_t),                           // strideIn0
    192 * sizeof (int16_t),                           // strideIn1
    256 * sizeof (int16_t),                           // strideOut
    10,                                               // shift
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    8,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case9,                                // Input vector 0
    VXLIB_UINT8,                                      // data type in0
    staticRefIn1Case9,                                // Input vector 1
    VXLIB_INT16,                                      // data type in1
    staticRefOutCase9,                                // Output vector
    VXLIB_INT16,                                      // data type out
    10,                                               // width of image
    120,                                              // height of image
    10 * sizeof (uint8_t),                            // strideIn0
    10 * sizeof (int16_t),                            // strideIn1
    10 * sizeof (int16_t),                            // strideOut
    12,                                               // shift
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    9,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case10,                               // Input vector 0
    VXLIB_UINT8,                                      // data type in0
    staticRefIn1Case10,                               // Input vector 1
    VXLIB_INT16,                                      // data type in1
    staticRefOutCase10,                               // Output vector
    VXLIB_INT16,                                      // data type out
    1,                                                // width of image
    1200,                                             // height of image
    10 * sizeof (uint8_t),                            // strideIn0
    10 * sizeof (int16_t),                            // strideIn1
    10 * sizeof (int16_t),                            // strideOut
    13,                                               // shift
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    10,                                               // test ID
    },
#endif

};

/*
 *  Sends the test parameter structure and number of tests
 */
void
VXLIB_addSquare_getTestParams (VXLIB_addSquare_testParams_t ** params, int32_t * numTests)
{
   *params = testParams;
   *numTests = sizeof (testParams) / sizeof (VXLIB_addSquare_testParams_t);
}
