/******************************************************************************/
/* Copyright (C) 2023 Texas Instruments Incorporated - http://www.ti.com/
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 ******************************************************************************/

#include "VXLIB_halfScaleGaussian_idat.h"
/*This file is autogenerated*/
/*Please do not edit*/

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
#include "test_data/staticRefCase1.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
#include "test_data/staticRefCase2.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
#include "test_data/staticRefCase3.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
#include "test_data/staticRefCase4.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
#include "test_data/staticRefCase5.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
#include "test_data/staticRefCase6.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
#include "test_data/staticRefCase7.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
#include "test_data/staticRefCase8.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
#include "test_data/staticRefCase9.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
#include "test_data/staticRefCase10.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
#include "test_data/staticRefCase11.h"
#endif

static VXLIB_halfScaleGaussian_testParams_t testParams[] = {
#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
   {
    STATIC,                                           // Test pattern
    staticRefInCase1,                                 // Input vector
    VXLIB_UINT8,                                      // data type in
    staticRefOutCase1,                                // Output vector
    VXLIB_UINT8,                                      // data type out
    10,                                               // width of input image
    10,                                               // height of input image
    3,                                                // width of output image
    3,                                                // height of output image
    5,                                                // size of filter
    10 * sizeof (uint8_t),                            // strideIn
    3 * sizeof (uint8_t),                             // strideOut
    0,                                                // padLeft
    0,                                                // padRight
    0,                                                // padTop
    0,                                                // padBottom
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    1,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
   {
    STATIC,                                           // Test pattern
    staticRefInCase2,                                 // Input vector
    VXLIB_UINT8,                                      // data type in
    staticRefOutCase2,                                // Output vector
    VXLIB_UINT8,                                      // data type out
    36,                                               // width of input image
    36,                                               // height of input image
    16,                                               // width of output image
    16,                                               // height of output image
    5,                                                // size of filter
    36 * sizeof (uint8_t),                            // strideIn
    16 * sizeof (uint8_t),                            // strideOut
    0,                                                // padLeft
    0,                                                // padRight
    0,                                                // padTop
    0,                                                // padBottom
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    2,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
   {
    STATIC,                                           // Test pattern
    staticRefInCase3,                                 // Input vector
    VXLIB_UINT8,                                      // data type in
    staticRefOutCase3,                                // Output vector
    VXLIB_UINT8,                                      // data type out
    32,                                               // width of input image
    32,                                               // height of input image
    14,                                               // width of output image
    14,                                               // height of output image
    5,                                                // size of filter
    36 * sizeof (uint8_t),                            // strideIn
    16 * sizeof (uint8_t),                            // strideOut
    0,                                                // padLeft
    0,                                                // padRight
    0,                                                // padTop
    0,                                                // padBottom
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    3,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
   {
    STATIC,                                           // Test pattern
    staticRefInCase4,                                 // Input vector
    VXLIB_UINT8,                                      // data type in
    staticRefOutCase4,                                // Output vector
    VXLIB_UINT8,                                      // data type out
    32,                                               // width of input image
    36,                                               // height of input image
    14,                                               // width of output image
    16,                                               // height of output image
    5,                                                // size of filter
    36 * sizeof (uint8_t),                            // strideIn
    16 * sizeof (uint8_t),                            // strideOut
    0,                                                // padLeft
    0,                                                // padRight
    0,                                                // padTop
    0,                                                // padBottom
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    4,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
   {
    STATIC,                                           // Test pattern
    staticRefInCase5,                                 // Input vector
    VXLIB_UINT8,                                      // data type in
    staticRefOutCase5,                                // Output vector
    VXLIB_UINT8,                                      // data type out
    16,                                               // width of input image
    16,                                               // height of input image
    6,                                                // width of output image
    6,                                                // height of output image
    5,                                                // size of filter
    16 * sizeof (uint8_t),                            // strideIn
    6 * sizeof (uint8_t),                             // strideOut
    0,                                                // padLeft
    0,                                                // padRight
    0,                                                // padTop
    0,                                                // padBottom
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    5,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
   {
    STATIC,                                           // Test pattern
    staticRefInCase6,                                 // Input vector
    VXLIB_UINT8,                                      // data type in
    staticRefOutCase6,                                // Output vector
    VXLIB_UINT8,                                      // data type out
    32,                                               // width of input image
    32,                                               // height of input image
    14,                                               // width of output image
    14,                                               // height of output image
    5,                                                // size of filter
    32 * sizeof (uint8_t),                            // strideIn
    14 * sizeof (uint8_t),                            // strideOut
    0,                                                // padLeft
    0,                                                // padRight
    0,                                                // padTop
    0,                                                // padBottom
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    6,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
   {
    STATIC,                                           // Test pattern
    staticRefInCase7,                                 // Input vector
    VXLIB_UINT8,                                      // data type in
    staticRefOutCase7,                                // Output vector
    VXLIB_UINT8,                                      // data type out
    64,                                               // width of input image
    64,                                               // height of input image
    30,                                               // width of output image
    30,                                               // height of output image
    5,                                                // size of filter
    64 * sizeof (uint8_t),                            // strideIn
    30 * sizeof (uint8_t),                            // strideOut
    0,                                                // padLeft
    0,                                                // padRight
    0,                                                // padTop
    0,                                                // padBottom
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    7,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
   {
    STATIC,                                           // Test pattern
    staticRefInCase8,                                 // Input vector
    VXLIB_UINT8,                                      // data type in
    staticRefOutCase8,                                // Output vector
    VXLIB_UINT8,                                      // data type out
    128,                                              // width of input image
    128,                                              // height of input image
    62,                                               // width of output image
    62,                                               // height of output image
    5,                                                // size of filter
    128 * sizeof (uint8_t),                           // strideIn
    62 * sizeof (uint8_t),                            // strideOut
    0,                                                // padLeft
    0,                                                // padRight
    0,                                                // padTop
    0,                                                // padBottom
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    8,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
   {
    STATIC,                                           // Test pattern
    staticRefInCase9,                                 // Input vector
    VXLIB_UINT8,                                      // data type in
    staticRefOutCase9,                                // Output vector
    VXLIB_UINT8,                                      // data type out
    256,                                              // width of input image
    256,                                              // height of input image
    126,                                              // width of output image
    126,                                              // height of output image
    5,                                                // size of filter
    256 * sizeof (uint8_t),                           // strideIn
    126 * sizeof (uint8_t),                           // strideOut
    0,                                                // padLeft
    0,                                                // padRight
    0,                                                // padTop
    0,                                                // padBottom
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    9,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
   {
    STATIC,                                           // Test pattern
    staticRefInCase10,                                // Input vector
    VXLIB_UINT8,                                      // data type in
    staticRefOutCase10,                               // Output vector
    VXLIB_UINT8,                                      // data type out
    512,                                              // width of input image
    512,                                              // height of input image
    254,                                              // width of output image
    254,                                              // height of output image
    5,                                                // size of filter
    512 * sizeof (uint8_t),                           // strideIn
    254 * sizeof (uint8_t),                           // strideOut
    0,                                                // padLeft
    0,                                                // padRight
    0,                                                // padTop
    0,                                                // padBottom
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    10,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
   {
    STATIC,                                           // Test pattern
    staticRefInCase11,                                // Input vector
    VXLIB_UINT8,                                      // data type in
    staticRefOutCase11,                               // Output vector
    VXLIB_UINT8,                                      // data type out
    65,                                               // width of input image
    64,                                               // height of input image
    15,                                               // width of output image
    30,                                               // height of output image
    5,                                                // size of filter
    100 * sizeof (uint8_t),                           // strideIn
    30 * sizeof (uint8_t),                            // strideOut
    0,                                                // padLeft
    0,                                                // padRight
    0,                                                // padTop
    0,                                                // padBottom
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    11,                                               // test ID
    },
#endif

};

/*
 *  Sends the test parameter structure and number of tests
 */
void
VXLIB_halfScaleGaussian_getTestParams (VXLIB_halfScaleGaussian_testParams_t ** params, int32_t * numTests)
{
   *params = testParams;
   *numTests = sizeof (testParams) / sizeof (VXLIB_halfScaleGaussian_testParams_t);
}
