/******************************************************************************/
/* Copyright (C) 2023 Texas Instruments Incorporated - http://www.ti.com/
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 ******************************************************************************/
#include "DSPLIB_lud_idat.h"
/*This file is autogenerated*/
/*Please do not edit*/

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
#include "test_data/staticRefCase1.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
#include "test_data/staticRefCase3.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
#include "test_data/staticRefCase7.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 37))
#include "test_data/staticRefCase37.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 39))
#include "test_data/staticRefCase39.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 43))
#include "test_data/staticRefCase43.h"
#endif

static DSPLIB_lud_testParams_t testParams[] = {
#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
   {
    STATIC,                                           // Test pattern
    staticRefInACase1,                                // Input matrix A
    staticRefInBCase1,                                // Input array B
    staticRefOutPCase1,                               // Output matrix P
    staticRefOutLCase1,                               // Output matrix L
    staticRefOutUCase1,                               // Output matrix U
    staticRefOutXCase1,                               // Output matrix X
    staticRefOutInvACase1,                            // Output matrix invA
    DSPLIB_FLOAT32,                                   // dataType
    4,                                                // order
    DSPLIB_CALC_STRIDE (4 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),        // stride of A matrix
    DSPLIB_CALC_STRIDE (4 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    1,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT32,                                   // dataType
    6,                                                // order
    DSPLIB_CALC_STRIDE (6 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),        // stride of A matrix
    DSPLIB_CALC_STRIDE (6 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    2,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
   {
    STATIC,                                           // Test pattern
    staticRefInACase3,                                // Input matrix A
    staticRefInBCase3,                                // Input array B
    staticRefOutPCase3,                               // Output matrix P
    staticRefOutLCase3,                               // Output matrix L
    staticRefOutUCase3,                               // Output matrix U
    staticRefOutXCase3,                               // Output matrix X
    staticRefOutInvACase3,                            // Output matrix invA
    DSPLIB_FLOAT32,                                   // dataType
    8,                                                // order
    DSPLIB_CALC_STRIDE (8 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),        // stride of A matrix
    DSPLIB_CALC_STRIDE (8 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    3,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT32,                                   // dataType
    12,                                               // order
    DSPLIB_CALC_STRIDE (12 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of A matrix
    DSPLIB_CALC_STRIDE (12 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    4,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT32,                                   // dataType
    16,                                               // order
    DSPLIB_CALC_STRIDE (16 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of A matrix
    DSPLIB_CALC_STRIDE (16 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    5,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT32,                                   // dataType
    20,                                               // order
    DSPLIB_CALC_STRIDE (20 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of A matrix
    DSPLIB_CALC_STRIDE (20 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    6,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
   {
    STATIC,                                           // Test pattern
    staticRefInACase7,                                // Input matrix A
    staticRefInBCase7,                                // Input array B
    staticRefOutPCase7,                               // Output matrix P
    staticRefOutLCase7,                               // Output matrix L
    staticRefOutUCase7,                               // Output matrix U
    staticRefOutXCase7,                               // Output matrix X
    staticRefOutInvACase7,                            // Output matrix invA
    DSPLIB_FLOAT32,                                   // dataType
    24,                                               // order
    DSPLIB_CALC_STRIDE (24 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of A matrix
    DSPLIB_CALC_STRIDE (24 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    7,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT32,                                   // dataType
    28,                                               // order
    DSPLIB_CALC_STRIDE (28 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of A matrix
    DSPLIB_CALC_STRIDE (28 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    8,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT32,                                   // dataType
    32,                                               // order
    DSPLIB_CALC_STRIDE (32 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of A matrix
    DSPLIB_CALC_STRIDE (32 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    9,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT32,                                   // dataType
    36,                                               // order
    DSPLIB_CALC_STRIDE (36 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of A matrix
    DSPLIB_CALC_STRIDE (36 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    10,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT32,                                   // dataType
    37,                                               // order
    DSPLIB_CALC_STRIDE (37 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of A matrix
    DSPLIB_CALC_STRIDE (37 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    11,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT32,                                   // dataType
    44,                                               // order
    DSPLIB_CALC_STRIDE (44 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of A matrix
    DSPLIB_CALC_STRIDE (44 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    12,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 13))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT32,                                   // dataType
    48,                                               // order
    DSPLIB_CALC_STRIDE (48 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of A matrix
    DSPLIB_CALC_STRIDE (48 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    13,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 14))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT32,                                   // dataType
    52,                                               // order
    DSPLIB_CALC_STRIDE (52 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of A matrix
    DSPLIB_CALC_STRIDE (52 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    14,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 15))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT32,                                   // dataType
    59,                                               // order
    DSPLIB_CALC_STRIDE (59 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of A matrix
    DSPLIB_CALC_STRIDE (59 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    15,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 16))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT32,                                   // dataType
    60,                                               // order
    DSPLIB_CALC_STRIDE (60 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of A matrix
    DSPLIB_CALC_STRIDE (60 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    16,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 17))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT32,                                   // dataType
    64,                                               // order
    DSPLIB_CALC_STRIDE (64 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of A matrix
    DSPLIB_CALC_STRIDE (64 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    17,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 18))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT32,                                   // dataType
    68,                                               // order
    DSPLIB_CALC_STRIDE (68 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of A matrix
    DSPLIB_CALC_STRIDE (68 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    18,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 19))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT32,                                   // dataType
    72,                                               // order
    DSPLIB_CALC_STRIDE (72 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of A matrix
    DSPLIB_CALC_STRIDE (72 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    19,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 20))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT32,                                   // dataType
    76,                                               // order
    DSPLIB_CALC_STRIDE (76 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of A matrix
    DSPLIB_CALC_STRIDE (76 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    20,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 21))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT32,                                   // dataType
    80,                                               // order
    DSPLIB_CALC_STRIDE (80 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of A matrix
    DSPLIB_CALC_STRIDE (80 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    21,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 22))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT32,                                   // dataType
    84,                                               // order
    DSPLIB_CALC_STRIDE (84 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of A matrix
    DSPLIB_CALC_STRIDE (84 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    22,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 23))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT32,                                   // dataType
    88,                                               // order
    DSPLIB_CALC_STRIDE (88 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of A matrix
    DSPLIB_CALC_STRIDE (88 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    23,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 24))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT32,                                   // dataType
    92,                                               // order
    DSPLIB_CALC_STRIDE (92 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of A matrix
    DSPLIB_CALC_STRIDE (92 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    24,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 25))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT32,                                   // dataType
    96,                                               // order
    DSPLIB_CALC_STRIDE (96 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of A matrix
    DSPLIB_CALC_STRIDE (96 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    25,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 26))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT32,                                   // dataType
    101,                                              // order
    DSPLIB_CALC_STRIDE (101 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of A matrix
    DSPLIB_CALC_STRIDE (101 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),     // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    26,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 27))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT32,                                   // dataType
    104,                                              // order
    DSPLIB_CALC_STRIDE (104 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of A matrix
    DSPLIB_CALC_STRIDE (104 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),     // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    27,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 28))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT32,                                   // dataType
    108,                                              // order
    DSPLIB_CALC_STRIDE (108 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of A matrix
    DSPLIB_CALC_STRIDE (108 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),     // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    28,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 29))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT32,                                   // dataType
    112,                                              // order
    DSPLIB_CALC_STRIDE (112 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of A matrix
    DSPLIB_CALC_STRIDE (112 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),     // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    29,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 30))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT32,                                   // dataType
    116,                                              // order
    DSPLIB_CALC_STRIDE (116 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of A matrix
    DSPLIB_CALC_STRIDE (116 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),     // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    30,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 31))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT32,                                   // dataType
    120,                                              // order
    DSPLIB_CALC_STRIDE (120 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of A matrix
    DSPLIB_CALC_STRIDE (120 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),     // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    31,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 32))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT32,                                   // dataType
    124,                                              // order
    DSPLIB_CALC_STRIDE (124 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of A matrix
    DSPLIB_CALC_STRIDE (124 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),     // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    32,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 33))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT32,                                   // dataType
    128,                                              // order
    DSPLIB_CALC_STRIDE (128 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of A matrix
    DSPLIB_CALC_STRIDE (128 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),     // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    33,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 34))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT32,                                   // dataType
    132,                                              // order
    DSPLIB_CALC_STRIDE (132 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of A matrix
    DSPLIB_CALC_STRIDE (132 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),     // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    34,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 35))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT32,                                   // dataType
    136,                                              // order
    DSPLIB_CALC_STRIDE (136 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of A matrix
    DSPLIB_CALC_STRIDE (136 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),     // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    35,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 36))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT32,                                   // dataType
    140,                                              // order
    DSPLIB_CALC_STRIDE (140 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of A matrix
    DSPLIB_CALC_STRIDE (140 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),     // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    36,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 37))
   {
    STATIC,                                           // Test pattern
    staticRefInACase37,                               // Input matrix A
    staticRefInBCase37,                               // Input array B
    staticRefOutPCase37,                              // Output matrix P
    staticRefOutLCase37,                              // Output matrix L
    staticRefOutUCase37,                              // Output matrix U
    staticRefOutXCase37,                              // Output matrix X
    staticRefOutInvACase37,                           // Output matrix invA
    DSPLIB_FLOAT64,                                   // dataType
    4,                                                // order
    DSPLIB_CALC_STRIDE (4 * sizeof (double), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of A matrix
    DSPLIB_CALC_STRIDE (4 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    37,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 38))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT64,                                   // dataType
    6,                                                // order
    DSPLIB_CALC_STRIDE (6 * sizeof (double), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of A matrix
    DSPLIB_CALC_STRIDE (6 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    38,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 39))
   {
    STATIC,                                           // Test pattern
    staticRefInACase39,                               // Input matrix A
    staticRefInBCase39,                               // Input array B
    staticRefOutPCase39,                              // Output matrix P
    staticRefOutLCase39,                              // Output matrix L
    staticRefOutUCase39,                              // Output matrix U
    staticRefOutXCase39,                              // Output matrix X
    staticRefOutInvACase39,                           // Output matrix invA
    DSPLIB_FLOAT64,                                   // dataType
    8,                                                // order
    DSPLIB_CALC_STRIDE (8 * sizeof (double), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of A matrix
    DSPLIB_CALC_STRIDE (8 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    39,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 40))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT64,                                   // dataType
    12,                                               // order
    DSPLIB_CALC_STRIDE (12 * sizeof (double), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of A matrix
    DSPLIB_CALC_STRIDE (12 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    40,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 41))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT64,                                   // dataType
    16,                                               // order
    DSPLIB_CALC_STRIDE (16 * sizeof (double), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of A matrix
    DSPLIB_CALC_STRIDE (16 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    41,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 42))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT64,                                   // dataType
    20,                                               // order
    DSPLIB_CALC_STRIDE (20 * sizeof (double), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of A matrix
    DSPLIB_CALC_STRIDE (20 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    42,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 43))
   {
    STATIC,                                           // Test pattern
    staticRefInACase43,                               // Input matrix A
    staticRefInBCase43,                               // Input array B
    staticRefOutPCase43,                              // Output matrix P
    staticRefOutLCase43,                              // Output matrix L
    staticRefOutUCase43,                              // Output matrix U
    staticRefOutXCase43,                              // Output matrix X
    staticRefOutInvACase43,                           // Output matrix invA
    DSPLIB_FLOAT64,                                   // dataType
    24,                                               // order
    DSPLIB_CALC_STRIDE (24 * sizeof (double), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of A matrix
    DSPLIB_CALC_STRIDE (24 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    43,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 44))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT64,                                   // dataType
    28,                                               // order
    DSPLIB_CALC_STRIDE (28 * sizeof (double), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of A matrix
    DSPLIB_CALC_STRIDE (28 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    44,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 45))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT64,                                   // dataType
    32,                                               // order
    DSPLIB_CALC_STRIDE (32 * sizeof (double), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of A matrix
    DSPLIB_CALC_STRIDE (32 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    45,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 46))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT64,                                   // dataType
    36,                                               // order
    DSPLIB_CALC_STRIDE (36 * sizeof (double), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of A matrix
    DSPLIB_CALC_STRIDE (36 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    46,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 47))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT64,                                   // dataType
    37,                                               // order
    DSPLIB_CALC_STRIDE (37 * sizeof (double), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of A matrix
    DSPLIB_CALC_STRIDE (37 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    47,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 48))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT64,                                   // dataType
    44,                                               // order
    DSPLIB_CALC_STRIDE (44 * sizeof (double), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of A matrix
    DSPLIB_CALC_STRIDE (44 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    48,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 49))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT64,                                   // dataType
    48,                                               // order
    DSPLIB_CALC_STRIDE (48 * sizeof (double), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of A matrix
    DSPLIB_CALC_STRIDE (48 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    49,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 50))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT64,                                   // dataType
    52,                                               // order
    DSPLIB_CALC_STRIDE (52 * sizeof (double), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of A matrix
    DSPLIB_CALC_STRIDE (52 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    50,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 51))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT64,                                   // dataType
    59,                                               // order
    DSPLIB_CALC_STRIDE (59 * sizeof (double), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of A matrix
    DSPLIB_CALC_STRIDE (59 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    51,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 52))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT64,                                   // dataType
    60,                                               // order
    DSPLIB_CALC_STRIDE (60 * sizeof (double), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of A matrix
    DSPLIB_CALC_STRIDE (60 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    52,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 53))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT64,                                   // dataType
    64,                                               // order
    DSPLIB_CALC_STRIDE (64 * sizeof (double), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of A matrix
    DSPLIB_CALC_STRIDE (64 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    53,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 54))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT64,                                   // dataType
    68,                                               // order
    DSPLIB_CALC_STRIDE (68 * sizeof (double), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of A matrix
    DSPLIB_CALC_STRIDE (68 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    54,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 55))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT64,                                   // dataType
    72,                                               // order
    DSPLIB_CALC_STRIDE (72 * sizeof (double), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of A matrix
    DSPLIB_CALC_STRIDE (72 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    55,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 56))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT64,                                   // dataType
    76,                                               // order
    DSPLIB_CALC_STRIDE (76 * sizeof (double), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of A matrix
    DSPLIB_CALC_STRIDE (76 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    56,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 57))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT64,                                   // dataType
    80,                                               // order
    DSPLIB_CALC_STRIDE (80 * sizeof (double), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of A matrix
    DSPLIB_CALC_STRIDE (80 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    57,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 58))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT64,                                   // dataType
    84,                                               // order
    DSPLIB_CALC_STRIDE (84 * sizeof (double), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of A matrix
    DSPLIB_CALC_STRIDE (84 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    58,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 59))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT64,                                   // dataType
    88,                                               // order
    DSPLIB_CALC_STRIDE (88 * sizeof (double), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of A matrix
    DSPLIB_CALC_STRIDE (88 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    59,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 60))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT64,                                   // dataType
    92,                                               // order
    DSPLIB_CALC_STRIDE (92 * sizeof (double), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of A matrix
    DSPLIB_CALC_STRIDE (92 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    60,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 61))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT64,                                   // dataType
    96,                                               // order
    DSPLIB_CALC_STRIDE (96 * sizeof (double), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of A matrix
    DSPLIB_CALC_STRIDE (96 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    61,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 62))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT64,                                   // dataType
    101,                                              // order
    DSPLIB_CALC_STRIDE (101 * sizeof (double), DSPLIB_ALIGN_SHIFT_64BYTES),     // stride of A matrix
    DSPLIB_CALC_STRIDE (101 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),     // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    62,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 63))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT64,                                   // dataType
    104,                                              // order
    DSPLIB_CALC_STRIDE (104 * sizeof (double), DSPLIB_ALIGN_SHIFT_64BYTES),     // stride of A matrix
    DSPLIB_CALC_STRIDE (104 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),     // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    63,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 64))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT64,                                   // dataType
    108,                                              // order
    DSPLIB_CALC_STRIDE (108 * sizeof (double), DSPLIB_ALIGN_SHIFT_64BYTES),     // stride of A matrix
    DSPLIB_CALC_STRIDE (108 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),     // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    64,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 65))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT64,                                   // dataType
    112,                                              // order
    DSPLIB_CALC_STRIDE (112 * sizeof (double), DSPLIB_ALIGN_SHIFT_64BYTES),     // stride of A matrix
    DSPLIB_CALC_STRIDE (112 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),     // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    65,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 66))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT64,                                   // dataType
    116,                                              // order
    DSPLIB_CALC_STRIDE (116 * sizeof (double), DSPLIB_ALIGN_SHIFT_64BYTES),     // stride of A matrix
    DSPLIB_CALC_STRIDE (116 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),     // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    66,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 67))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT64,                                   // dataType
    120,                                              // order
    DSPLIB_CALC_STRIDE (120 * sizeof (double), DSPLIB_ALIGN_SHIFT_64BYTES),     // stride of A matrix
    DSPLIB_CALC_STRIDE (120 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),     // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    67,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 68))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT64,                                   // dataType
    124,                                              // order
    DSPLIB_CALC_STRIDE (124 * sizeof (double), DSPLIB_ALIGN_SHIFT_64BYTES),     // stride of A matrix
    DSPLIB_CALC_STRIDE (124 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),     // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    68,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 69))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT64,                                   // dataType
    128,                                              // order
    DSPLIB_CALC_STRIDE (128 * sizeof (double), DSPLIB_ALIGN_SHIFT_64BYTES),     // stride of A matrix
    DSPLIB_CALC_STRIDE (128 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),     // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    69,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 70))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT64,                                   // dataType
    132,                                              // order
    DSPLIB_CALC_STRIDE (132 * sizeof (double), DSPLIB_ALIGN_SHIFT_64BYTES),     // stride of A matrix
    DSPLIB_CALC_STRIDE (132 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),     // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    70,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 71))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT64,                                   // dataType
    136,                                              // order
    DSPLIB_CALC_STRIDE (136 * sizeof (double), DSPLIB_ALIGN_SHIFT_64BYTES),     // stride of A matrix
    DSPLIB_CALC_STRIDE (136 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),     // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    71,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 72))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT64,                                   // dataType
    140,                                              // order
    DSPLIB_CALC_STRIDE (140 * sizeof (double), DSPLIB_ALIGN_SHIFT_64BYTES),     // stride of A matrix
    DSPLIB_CALC_STRIDE (140 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),     // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    72,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 73))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT32,                                   // dataType
    256,                                              // order
    DSPLIB_CALC_STRIDE (256 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of A matrix
    DSPLIB_CALC_STRIDE (256 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),     // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    73,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 74))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT64,                                   // dataType
    256,                                              // order
    DSPLIB_CALC_STRIDE (256 * sizeof (double), DSPLIB_ALIGN_SHIFT_64BYTES),     // stride of A matrix
    DSPLIB_CALC_STRIDE (256 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),     // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    74,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 75))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input array B
    NULL,                                             // Output matrix P
    NULL,                                             // Output matrix L
    NULL,                                             // Output matrix U
    NULL,                                             // Output matrix X
    NULL,                                             // Output matrix invA
    DSPLIB_FLOAT64,                                   // dataType
    1,                                                // order
    DSPLIB_CALC_STRIDE (1 * sizeof (double), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of A matrix
    DSPLIB_CALC_STRIDE (1 * sizeof (unsigned short), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of P matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    75,                                               // test ID
    },
#endif

};

/*
 *  Sends the test parameter structure and number of tests
 */
void
DSPLIB_lud_getTestParams (DSPLIB_lud_testParams_t ** params, int32_t * numTests)
{
   *params = testParams;
   *numTests = sizeof (testParams) / sizeof (DSPLIB_lud_testParams_t);
}
