/******************************************************************************/
/* Copyright (C) 2023 Texas Instruments Incorporated - http://www.ti.com/
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 ******************************************************************************/
#include "DSPLIB_dotp_sqr_idat.h"
/*This file is autogenerated*/
/*Please do not edit*/

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 33))
#include "test_data/staticRefCase33.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 34))
#include "test_data/staticRefCase34.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 35))
#include "test_data/staticRefCase35.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 36))
#include "test_data/staticRefCase36.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 37))
#include "test_data/staticRefCase37.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 38))
#include "test_data/staticRefCase38.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 39))
#include "test_data/staticRefCase39.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 40))
#include "test_data/staticRefCase40.h"
#endif

static DSPLIB_dotp_sqr_testParams_t testParams[] = {
#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_UINT8,                                     // Input data type
    256,                                              // Input data length
    DSPLIB_UINT32,                                    // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    1,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_UINT8,                                     // Input data type
    512,                                              // Input data length
    DSPLIB_UINT32,                                    // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    2,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_UINT8,                                     // Input data type
    1024,                                             // Input data length
    DSPLIB_UINT32,                                    // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    3,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_UINT8,                                     // Input data type
    2048,                                             // Input data length
    DSPLIB_UINT32,                                    // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    4,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_UINT8,                                     // Input data type
    4096,                                             // Input data length
    DSPLIB_UINT32,                                    // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    5,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_UINT8,                                     // Input data type
    8192,                                             // Input data length
    DSPLIB_UINT32,                                    // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    6,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_UINT8,                                     // Input data type
    16384,                                            // Input data length
    DSPLIB_UINT32,                                    // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    7,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_UINT8,                                     // Input data type
    32768,                                            // Input data length
    DSPLIB_UINT32,                                    // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    8,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_INT8,                                      // Input data type
    256,                                              // Input data length
    DSPLIB_INT32,                                     // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    9,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_INT8,                                      // Input data type
    512,                                              // Input data length
    DSPLIB_INT32,                                     // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    10,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_INT8,                                      // Input data type
    1024,                                             // Input data length
    DSPLIB_INT32,                                     // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    11,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_INT8,                                      // Input data type
    2048,                                             // Input data length
    DSPLIB_INT32,                                     // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    12,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 13))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_INT8,                                      // Input data type
    4096,                                             // Input data length
    DSPLIB_INT32,                                     // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    13,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 14))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_INT8,                                      // Input data type
    8192,                                             // Input data length
    DSPLIB_INT32,                                     // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    14,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 15))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_INT8,                                      // Input data type
    16384,                                            // Input data length
    DSPLIB_INT32,                                     // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    15,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 16))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_INT8,                                      // Input data type
    32768,                                            // Input data length
    DSPLIB_INT32,                                     // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    16,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 17))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_UINT16,                                    // Input data type
    256,                                              // Input data length
    DSPLIB_UINT64,                                    // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    17,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 18))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_UINT16,                                    // Input data type
    512,                                              // Input data length
    DSPLIB_UINT64,                                    // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    18,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 19))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_UINT16,                                    // Input data type
    1024,                                             // Input data length
    DSPLIB_UINT64,                                    // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    19,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 20))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_UINT16,                                    // Input data type
    2048,                                             // Input data length
    DSPLIB_UINT64,                                    // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    20,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 21))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_UINT16,                                    // Input data type
    4096,                                             // Input data length
    DSPLIB_UINT64,                                    // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    21,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 22))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_UINT16,                                    // Input data type
    8192,                                             // Input data length
    DSPLIB_UINT64,                                    // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    22,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 23))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_UINT16,                                    // Input data type
    16384,                                            // Input data length
    DSPLIB_UINT64,                                    // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    23,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 24))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_UINT16,                                    // Input data type
    32768,                                            // Input data length
    DSPLIB_UINT64,                                    // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    24,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 25))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_INT16,                                     // Input data type
    256,                                              // Input data length
    DSPLIB_INT64,                                     // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    25,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 26))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_INT16,                                     // Input data type
    512,                                              // Input data length
    DSPLIB_INT64,                                     // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    26,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 27))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_INT16,                                     // Input data type
    1024,                                             // Input data length
    DSPLIB_INT64,                                     // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    27,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 28))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_INT16,                                     // Input data type
    2048,                                             // Input data length
    DSPLIB_INT64,                                     // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    28,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 29))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_INT16,                                     // Input data type
    4096,                                             // Input data length
    DSPLIB_INT64,                                     // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    29,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 30))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_INT16,                                     // Input data type
    8192,                                             // Input data length
    DSPLIB_INT64,                                     // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    30,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 31))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_INT16,                                     // Input data type
    16384,                                            // Input data length
    DSPLIB_INT64,                                     // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    31,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 32))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_INT16,                                     // Input data type
    32768,                                            // Input data length
    DSPLIB_INT64,                                     // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    32,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 33))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case33,                               // Input vector 0
    staticRefIn1Case33,                               // Input vector 1
    staticRefOutCase33,                               // Output vector
    DSPLIB_UINT32,                                    // Input data type
    256,                                              // Input data length
    DSPLIB_UINT64,                                    // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    33,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 34))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case34,                               // Input vector 0
    staticRefIn1Case34,                               // Input vector 1
    staticRefOutCase34,                               // Output vector
    DSPLIB_UINT32,                                    // Input data type
    512,                                              // Input data length
    DSPLIB_UINT64,                                    // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    34,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 35))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case35,                               // Input vector 0
    staticRefIn1Case35,                               // Input vector 1
    staticRefOutCase35,                               // Output vector
    DSPLIB_UINT32,                                    // Input data type
    1024,                                             // Input data length
    DSPLIB_UINT64,                                    // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    35,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 36))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case36,                               // Input vector 0
    staticRefIn1Case36,                               // Input vector 1
    staticRefOutCase36,                               // Output vector
    DSPLIB_UINT32,                                    // Input data type
    2048,                                             // Input data length
    DSPLIB_UINT64,                                    // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    36,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 37))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case37,                               // Input vector 0
    staticRefIn1Case37,                               // Input vector 1
    staticRefOutCase37,                               // Output vector
    DSPLIB_UINT32,                                    // Input data type
    4096,                                             // Input data length
    DSPLIB_UINT64,                                    // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    37,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 38))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case38,                               // Input vector 0
    staticRefIn1Case38,                               // Input vector 1
    staticRefOutCase38,                               // Output vector
    DSPLIB_UINT32,                                    // Input data type
    8192,                                             // Input data length
    DSPLIB_UINT64,                                    // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    38,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 39))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case39,                               // Input vector 0
    staticRefIn1Case39,                               // Input vector 1
    staticRefOutCase39,                               // Output vector
    DSPLIB_UINT32,                                    // Input data type
    16384,                                            // Input data length
    DSPLIB_UINT64,                                    // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    39,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 40))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case40,                               // Input vector 0
    staticRefIn1Case40,                               // Input vector 1
    staticRefOutCase40,                               // Output vector
    DSPLIB_UINT32,                                    // Input data type
    32768,                                            // Input data length
    DSPLIB_UINT64,                                    // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    40,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 41))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_INT32,                                     // Input data type
    256,                                              // Input data length
    DSPLIB_INT64,                                     // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    41,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 42))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_INT32,                                     // Input data type
    512,                                              // Input data length
    DSPLIB_INT64,                                     // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    42,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 43))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_INT32,                                     // Input data type
    1024,                                             // Input data length
    DSPLIB_INT64,                                     // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    43,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 44))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_INT32,                                     // Input data type
    2048,                                             // Input data length
    DSPLIB_INT64,                                     // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    44,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 45))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_INT32,                                     // Input data type
    4096,                                             // Input data length
    DSPLIB_INT64,                                     // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    45,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 46))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_INT32,                                     // Input data type
    8192,                                             // Input data length
    DSPLIB_INT64,                                     // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    46,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 47))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_INT32,                                     // Input data type
    16384,                                            // Input data length
    DSPLIB_INT64,                                     // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    47,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 48))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_INT32,                                     // Input data type
    32768,                                            // Input data length
    DSPLIB_INT64,                                     // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    48,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 49))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_FLOAT32,                                   // Input data type
    256,                                              // Input data length
    DSPLIB_FLOAT32,                                   // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    49,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 50))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_FLOAT32,                                   // Input data type
    512,                                              // Input data length
    DSPLIB_FLOAT32,                                   // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    50,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 51))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_FLOAT32,                                   // Input data type
    1024,                                             // Input data length
    DSPLIB_FLOAT32,                                   // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    51,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 52))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_FLOAT32,                                   // Input data type
    2048,                                             // Input data length
    DSPLIB_FLOAT32,                                   // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    52,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 53))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_FLOAT32,                                   // Input data type
    4096,                                             // Input data length
    DSPLIB_FLOAT32,                                   // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    53,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 54))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_FLOAT32,                                   // Input data type
    8192,                                             // Input data length
    DSPLIB_FLOAT32,                                   // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    54,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 55))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_FLOAT32,                                   // Input data type
    16384,                                            // Input data length
    DSPLIB_FLOAT32,                                   // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    55,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 56))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_FLOAT32,                                   // Input data type
    32768,                                            // Input data length
    DSPLIB_FLOAT32,                                   // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    56,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 57) || defined(DEMO_CASE))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_FLOAT64,                                   // Input data type
    256,                                              // Input data length
    DSPLIB_FLOAT64,                                   // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    57,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 58) || defined(DEMO_CASE))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_FLOAT64,                                   // Input data type
    512,                                              // Input data length
    DSPLIB_FLOAT64,                                   // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    58,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 59) || defined(DEMO_CASE))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_FLOAT64,                                   // Input data type
    1024,                                             // Input data length
    DSPLIB_FLOAT64,                                   // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    59,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 60) || defined(DEMO_CASE))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_FLOAT64,                                   // Input data type
    2048,                                             // Input data length
    DSPLIB_FLOAT64,                                   // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    60,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 61) || defined(DEMO_CASE))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_FLOAT64,                                   // Input data type
    4096,                                             // Input data length
    DSPLIB_FLOAT64,                                   // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    61,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 62) || defined(DEMO_CASE))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_FLOAT64,                                   // Input data type
    8192,                                             // Input data length
    DSPLIB_FLOAT64,                                   // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    62,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 63) || defined(DEMO_CASE))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_FLOAT64,                                   // Input data type
    16384,                                            // Input data length
    DSPLIB_FLOAT64,                                   // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    63,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 64) || defined(DEMO_CASE))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input vector 0
    NULL,                                             // Input vector 1
    NULL,                                             // Output vector
    DSPLIB_FLOAT64,                                   // Input data type
    32768,                                            // Input data length
    DSPLIB_FLOAT64,                                   // Output data type
    2,                                                // Output data length
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    64,                                               // test ID
    },
#endif

};

/*
 *  Sends the test parameter structure and number of tests
 */
void
DSPLIB_dotp_sqr_getTestParams (DSPLIB_dotp_sqr_testParams_t ** params, int32_t * numTests)
{
   *params = testParams;
   *numTests = sizeof (testParams) / sizeof (DSPLIB_dotp_sqr_testParams_t);
}
