/******************************************************************************/
/* Copyright (C) 2023 Texas Instruments Incorporated - http://www.ti.com/
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 ******************************************************************************/

#include "VXLIB_meanStdDev_idat.h"
/*This file is autogenerated*/
/*Please do not edit*/

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
#include "test_data/staticRefCase1.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
#include "test_data/staticRefCase2.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
#include "test_data/staticRefCase3.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
#include "test_data/staticRefCase4.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
#include "test_data/staticRefCase5.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
#include "test_data/staticRefCase6.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
#include "test_data/staticRefCase7.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
#include "test_data/staticRefCase8.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
#include "test_data/staticRefCase9.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
#include "test_data/staticRefCase10.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
#include "test_data/staticRefCase11.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12))
#include "test_data/staticRefCase12.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 13))
#include "test_data/staticRefCase13.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 14))
#include "test_data/staticRefCase14.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 15))
#include "test_data/staticRefCase15.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 16))
#include "test_data/staticRefCase16.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 17))
#include "test_data/staticRefCase17.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 18))
#include "test_data/staticRefCase18.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 19))
#include "test_data/staticRefCase19.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 20))
#include "test_data/staticRefCase20.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 21))
#include "test_data/staticRefCase21.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 22))
#include "test_data/staticRefCase22.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 23))
#include "test_data/staticRefCase23.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 24))
#include "test_data/staticRefCase24.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 25))
#include "test_data/staticRefCase25.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 26))
#include "test_data/staticRefCase26.h"
#endif

static VXLIB_meanStdDev_testParams_t testParams[] = {
#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
   {
    STATIC,                                           // Test pattern
    staticRefInCase1,                                 // Input vector
    VXLIB_UINT8,                                      // data type in
    staticRefOut0Case1,                               // Mean Output vector
    staticRefOut1Case1,                               // Standard Deviation Output vector
    VXLIB_FLOAT32,                                    // data type out
    6,                                                // width of image
    6,                                                // height of image
    6 * sizeof (uint8_t),                             // strideIn
    staticRefPixelsProcessedInCase1,                  // number of pixels processed in
    staticRefCurrentSumInCase1,                       // current sum in
    staticRefCurrentSqSumInCase1,                     // current square sum in
    staticRefPixelsProcessedOutCase1,                 // number of pixels processed out
    staticRefCurrentSumOutCase1,                      // current sum out
    staticRefCurrentSqSumOutCase1,                    // current square sum out
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    1,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
   {
    STATIC,                                           // Test pattern
    staticRefInCase2,                                 // Input vector
    VXLIB_UINT8,                                      // data type in
    staticRefOut0Case2,                               // Mean Output vector
    staticRefOut1Case2,                               // Standard Deviation Output vector
    VXLIB_FLOAT32,                                    // data type out
    16,                                               // width of image
    16,                                               // height of image
    16 * sizeof (uint8_t),                            // strideIn
    staticRefPixelsProcessedInCase2,                  // number of pixels processed in
    staticRefCurrentSumInCase2,                       // current sum in
    staticRefCurrentSqSumInCase2,                     // current square sum in
    staticRefPixelsProcessedOutCase2,                 // number of pixels processed out
    staticRefCurrentSumOutCase2,                      // current sum out
    staticRefCurrentSqSumOutCase2,                    // current square sum out
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    2,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
   {
    STATIC,                                           // Test pattern
    staticRefInCase3,                                 // Input vector
    VXLIB_UINT8,                                      // data type in
    staticRefOut0Case3,                               // Mean Output vector
    staticRefOut1Case3,                               // Standard Deviation Output vector
    VXLIB_FLOAT32,                                    // data type out
    32,                                               // width of image
    32,                                               // height of image
    32 * sizeof (uint8_t),                            // strideIn
    staticRefPixelsProcessedInCase3,                  // number of pixels processed in
    staticRefCurrentSumInCase3,                       // current sum in
    staticRefCurrentSqSumInCase3,                     // current square sum in
    staticRefPixelsProcessedOutCase3,                 // number of pixels processed out
    staticRefCurrentSumOutCase3,                      // current sum out
    staticRefCurrentSqSumOutCase3,                    // current square sum out
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    3,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
   {
    STATIC,                                           // Test pattern
    staticRefInCase4,                                 // Input vector
    VXLIB_UINT8,                                      // data type in
    staticRefOut0Case4,                               // Mean Output vector
    staticRefOut1Case4,                               // Standard Deviation Output vector
    VXLIB_FLOAT32,                                    // data type out
    64,                                               // width of image
    64,                                               // height of image
    64 * sizeof (uint8_t),                            // strideIn
    staticRefPixelsProcessedInCase4,                  // number of pixels processed in
    staticRefCurrentSumInCase4,                       // current sum in
    staticRefCurrentSqSumInCase4,                     // current square sum in
    staticRefPixelsProcessedOutCase4,                 // number of pixels processed out
    staticRefCurrentSumOutCase4,                      // current sum out
    staticRefCurrentSqSumOutCase4,                    // current square sum out
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    4,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
   {
    STATIC,                                           // Test pattern
    staticRefInCase5,                                 // Input vector
    VXLIB_UINT8,                                      // data type in
    staticRefOut0Case5,                               // Mean Output vector
    staticRefOut1Case5,                               // Standard Deviation Output vector
    VXLIB_FLOAT32,                                    // data type out
    128,                                              // width of image
    128,                                              // height of image
    128 * sizeof (uint8_t),                           // strideIn
    staticRefPixelsProcessedInCase5,                  // number of pixels processed in
    staticRefCurrentSumInCase5,                       // current sum in
    staticRefCurrentSqSumInCase5,                     // current square sum in
    staticRefPixelsProcessedOutCase5,                 // number of pixels processed out
    staticRefCurrentSumOutCase5,                      // current sum out
    staticRefCurrentSqSumOutCase5,                    // current square sum out
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    5,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
   {
    STATIC,                                           // Test pattern
    staticRefInCase6,                                 // Input vector
    VXLIB_UINT8,                                      // data type in
    staticRefOut0Case6,                               // Mean Output vector
    staticRefOut1Case6,                               // Standard Deviation Output vector
    VXLIB_FLOAT32,                                    // data type out
    256,                                              // width of image
    256,                                              // height of image
    256 * sizeof (uint8_t),                           // strideIn
    staticRefPixelsProcessedInCase6,                  // number of pixels processed in
    staticRefCurrentSumInCase6,                       // current sum in
    staticRefCurrentSqSumInCase6,                     // current square sum in
    staticRefPixelsProcessedOutCase6,                 // number of pixels processed out
    staticRefCurrentSumOutCase6,                      // current sum out
    staticRefCurrentSqSumOutCase6,                    // current square sum out
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    6,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
   {
    STATIC,                                           // Test pattern
    staticRefInCase7,                                 // Input vector
    VXLIB_UINT8,                                      // data type in
    staticRefOut0Case7,                               // Mean Output vector
    staticRefOut1Case7,                               // Standard Deviation Output vector
    VXLIB_FLOAT32,                                    // data type out
    20,                                               // width of image
    23,                                               // height of image
    25 * sizeof (uint8_t),                            // strideIn
    staticRefPixelsProcessedInCase7,                  // number of pixels processed in
    staticRefCurrentSumInCase7,                       // current sum in
    staticRefCurrentSqSumInCase7,                     // current square sum in
    staticRefPixelsProcessedOutCase7,                 // number of pixels processed out
    staticRefCurrentSumOutCase7,                      // current sum out
    staticRefCurrentSqSumOutCase7,                    // current square sum out
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    7,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
   {
    STATIC,                                           // Test pattern
    staticRefInCase8,                                 // Input vector
    VXLIB_UINT8,                                      // data type in
    staticRefOut0Case8,                               // Mean Output vector
    staticRefOut1Case8,                               // Standard Deviation Output vector
    VXLIB_FLOAT32,                                    // data type out
    65,                                               // width of image
    71,                                               // height of image
    75 * sizeof (uint8_t),                            // strideIn
    staticRefPixelsProcessedInCase8,                  // number of pixels processed in
    staticRefCurrentSumInCase8,                       // current sum in
    staticRefCurrentSqSumInCase8,                     // current square sum in
    staticRefPixelsProcessedOutCase8,                 // number of pixels processed out
    staticRefCurrentSumOutCase8,                      // current sum out
    staticRefCurrentSqSumOutCase8,                    // current square sum out
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    8,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
   {
    STATIC,                                           // Test pattern
    staticRefInCase9,                                 // Input vector
    VXLIB_UINT8,                                      // data type in
    staticRefOut0Case9,                               // Mean Output vector
    staticRefOut1Case9,                               // Standard Deviation Output vector
    VXLIB_FLOAT32,                                    // data type out
    123,                                              // width of image
    54,                                               // height of image
    150 * sizeof (uint8_t),                           // strideIn
    staticRefPixelsProcessedInCase9,                  // number of pixels processed in
    staticRefCurrentSumInCase9,                       // current sum in
    staticRefCurrentSqSumInCase9,                     // current square sum in
    staticRefPixelsProcessedOutCase9,                 // number of pixels processed out
    staticRefCurrentSumOutCase9,                      // current sum out
    staticRefCurrentSqSumOutCase9,                    // current square sum out
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    9,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
   {
    STATIC,                                           // Test pattern
    staticRefInCase10,                                // Input vector
    VXLIB_UINT8,                                      // data type in
    staticRefOut0Case10,                              // Mean Output vector
    staticRefOut1Case10,                              // Standard Deviation Output vector
    VXLIB_FLOAT32,                                    // data type out
    200,                                              // width of image
    163,                                              // height of image
    232 * sizeof (uint8_t),                           // strideIn
    staticRefPixelsProcessedInCase10,                 // number of pixels processed in
    staticRefCurrentSumInCase10,                      // current sum in
    staticRefCurrentSqSumInCase10,                    // current square sum in
    staticRefPixelsProcessedOutCase10,                // number of pixels processed out
    staticRefCurrentSumOutCase10,                     // current sum out
    staticRefCurrentSqSumOutCase10,                   // current square sum out
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    10,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
   {
    STATIC,                                           // Test pattern
    staticRefInCase11,                                // Input vector
    VXLIB_UINT8,                                      // data type in
    staticRefOut0Case11,                              // Mean Output vector
    staticRefOut1Case11,                              // Standard Deviation Output vector
    VXLIB_FLOAT32,                                    // data type out
    35,                                               // width of image
    23,                                               // height of image
    43 * sizeof (uint8_t),                            // strideIn
    staticRefPixelsProcessedInCase11,                 // number of pixels processed in
    staticRefCurrentSumInCase11,                      // current sum in
    staticRefCurrentSqSumInCase11,                    // current square sum in
    staticRefPixelsProcessedOutCase11,                // number of pixels processed out
    staticRefCurrentSumOutCase11,                     // current sum out
    staticRefCurrentSqSumOutCase11,                   // current square sum out
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    11,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12))
   {
    STATIC,                                           // Test pattern
    staticRefInCase12,                                // Input vector
    VXLIB_UINT8,                                      // data type in
    staticRefOut0Case12,                              // Mean Output vector
    staticRefOut1Case12,                              // Standard Deviation Output vector
    VXLIB_FLOAT32,                                    // data type out
    62,                                               // width of image
    45,                                               // height of image
    74 * sizeof (uint8_t),                            // strideIn
    staticRefPixelsProcessedInCase12,                 // number of pixels processed in
    staticRefCurrentSumInCase12,                      // current sum in
    staticRefCurrentSqSumInCase12,                    // current square sum in
    staticRefPixelsProcessedOutCase12,                // number of pixels processed out
    staticRefCurrentSumOutCase12,                     // current sum out
    staticRefCurrentSqSumOutCase12,                   // current square sum out
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    12,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 13))
   {
    STATIC,                                           // Test pattern
    staticRefInCase13,                                // Input vector
    VXLIB_UINT8,                                      // data type in
    staticRefOut0Case13,                              // Mean Output vector
    staticRefOut1Case13,                              // Standard Deviation Output vector
    VXLIB_FLOAT32,                                    // data type out
    126,                                              // width of image
    163,                                              // height of image
    232 * sizeof (uint8_t),                           // strideIn
    staticRefPixelsProcessedInCase13,                 // number of pixels processed in
    staticRefCurrentSumInCase13,                      // current sum in
    staticRefCurrentSqSumInCase13,                    // current square sum in
    staticRefPixelsProcessedOutCase13,                // number of pixels processed out
    staticRefCurrentSumOutCase13,                     // current sum out
    staticRefCurrentSqSumOutCase13,                   // current square sum out
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    13,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 14))
   {
    STATIC,                                           // Test pattern
    staticRefInCase14,                                // Input vector
    VXLIB_UINT16,                                     // data type in
    staticRefOut0Case14,                              // Mean Output vector
    staticRefOut1Case14,                              // Standard Deviation Output vector
    VXLIB_FLOAT32,                                    // data type out
    6,                                                // width of image
    6,                                                // height of image
    6 * sizeof (uint16_t),                            // strideIn
    staticRefPixelsProcessedInCase14,                 // number of pixels processed in
    staticRefCurrentSumInCase14,                      // current sum in
    staticRefCurrentSqSumInCase14,                    // current square sum in
    staticRefPixelsProcessedOutCase14,                // number of pixels processed out
    staticRefCurrentSumOutCase14,                     // current sum out
    staticRefCurrentSqSumOutCase14,                   // current square sum out
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    14,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 15))
   {
    STATIC,                                           // Test pattern
    staticRefInCase15,                                // Input vector
    VXLIB_UINT16,                                     // data type in
    staticRefOut0Case15,                              // Mean Output vector
    staticRefOut1Case15,                              // Standard Deviation Output vector
    VXLIB_FLOAT32,                                    // data type out
    16,                                               // width of image
    16,                                               // height of image
    16 * sizeof (uint16_t),                           // strideIn
    staticRefPixelsProcessedInCase15,                 // number of pixels processed in
    staticRefCurrentSumInCase15,                      // current sum in
    staticRefCurrentSqSumInCase15,                    // current square sum in
    staticRefPixelsProcessedOutCase15,                // number of pixels processed out
    staticRefCurrentSumOutCase15,                     // current sum out
    staticRefCurrentSqSumOutCase15,                   // current square sum out
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    15,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 16))
   {
    STATIC,                                           // Test pattern
    staticRefInCase16,                                // Input vector
    VXLIB_UINT16,                                     // data type in
    staticRefOut0Case16,                              // Mean Output vector
    staticRefOut1Case16,                              // Standard Deviation Output vector
    VXLIB_FLOAT32,                                    // data type out
    32,                                               // width of image
    32,                                               // height of image
    32 * sizeof (uint16_t),                           // strideIn
    staticRefPixelsProcessedInCase16,                 // number of pixels processed in
    staticRefCurrentSumInCase16,                      // current sum in
    staticRefCurrentSqSumInCase16,                    // current square sum in
    staticRefPixelsProcessedOutCase16,                // number of pixels processed out
    staticRefCurrentSumOutCase16,                     // current sum out
    staticRefCurrentSqSumOutCase16,                   // current square sum out
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    16,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 17))
   {
    STATIC,                                           // Test pattern
    staticRefInCase17,                                // Input vector
    VXLIB_UINT16,                                     // data type in
    staticRefOut0Case17,                              // Mean Output vector
    staticRefOut1Case17,                              // Standard Deviation Output vector
    VXLIB_FLOAT32,                                    // data type out
    64,                                               // width of image
    64,                                               // height of image
    64 * sizeof (uint16_t),                           // strideIn
    staticRefPixelsProcessedInCase17,                 // number of pixels processed in
    staticRefCurrentSumInCase17,                      // current sum in
    staticRefCurrentSqSumInCase17,                    // current square sum in
    staticRefPixelsProcessedOutCase17,                // number of pixels processed out
    staticRefCurrentSumOutCase17,                     // current sum out
    staticRefCurrentSqSumOutCase17,                   // current square sum out
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    17,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 18))
   {
    STATIC,                                           // Test pattern
    staticRefInCase18,                                // Input vector
    VXLIB_UINT16,                                     // data type in
    staticRefOut0Case18,                              // Mean Output vector
    staticRefOut1Case18,                              // Standard Deviation Output vector
    VXLIB_FLOAT32,                                    // data type out
    128,                                              // width of image
    128,                                              // height of image
    128 * sizeof (uint16_t),                          // strideIn
    staticRefPixelsProcessedInCase18,                 // number of pixels processed in
    staticRefCurrentSumInCase18,                      // current sum in
    staticRefCurrentSqSumInCase18,                    // current square sum in
    staticRefPixelsProcessedOutCase18,                // number of pixels processed out
    staticRefCurrentSumOutCase18,                     // current sum out
    staticRefCurrentSqSumOutCase18,                   // current square sum out
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    18,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 19))
   {
    STATIC,                                           // Test pattern
    staticRefInCase19,                                // Input vector
    VXLIB_UINT16,                                     // data type in
    staticRefOut0Case19,                              // Mean Output vector
    staticRefOut1Case19,                              // Standard Deviation Output vector
    VXLIB_FLOAT32,                                    // data type out
    256,                                              // width of image
    256,                                              // height of image
    256 * sizeof (uint16_t),                          // strideIn
    staticRefPixelsProcessedInCase19,                 // number of pixels processed in
    staticRefCurrentSumInCase19,                      // current sum in
    staticRefCurrentSqSumInCase19,                    // current square sum in
    staticRefPixelsProcessedOutCase19,                // number of pixels processed out
    staticRefCurrentSumOutCase19,                     // current sum out
    staticRefCurrentSqSumOutCase19,                   // current square sum out
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    19,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 20))
   {
    STATIC,                                           // Test pattern
    staticRefInCase20,                                // Input vector
    VXLIB_UINT16,                                     // data type in
    staticRefOut0Case20,                              // Mean Output vector
    staticRefOut1Case20,                              // Standard Deviation Output vector
    VXLIB_FLOAT32,                                    // data type out
    20,                                               // width of image
    23,                                               // height of image
    25 * sizeof (uint16_t),                           // strideIn
    staticRefPixelsProcessedInCase20,                 // number of pixels processed in
    staticRefCurrentSumInCase20,                      // current sum in
    staticRefCurrentSqSumInCase20,                    // current square sum in
    staticRefPixelsProcessedOutCase20,                // number of pixels processed out
    staticRefCurrentSumOutCase20,                     // current sum out
    staticRefCurrentSqSumOutCase20,                   // current square sum out
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    20,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 21))
   {
    STATIC,                                           // Test pattern
    staticRefInCase21,                                // Input vector
    VXLIB_UINT16,                                     // data type in
    staticRefOut0Case21,                              // Mean Output vector
    staticRefOut1Case21,                              // Standard Deviation Output vector
    VXLIB_FLOAT32,                                    // data type out
    65,                                               // width of image
    71,                                               // height of image
    75 * sizeof (uint16_t),                           // strideIn
    staticRefPixelsProcessedInCase21,                 // number of pixels processed in
    staticRefCurrentSumInCase21,                      // current sum in
    staticRefCurrentSqSumInCase21,                    // current square sum in
    staticRefPixelsProcessedOutCase21,                // number of pixels processed out
    staticRefCurrentSumOutCase21,                     // current sum out
    staticRefCurrentSqSumOutCase21,                   // current square sum out
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    21,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 22))
   {
    STATIC,                                           // Test pattern
    staticRefInCase22,                                // Input vector
    VXLIB_UINT16,                                     // data type in
    staticRefOut0Case22,                              // Mean Output vector
    staticRefOut1Case22,                              // Standard Deviation Output vector
    VXLIB_FLOAT32,                                    // data type out
    123,                                              // width of image
    54,                                               // height of image
    150 * sizeof (uint16_t),                          // strideIn
    staticRefPixelsProcessedInCase22,                 // number of pixels processed in
    staticRefCurrentSumInCase22,                      // current sum in
    staticRefCurrentSqSumInCase22,                    // current square sum in
    staticRefPixelsProcessedOutCase22,                // number of pixels processed out
    staticRefCurrentSumOutCase22,                     // current sum out
    staticRefCurrentSqSumOutCase22,                   // current square sum out
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    22,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 23))
   {
    STATIC,                                           // Test pattern
    staticRefInCase23,                                // Input vector
    VXLIB_UINT16,                                     // data type in
    staticRefOut0Case23,                              // Mean Output vector
    staticRefOut1Case23,                              // Standard Deviation Output vector
    VXLIB_FLOAT32,                                    // data type out
    200,                                              // width of image
    163,                                              // height of image
    232 * sizeof (uint16_t),                          // strideIn
    staticRefPixelsProcessedInCase23,                 // number of pixels processed in
    staticRefCurrentSumInCase23,                      // current sum in
    staticRefCurrentSqSumInCase23,                    // current square sum in
    staticRefPixelsProcessedOutCase23,                // number of pixels processed out
    staticRefCurrentSumOutCase23,                     // current sum out
    staticRefCurrentSqSumOutCase23,                   // current square sum out
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    23,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 24))
   {
    STATIC,                                           // Test pattern
    staticRefInCase24,                                // Input vector
    VXLIB_UINT16,                                     // data type in
    staticRefOut0Case24,                              // Mean Output vector
    staticRefOut1Case24,                              // Standard Deviation Output vector
    VXLIB_FLOAT32,                                    // data type out
    35,                                               // width of image
    23,                                               // height of image
    43 * sizeof (uint16_t),                           // strideIn
    staticRefPixelsProcessedInCase24,                 // number of pixels processed in
    staticRefCurrentSumInCase24,                      // current sum in
    staticRefCurrentSqSumInCase24,                    // current square sum in
    staticRefPixelsProcessedOutCase24,                // number of pixels processed out
    staticRefCurrentSumOutCase24,                     // current sum out
    staticRefCurrentSqSumOutCase24,                   // current square sum out
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    24,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 25))
   {
    STATIC,                                           // Test pattern
    staticRefInCase25,                                // Input vector
    VXLIB_UINT16,                                     // data type in
    staticRefOut0Case25,                              // Mean Output vector
    staticRefOut1Case25,                              // Standard Deviation Output vector
    VXLIB_FLOAT32,                                    // data type out
    62,                                               // width of image
    45,                                               // height of image
    74 * sizeof (uint16_t),                           // strideIn
    staticRefPixelsProcessedInCase25,                 // number of pixels processed in
    staticRefCurrentSumInCase25,                      // current sum in
    staticRefCurrentSqSumInCase25,                    // current square sum in
    staticRefPixelsProcessedOutCase25,                // number of pixels processed out
    staticRefCurrentSumOutCase25,                     // current sum out
    staticRefCurrentSqSumOutCase25,                   // current square sum out
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    25,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 26))
   {
    STATIC,                                           // Test pattern
    staticRefInCase26,                                // Input vector
    VXLIB_UINT16,                                     // data type in
    staticRefOut0Case26,                              // Mean Output vector
    staticRefOut1Case26,                              // Standard Deviation Output vector
    VXLIB_FLOAT32,                                    // data type out
    126,                                              // width of image
    163,                                              // height of image
    232 * sizeof (uint16_t),                          // strideIn
    staticRefPixelsProcessedInCase26,                 // number of pixels processed in
    staticRefCurrentSumInCase26,                      // current sum in
    staticRefCurrentSqSumInCase26,                    // current square sum in
    staticRefPixelsProcessedOutCase26,                // number of pixels processed out
    staticRefCurrentSumOutCase26,                     // current sum out
    staticRefCurrentSqSumOutCase26,                   // current square sum out
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    26,                                               // test ID
    },
#endif

};

/*
 *  Sends the test parameter structure and number of tests
 */
void
VXLIB_meanStdDev_getTestParams (VXLIB_meanStdDev_testParams_t ** params, int32_t * numTests)
{
   *params = testParams;
   *numTests = sizeof (testParams) / sizeof (VXLIB_meanStdDev_testParams_t);
}
