/******************************************************************************/
/* Copyright (C) 2023 Texas Instruments Incorporated - http://www.ti.com/
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 ******************************************************************************/

#include "VXLIB_not_idat.h"
/*This file is autogenerated*/
/*Please do not edit*/

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
#include "test_data/staticRefCase1.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
#include "test_data/staticRefCase2.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
#include "test_data/staticRefCase3.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
#include "test_data/staticRefCase4.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
#include "test_data/staticRefCase5.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
#include "test_data/staticRefCase6.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
#include "test_data/staticRefCase7.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
#include "test_data/staticRefCase8.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
#include "test_data/staticRefCase9.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
#include "test_data/staticRefCase10.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
#include "test_data/staticRefCase11.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12))
#include "test_data/staticRefCase12.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 13))
#include "test_data/staticRefCase13.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 14))
#include "test_data/staticRefCase14.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 15))
#include "test_data/staticRefCase15.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 16))
#include "test_data/staticRefCase16.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 17))
#include "test_data/staticRefCase17.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 18))
#include "test_data/staticRefCase18.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 19))
#include "test_data/staticRefCase19.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 20))
#include "test_data/staticRefCase20.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 21))
#include "test_data/staticRefCase21.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 22))
#include "test_data/staticRefCase22.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 23))
#include "test_data/staticRefCase23.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 24))
#include "test_data/staticRefCase24.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 25))
#include "test_data/staticRefCase25.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 26))
#include "test_data/staticRefCase26.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 27))
#include "test_data/staticRefCase27.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 28))
#include "test_data/staticRefCase28.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 29))
#include "test_data/staticRefCase29.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 30))
#include "test_data/staticRefCase30.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 31))
#include "test_data/staticRefCase31.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 32))
#include "test_data/staticRefCase32.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 33))
#include "test_data/staticRefCase33.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 34))
#include "test_data/staticRefCase34.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 35))
#include "test_data/staticRefCase35.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 36))
#include "test_data/staticRefCase36.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 37))
#include "test_data/staticRefCase37.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 38))
#include "test_data/staticRefCase38.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 39))
#include "test_data/staticRefCase39.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 40))
#include "test_data/staticRefCase40.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 41))
#include "test_data/staticRefCase41.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 42))
#include "test_data/staticRefCase42.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 43))
#include "test_data/staticRefCase43.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 44))
#include "test_data/staticRefCase44.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 45))
#include "test_data/staticRefCase45.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 46))
#include "test_data/staticRefCase46.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 47))
#include "test_data/staticRefCase47.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 48))
#include "test_data/staticRefCase48.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 49))
#include "test_data/staticRefCase49.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 50))
#include "test_data/staticRefCase50.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 51))
#include "test_data/staticRefCase51.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 52))
#include "test_data/staticRefCase52.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 53))
#include "test_data/staticRefCase53.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 54))
#include "test_data/staticRefCase54.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 55))
#include "test_data/staticRefCase55.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 56))
#include "test_data/staticRefCase56.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 57))
#include "test_data/staticRefCase57.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 58))
#include "test_data/staticRefCase58.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 59))
#include "test_data/staticRefCase59.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 60))
#include "test_data/staticRefCase60.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 61))
#include "test_data/staticRefCase61.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 62))
#include "test_data/staticRefCase62.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 63))
#include "test_data/staticRefCase63.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 64))
#include "test_data/staticRefCase64.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 65))
#include "test_data/staticRefCase65.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 66))
#include "test_data/staticRefCase66.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 67))
#include "test_data/staticRefCase67.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 68))
#include "test_data/staticRefCase68.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 69))
#include "test_data/staticRefCase69.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 70))
#include "test_data/staticRefCase70.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 71))
#include "test_data/staticRefCase71.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 72))
#include "test_data/staticRefCase72.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 73))
#include "test_data/staticRefCase73.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 74))
#include "test_data/staticRefCase74.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 75))
#include "test_data/staticRefCase75.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 76))
#include "test_data/staticRefCase76.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 77))
#include "test_data/staticRefCase77.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 78))
#include "test_data/staticRefCase78.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 79))
#include "test_data/staticRefCase79.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 80))
#include "test_data/staticRefCase80.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 81))
#include "test_data/staticRefCase81.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 82))
#include "test_data/staticRefCase82.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 83))
#include "test_data/staticRefCase83.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 84))
#include "test_data/staticRefCase84.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 85))
#include "test_data/staticRefCase85.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 86))
#include "test_data/staticRefCase86.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 87))
#include "test_data/staticRefCase87.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 88))
#include "test_data/staticRefCase88.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 89))
#include "test_data/staticRefCase89.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 90))
#include "test_data/staticRefCase90.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 91))
#include "test_data/staticRefCase91.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 92))
#include "test_data/staticRefCase92.h"
#endif

static VXLIB_not_testParams_t testParams[] = {
#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
   {
    STATIC,                                           // Test pattern
    staticRefInCase1,                                 // Input image
    staticRefOutCase1,                                // Output image
    VXLIB_UINT8,                                      // data type
    3,                                                // width of image
    3,                                                // height of image
    3 * sizeof (uint8_t),                             // stride of image
    3 * sizeof (uint8_t),                             // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    1,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
   {
    STATIC,                                           // Test pattern
    staticRefInCase2,                                 // Input image
    staticRefOutCase2,                                // Output image
    VXLIB_UINT8,                                      // data type
    8,                                                // width of image
    8,                                                // height of image
    8 * sizeof (uint8_t),                             // stride of image
    8 * sizeof (uint8_t),                             // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    2,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
   {
    STATIC,                                           // Test pattern
    staticRefInCase3,                                 // Input image
    staticRefOutCase3,                                // Output image
    VXLIB_UINT8,                                      // data type
    16,                                               // width of image
    16,                                               // height of image
    16 * sizeof (uint8_t),                            // stride of image
    16 * sizeof (uint8_t),                            // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    3,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
   {
    STATIC,                                           // Test pattern
    staticRefInCase4,                                 // Input image
    staticRefOutCase4,                                // Output image
    VXLIB_UINT8,                                      // data type
    32,                                               // width of image
    32,                                               // height of image
    32 * sizeof (uint8_t),                            // stride of image
    32 * sizeof (uint8_t),                            // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    4,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
   {
    STATIC,                                           // Test pattern
    staticRefInCase5,                                 // Input image
    staticRefOutCase5,                                // Output image
    VXLIB_UINT8,                                      // data type
    64,                                               // width of image
    64,                                               // height of image
    64 * sizeof (uint8_t),                            // stride of image
    64 * sizeof (uint8_t),                            // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    5,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
   {
    STATIC,                                           // Test pattern
    staticRefInCase6,                                 // Input image
    staticRefOutCase6,                                // Output image
    VXLIB_UINT8,                                      // data type
    128,                                              // width of image
    128,                                              // height of image
    128 * sizeof (uint8_t),                           // stride of image
    128 * sizeof (uint8_t),                           // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    6,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
   {
    STATIC,                                           // Test pattern
    staticRefInCase7,                                 // Input image
    staticRefOutCase7,                                // Output image
    VXLIB_UINT8,                                      // data type
    256,                                              // width of image
    256,                                              // height of image
    256 * sizeof (uint8_t),                           // stride of image
    256 * sizeof (uint8_t),                           // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    7,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
   {
    STATIC,                                           // Test pattern
    staticRefInCase8,                                 // Input image
    staticRefOutCase8,                                // Output image
    VXLIB_UINT8,                                      // data type
    3,                                                // width of image
    3,                                                // height of image
    64 * sizeof (uint8_t),                            // stride of image
    64 * sizeof (uint8_t),                            // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    8,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
   {
    STATIC,                                           // Test pattern
    staticRefInCase9,                                 // Input image
    staticRefOutCase9,                                // Output image
    VXLIB_UINT8,                                      // data type
    8,                                                // width of image
    8,                                                // height of image
    64 * sizeof (uint8_t),                            // stride of image
    64 * sizeof (uint8_t),                            // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    9,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
   {
    STATIC,                                           // Test pattern
    staticRefInCase10,                                // Input image
    staticRefOutCase10,                               // Output image
    VXLIB_UINT8,                                      // data type
    16,                                               // width of image
    16,                                               // height of image
    64 * sizeof (uint8_t),                            // stride of image
    64 * sizeof (uint8_t),                            // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    10,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
   {
    STATIC,                                           // Test pattern
    staticRefInCase11,                                // Input image
    staticRefOutCase11,                               // Output image
    VXLIB_UINT8,                                      // data type
    32,                                               // width of image
    32,                                               // height of image
    64 * sizeof (uint8_t),                            // stride of image
    64 * sizeof (uint8_t),                            // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    11,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12))
   {
    STATIC,                                           // Test pattern
    staticRefInCase12,                                // Input image
    staticRefOutCase12,                               // Output image
    VXLIB_UINT8,                                      // data type
    64,                                               // width of image
    64,                                               // height of image
    128 * sizeof (uint8_t),                           // stride of image
    128 * sizeof (uint8_t),                           // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    12,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 13))
   {
    STATIC,                                           // Test pattern
    staticRefInCase13,                                // Input image
    staticRefOutCase13,                               // Output image
    VXLIB_UINT8,                                      // data type
    128,                                              // width of image
    128,                                              // height of image
    192 * sizeof (uint8_t),                           // stride of image
    192 * sizeof (uint8_t),                           // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    13,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 14))
   {
    STATIC,                                           // Test pattern
    staticRefInCase14,                                // Input image
    staticRefOutCase14,                               // Output image
    VXLIB_UINT8,                                      // data type
    256,                                              // width of image
    256,                                              // height of image
    320 * sizeof (uint8_t),                           // stride of image
    320 * sizeof (uint8_t),                           // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    14,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 15))
   {
    STATIC,                                           // Test pattern
    staticRefInCase15,                                // Input image
    staticRefOutCase15,                               // Output image
    VXLIB_UINT8,                                      // data type
    4,                                                // width of image
    2,                                                // height of image
    64 * sizeof (uint8_t),                            // stride of image
    64 * sizeof (uint8_t),                            // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    15,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 16))
   {
    STATIC,                                           // Test pattern
    staticRefInCase16,                                // Input image
    staticRefOutCase16,                               // Output image
    VXLIB_UINT8,                                      // data type
    3,                                                // width of image
    33,                                               // height of image
    48 * sizeof (uint8_t),                            // stride of image
    48 * sizeof (uint8_t),                            // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    16,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 17))
   {
    STATIC,                                           // Test pattern
    staticRefInCase17,                                // Input image
    staticRefOutCase17,                               // Output image
    VXLIB_UINT8,                                      // data type
    65,                                               // width of image
    33,                                               // height of image
    65 * sizeof (uint8_t),                            // stride of image
    65 * sizeof (uint8_t),                            // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    17,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 18))
   {
    STATIC,                                           // Test pattern
    staticRefInCase18,                                // Input image
    staticRefOutCase18,                               // Output image
    VXLIB_UINT8,                                      // data type
    31,                                               // width of image
    31,                                               // height of image
    31 * sizeof (uint8_t),                            // stride of image
    128 * sizeof (uint8_t),                           // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    18,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 19))
   {
    STATIC,                                           // Test pattern
    staticRefInCase19,                                // Input image
    staticRefOutCase19,                               // Output image
    VXLIB_UINT8,                                      // data type
    65,                                               // width of image
    65,                                               // height of image
    65 * sizeof (uint8_t),                            // stride of image
    65 * sizeof (uint8_t),                            // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    19,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 20))
   {
    STATIC,                                           // Test pattern
    staticRefInCase20,                                // Input image
    staticRefOutCase20,                               // Output image
    VXLIB_UINT8,                                      // data type
    128,                                              // width of image
    128,                                              // height of image
    192 * sizeof (uint8_t),                           // stride of image
    256 * sizeof (uint8_t),                           // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    20,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 21))
   {
    STATIC,                                           // Test pattern
    staticRefInCase21,                                // Input image
    staticRefOutCase21,                               // Output image
    VXLIB_UINT8,                                      // data type
    144,                                              // width of image
    128,                                              // height of image
    144 * sizeof (uint8_t),                           // stride of image
    256 * sizeof (uint8_t),                           // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    21,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 22))
   {
    STATIC,                                           // Test pattern
    staticRefInCase22,                                // Input image
    staticRefOutCase22,                               // Output image
    VXLIB_UINT8,                                      // data type
    10,                                               // width of image
    120,                                              // height of image
    10 * sizeof (uint8_t),                            // stride of image
    10 * sizeof (uint8_t),                            // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    22,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 23))
   {
    STATIC,                                           // Test pattern
    staticRefInCase23,                                // Input image
    staticRefOutCase23,                               // Output image
    VXLIB_UINT8,                                      // data type
    1,                                                // width of image
    1200,                                             // height of image
    10 * sizeof (uint8_t),                            // stride of image
    10 * sizeof (uint8_t),                            // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    23,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 24))
   {
    STATIC,                                           // Test pattern
    staticRefInCase24,                                // Input image
    staticRefOutCase24,                               // Output image
    VXLIB_UINT16,                                     // data type
    3,                                                // width of image
    3,                                                // height of image
    3 * sizeof (uint16_t),                            // stride of image
    3 * sizeof (uint16_t),                            // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    24,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 25))
   {
    STATIC,                                           // Test pattern
    staticRefInCase25,                                // Input image
    staticRefOutCase25,                               // Output image
    VXLIB_UINT16,                                     // data type
    8,                                                // width of image
    8,                                                // height of image
    8 * sizeof (uint16_t),                            // stride of image
    8 * sizeof (uint16_t),                            // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    25,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 26))
   {
    STATIC,                                           // Test pattern
    staticRefInCase26,                                // Input image
    staticRefOutCase26,                               // Output image
    VXLIB_UINT16,                                     // data type
    16,                                               // width of image
    16,                                               // height of image
    16 * sizeof (uint16_t),                           // stride of image
    16 * sizeof (uint16_t),                           // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    26,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 27))
   {
    STATIC,                                           // Test pattern
    staticRefInCase27,                                // Input image
    staticRefOutCase27,                               // Output image
    VXLIB_UINT16,                                     // data type
    32,                                               // width of image
    32,                                               // height of image
    32 * sizeof (uint16_t),                           // stride of image
    32 * sizeof (uint16_t),                           // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    27,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 28))
   {
    STATIC,                                           // Test pattern
    staticRefInCase28,                                // Input image
    staticRefOutCase28,                               // Output image
    VXLIB_UINT16,                                     // data type
    64,                                               // width of image
    64,                                               // height of image
    64 * sizeof (uint16_t),                           // stride of image
    64 * sizeof (uint16_t),                           // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    28,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 29))
   {
    STATIC,                                           // Test pattern
    staticRefInCase29,                                // Input image
    staticRefOutCase29,                               // Output image
    VXLIB_UINT16,                                     // data type
    128,                                              // width of image
    128,                                              // height of image
    128 * sizeof (uint16_t),                          // stride of image
    128 * sizeof (uint16_t),                          // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    29,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 30))
   {
    STATIC,                                           // Test pattern
    staticRefInCase30,                                // Input image
    staticRefOutCase30,                               // Output image
    VXLIB_UINT16,                                     // data type
    256,                                              // width of image
    256,                                              // height of image
    256 * sizeof (uint16_t),                          // stride of image
    256 * sizeof (uint16_t),                          // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    30,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 31))
   {
    STATIC,                                           // Test pattern
    staticRefInCase31,                                // Input image
    staticRefOutCase31,                               // Output image
    VXLIB_UINT16,                                     // data type
    3,                                                // width of image
    3,                                                // height of image
    64 * sizeof (uint16_t),                           // stride of image
    64 * sizeof (uint16_t),                           // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    31,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 32))
   {
    STATIC,                                           // Test pattern
    staticRefInCase32,                                // Input image
    staticRefOutCase32,                               // Output image
    VXLIB_UINT16,                                     // data type
    8,                                                // width of image
    8,                                                // height of image
    64 * sizeof (uint16_t),                           // stride of image
    64 * sizeof (uint16_t),                           // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    32,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 33))
   {
    STATIC,                                           // Test pattern
    staticRefInCase33,                                // Input image
    staticRefOutCase33,                               // Output image
    VXLIB_UINT16,                                     // data type
    16,                                               // width of image
    16,                                               // height of image
    64 * sizeof (uint16_t),                           // stride of image
    64 * sizeof (uint16_t),                           // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    33,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 34))
   {
    STATIC,                                           // Test pattern
    staticRefInCase34,                                // Input image
    staticRefOutCase34,                               // Output image
    VXLIB_UINT16,                                     // data type
    32,                                               // width of image
    32,                                               // height of image
    64 * sizeof (uint16_t),                           // stride of image
    64 * sizeof (uint16_t),                           // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    34,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 35))
   {
    STATIC,                                           // Test pattern
    staticRefInCase35,                                // Input image
    staticRefOutCase35,                               // Output image
    VXLIB_UINT16,                                     // data type
    64,                                               // width of image
    64,                                               // height of image
    128 * sizeof (uint16_t),                          // stride of image
    128 * sizeof (uint16_t),                          // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    35,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 36))
   {
    STATIC,                                           // Test pattern
    staticRefInCase36,                                // Input image
    staticRefOutCase36,                               // Output image
    VXLIB_UINT16,                                     // data type
    128,                                              // width of image
    128,                                              // height of image
    192 * sizeof (uint16_t),                          // stride of image
    192 * sizeof (uint16_t),                          // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    36,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 37))
   {
    STATIC,                                           // Test pattern
    staticRefInCase37,                                // Input image
    staticRefOutCase37,                               // Output image
    VXLIB_UINT16,                                     // data type
    256,                                              // width of image
    256,                                              // height of image
    320 * sizeof (uint16_t),                          // stride of image
    320 * sizeof (uint16_t),                          // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    37,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 38))
   {
    STATIC,                                           // Test pattern
    staticRefInCase38,                                // Input image
    staticRefOutCase38,                               // Output image
    VXLIB_UINT16,                                     // data type
    4,                                                // width of image
    2,                                                // height of image
    64 * sizeof (uint16_t),                           // stride of image
    64 * sizeof (uint16_t),                           // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    38,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 39))
   {
    STATIC,                                           // Test pattern
    staticRefInCase39,                                // Input image
    staticRefOutCase39,                               // Output image
    VXLIB_UINT16,                                     // data type
    3,                                                // width of image
    33,                                               // height of image
    48 * sizeof (uint16_t),                           // stride of image
    48 * sizeof (uint16_t),                           // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    39,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 40))
   {
    STATIC,                                           // Test pattern
    staticRefInCase40,                                // Input image
    staticRefOutCase40,                               // Output image
    VXLIB_UINT16,                                     // data type
    65,                                               // width of image
    33,                                               // height of image
    65 * sizeof (uint16_t),                           // stride of image
    65 * sizeof (uint16_t),                           // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    40,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 41))
   {
    STATIC,                                           // Test pattern
    staticRefInCase41,                                // Input image
    staticRefOutCase41,                               // Output image
    VXLIB_UINT16,                                     // data type
    31,                                               // width of image
    31,                                               // height of image
    31 * sizeof (uint16_t),                           // stride of image
    128 * sizeof (uint16_t),                          // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    41,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 42))
   {
    STATIC,                                           // Test pattern
    staticRefInCase42,                                // Input image
    staticRefOutCase42,                               // Output image
    VXLIB_UINT16,                                     // data type
    65,                                               // width of image
    65,                                               // height of image
    65 * sizeof (uint16_t),                           // stride of image
    65 * sizeof (uint16_t),                           // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    42,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 43))
   {
    STATIC,                                           // Test pattern
    staticRefInCase43,                                // Input image
    staticRefOutCase43,                               // Output image
    VXLIB_UINT16,                                     // data type
    128,                                              // width of image
    128,                                              // height of image
    192 * sizeof (uint16_t),                          // stride of image
    256 * sizeof (uint16_t),                          // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    43,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 44))
   {
    STATIC,                                           // Test pattern
    staticRefInCase44,                                // Input image
    staticRefOutCase44,                               // Output image
    VXLIB_UINT16,                                     // data type
    144,                                              // width of image
    128,                                              // height of image
    144 * sizeof (uint16_t),                          // stride of image
    256 * sizeof (uint16_t),                          // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    44,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 45))
   {
    STATIC,                                           // Test pattern
    staticRefInCase45,                                // Input image
    staticRefOutCase45,                               // Output image
    VXLIB_UINT16,                                     // data type
    10,                                               // width of image
    120,                                              // height of image
    10 * sizeof (uint16_t),                           // stride of image
    10 * sizeof (uint16_t),                           // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    45,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 46))
   {
    STATIC,                                           // Test pattern
    staticRefInCase46,                                // Input image
    staticRefOutCase46,                               // Output image
    VXLIB_UINT16,                                     // data type
    1,                                                // width of image
    1200,                                             // height of image
    10 * sizeof (uint16_t),                           // stride of image
    10 * sizeof (uint16_t),                           // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    46,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 47))
   {
    STATIC,                                           // Test pattern
    staticRefInCase47,                                // Input image
    staticRefOutCase47,                               // Output image
    VXLIB_INT8,                                       // data type
    3,                                                // width of image
    3,                                                // height of image
    3 * sizeof (int8_t),                              // stride of image
    3 * sizeof (int8_t),                              // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    47,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 48))
   {
    STATIC,                                           // Test pattern
    staticRefInCase48,                                // Input image
    staticRefOutCase48,                               // Output image
    VXLIB_INT8,                                       // data type
    8,                                                // width of image
    8,                                                // height of image
    8 * sizeof (int8_t),                              // stride of image
    8 * sizeof (int8_t),                              // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    48,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 49))
   {
    STATIC,                                           // Test pattern
    staticRefInCase49,                                // Input image
    staticRefOutCase49,                               // Output image
    VXLIB_INT8,                                       // data type
    16,                                               // width of image
    16,                                               // height of image
    16 * sizeof (int8_t),                             // stride of image
    16 * sizeof (int8_t),                             // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    49,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 50))
   {
    STATIC,                                           // Test pattern
    staticRefInCase50,                                // Input image
    staticRefOutCase50,                               // Output image
    VXLIB_INT8,                                       // data type
    32,                                               // width of image
    32,                                               // height of image
    32 * sizeof (int8_t),                             // stride of image
    32 * sizeof (int8_t),                             // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    50,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 51))
   {
    STATIC,                                           // Test pattern
    staticRefInCase51,                                // Input image
    staticRefOutCase51,                               // Output image
    VXLIB_INT8,                                       // data type
    64,                                               // width of image
    64,                                               // height of image
    64 * sizeof (int8_t),                             // stride of image
    64 * sizeof (int8_t),                             // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    51,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 52))
   {
    STATIC,                                           // Test pattern
    staticRefInCase52,                                // Input image
    staticRefOutCase52,                               // Output image
    VXLIB_INT8,                                       // data type
    128,                                              // width of image
    128,                                              // height of image
    128 * sizeof (int8_t),                            // stride of image
    128 * sizeof (int8_t),                            // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    52,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 53))
   {
    STATIC,                                           // Test pattern
    staticRefInCase53,                                // Input image
    staticRefOutCase53,                               // Output image
    VXLIB_INT8,                                       // data type
    256,                                              // width of image
    256,                                              // height of image
    256 * sizeof (int8_t),                            // stride of image
    256 * sizeof (int8_t),                            // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    53,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 54))
   {
    STATIC,                                           // Test pattern
    staticRefInCase54,                                // Input image
    staticRefOutCase54,                               // Output image
    VXLIB_INT8,                                       // data type
    3,                                                // width of image
    3,                                                // height of image
    64 * sizeof (int8_t),                             // stride of image
    64 * sizeof (int8_t),                             // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    54,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 55))
   {
    STATIC,                                           // Test pattern
    staticRefInCase55,                                // Input image
    staticRefOutCase55,                               // Output image
    VXLIB_INT8,                                       // data type
    8,                                                // width of image
    8,                                                // height of image
    64 * sizeof (int8_t),                             // stride of image
    64 * sizeof (int8_t),                             // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    55,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 56))
   {
    STATIC,                                           // Test pattern
    staticRefInCase56,                                // Input image
    staticRefOutCase56,                               // Output image
    VXLIB_INT8,                                       // data type
    16,                                               // width of image
    16,                                               // height of image
    64 * sizeof (int8_t),                             // stride of image
    64 * sizeof (int8_t),                             // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    56,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 57))
   {
    STATIC,                                           // Test pattern
    staticRefInCase57,                                // Input image
    staticRefOutCase57,                               // Output image
    VXLIB_INT8,                                       // data type
    32,                                               // width of image
    32,                                               // height of image
    64 * sizeof (int8_t),                             // stride of image
    64 * sizeof (int8_t),                             // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    57,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 58))
   {
    STATIC,                                           // Test pattern
    staticRefInCase58,                                // Input image
    staticRefOutCase58,                               // Output image
    VXLIB_INT8,                                       // data type
    64,                                               // width of image
    64,                                               // height of image
    128 * sizeof (int8_t),                            // stride of image
    128 * sizeof (int8_t),                            // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    58,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 59))
   {
    STATIC,                                           // Test pattern
    staticRefInCase59,                                // Input image
    staticRefOutCase59,                               // Output image
    VXLIB_INT8,                                       // data type
    128,                                              // width of image
    128,                                              // height of image
    192 * sizeof (int8_t),                            // stride of image
    192 * sizeof (int8_t),                            // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    59,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 60))
   {
    STATIC,                                           // Test pattern
    staticRefInCase60,                                // Input image
    staticRefOutCase60,                               // Output image
    VXLIB_INT8,                                       // data type
    256,                                              // width of image
    256,                                              // height of image
    320 * sizeof (int8_t),                            // stride of image
    320 * sizeof (int8_t),                            // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    60,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 61))
   {
    STATIC,                                           // Test pattern
    staticRefInCase61,                                // Input image
    staticRefOutCase61,                               // Output image
    VXLIB_INT8,                                       // data type
    4,                                                // width of image
    2,                                                // height of image
    64 * sizeof (int8_t),                             // stride of image
    64 * sizeof (int8_t),                             // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    61,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 62))
   {
    STATIC,                                           // Test pattern
    staticRefInCase62,                                // Input image
    staticRefOutCase62,                               // Output image
    VXLIB_INT8,                                       // data type
    3,                                                // width of image
    33,                                               // height of image
    48 * sizeof (int8_t),                             // stride of image
    48 * sizeof (int8_t),                             // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    62,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 63))
   {
    STATIC,                                           // Test pattern
    staticRefInCase63,                                // Input image
    staticRefOutCase63,                               // Output image
    VXLIB_INT8,                                       // data type
    65,                                               // width of image
    33,                                               // height of image
    65 * sizeof (int8_t),                             // stride of image
    65 * sizeof (int8_t),                             // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    63,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 64))
   {
    STATIC,                                           // Test pattern
    staticRefInCase64,                                // Input image
    staticRefOutCase64,                               // Output image
    VXLIB_INT8,                                       // data type
    31,                                               // width of image
    31,                                               // height of image
    31 * sizeof (int8_t),                             // stride of image
    128 * sizeof (int8_t),                            // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    64,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 65))
   {
    STATIC,                                           // Test pattern
    staticRefInCase65,                                // Input image
    staticRefOutCase65,                               // Output image
    VXLIB_INT8,                                       // data type
    65,                                               // width of image
    65,                                               // height of image
    65 * sizeof (int8_t),                             // stride of image
    65 * sizeof (int8_t),                             // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    65,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 66))
   {
    STATIC,                                           // Test pattern
    staticRefInCase66,                                // Input image
    staticRefOutCase66,                               // Output image
    VXLIB_INT8,                                       // data type
    128,                                              // width of image
    128,                                              // height of image
    192 * sizeof (int8_t),                            // stride of image
    256 * sizeof (int8_t),                            // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    66,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 67))
   {
    STATIC,                                           // Test pattern
    staticRefInCase67,                                // Input image
    staticRefOutCase67,                               // Output image
    VXLIB_INT8,                                       // data type
    144,                                              // width of image
    128,                                              // height of image
    144 * sizeof (int8_t),                            // stride of image
    256 * sizeof (int8_t),                            // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    67,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 68))
   {
    STATIC,                                           // Test pattern
    staticRefInCase68,                                // Input image
    staticRefOutCase68,                               // Output image
    VXLIB_INT8,                                       // data type
    10,                                               // width of image
    120,                                              // height of image
    10 * sizeof (int8_t),                             // stride of image
    10 * sizeof (int8_t),                             // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    68,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 69))
   {
    STATIC,                                           // Test pattern
    staticRefInCase69,                                // Input image
    staticRefOutCase69,                               // Output image
    VXLIB_INT8,                                       // data type
    1,                                                // width of image
    1200,                                             // height of image
    10 * sizeof (int8_t),                             // stride of image
    10 * sizeof (int8_t),                             // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    69,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 70))
   {
    STATIC,                                           // Test pattern
    staticRefInCase70,                                // Input image
    staticRefOutCase70,                               // Output image
    VXLIB_INT16,                                      // data type
    3,                                                // width of image
    3,                                                // height of image
    3 * sizeof (int16_t),                             // stride of image
    3 * sizeof (int16_t),                             // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    70,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 71))
   {
    STATIC,                                           // Test pattern
    staticRefInCase71,                                // Input image
    staticRefOutCase71,                               // Output image
    VXLIB_INT16,                                      // data type
    8,                                                // width of image
    8,                                                // height of image
    8 * sizeof (int16_t),                             // stride of image
    8 * sizeof (int16_t),                             // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    71,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 72))
   {
    STATIC,                                           // Test pattern
    staticRefInCase72,                                // Input image
    staticRefOutCase72,                               // Output image
    VXLIB_INT16,                                      // data type
    16,                                               // width of image
    16,                                               // height of image
    16 * sizeof (int16_t),                            // stride of image
    16 * sizeof (int16_t),                            // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    72,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 73))
   {
    STATIC,                                           // Test pattern
    staticRefInCase73,                                // Input image
    staticRefOutCase73,                               // Output image
    VXLIB_INT16,                                      // data type
    32,                                               // width of image
    32,                                               // height of image
    32 * sizeof (int16_t),                            // stride of image
    32 * sizeof (int16_t),                            // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    73,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 74))
   {
    STATIC,                                           // Test pattern
    staticRefInCase74,                                // Input image
    staticRefOutCase74,                               // Output image
    VXLIB_INT16,                                      // data type
    64,                                               // width of image
    64,                                               // height of image
    64 * sizeof (int16_t),                            // stride of image
    64 * sizeof (int16_t),                            // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    74,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 75))
   {
    STATIC,                                           // Test pattern
    staticRefInCase75,                                // Input image
    staticRefOutCase75,                               // Output image
    VXLIB_INT16,                                      // data type
    128,                                              // width of image
    128,                                              // height of image
    128 * sizeof (int16_t),                           // stride of image
    128 * sizeof (int16_t),                           // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    75,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 76))
   {
    STATIC,                                           // Test pattern
    staticRefInCase76,                                // Input image
    staticRefOutCase76,                               // Output image
    VXLIB_INT16,                                      // data type
    256,                                              // width of image
    256,                                              // height of image
    256 * sizeof (int16_t),                           // stride of image
    256 * sizeof (int16_t),                           // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    76,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 77))
   {
    STATIC,                                           // Test pattern
    staticRefInCase77,                                // Input image
    staticRefOutCase77,                               // Output image
    VXLIB_INT16,                                      // data type
    3,                                                // width of image
    3,                                                // height of image
    64 * sizeof (int16_t),                            // stride of image
    64 * sizeof (int16_t),                            // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    77,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 78))
   {
    STATIC,                                           // Test pattern
    staticRefInCase78,                                // Input image
    staticRefOutCase78,                               // Output image
    VXLIB_INT16,                                      // data type
    8,                                                // width of image
    8,                                                // height of image
    64 * sizeof (int16_t),                            // stride of image
    64 * sizeof (int16_t),                            // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    78,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 79))
   {
    STATIC,                                           // Test pattern
    staticRefInCase79,                                // Input image
    staticRefOutCase79,                               // Output image
    VXLIB_INT16,                                      // data type
    16,                                               // width of image
    16,                                               // height of image
    64 * sizeof (int16_t),                            // stride of image
    64 * sizeof (int16_t),                            // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    79,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 80))
   {
    STATIC,                                           // Test pattern
    staticRefInCase80,                                // Input image
    staticRefOutCase80,                               // Output image
    VXLIB_INT16,                                      // data type
    32,                                               // width of image
    32,                                               // height of image
    64 * sizeof (int16_t),                            // stride of image
    64 * sizeof (int16_t),                            // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    80,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 81))
   {
    STATIC,                                           // Test pattern
    staticRefInCase81,                                // Input image
    staticRefOutCase81,                               // Output image
    VXLIB_INT16,                                      // data type
    64,                                               // width of image
    64,                                               // height of image
    128 * sizeof (int16_t),                           // stride of image
    128 * sizeof (int16_t),                           // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    81,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 82))
   {
    STATIC,                                           // Test pattern
    staticRefInCase82,                                // Input image
    staticRefOutCase82,                               // Output image
    VXLIB_INT16,                                      // data type
    128,                                              // width of image
    128,                                              // height of image
    192 * sizeof (int16_t),                           // stride of image
    192 * sizeof (int16_t),                           // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    82,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 83))
   {
    STATIC,                                           // Test pattern
    staticRefInCase83,                                // Input image
    staticRefOutCase83,                               // Output image
    VXLIB_INT16,                                      // data type
    256,                                              // width of image
    256,                                              // height of image
    320 * sizeof (int16_t),                           // stride of image
    320 * sizeof (int16_t),                           // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    83,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 84))
   {
    STATIC,                                           // Test pattern
    staticRefInCase84,                                // Input image
    staticRefOutCase84,                               // Output image
    VXLIB_INT16,                                      // data type
    4,                                                // width of image
    2,                                                // height of image
    64 * sizeof (int16_t),                            // stride of image
    64 * sizeof (int16_t),                            // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    84,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 85))
   {
    STATIC,                                           // Test pattern
    staticRefInCase85,                                // Input image
    staticRefOutCase85,                               // Output image
    VXLIB_INT16,                                      // data type
    3,                                                // width of image
    33,                                               // height of image
    48 * sizeof (int16_t),                            // stride of image
    48 * sizeof (int16_t),                            // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    85,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 86))
   {
    STATIC,                                           // Test pattern
    staticRefInCase86,                                // Input image
    staticRefOutCase86,                               // Output image
    VXLIB_INT16,                                      // data type
    65,                                               // width of image
    33,                                               // height of image
    65 * sizeof (int16_t),                            // stride of image
    65 * sizeof (int16_t),                            // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    86,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 87))
   {
    STATIC,                                           // Test pattern
    staticRefInCase87,                                // Input image
    staticRefOutCase87,                               // Output image
    VXLIB_INT16,                                      // data type
    31,                                               // width of image
    31,                                               // height of image
    31 * sizeof (int16_t),                            // stride of image
    128 * sizeof (int16_t),                           // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    87,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 88))
   {
    STATIC,                                           // Test pattern
    staticRefInCase88,                                // Input image
    staticRefOutCase88,                               // Output image
    VXLIB_INT16,                                      // data type
    65,                                               // width of image
    65,                                               // height of image
    65 * sizeof (int16_t),                            // stride of image
    65 * sizeof (int16_t),                            // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    88,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 89))
   {
    STATIC,                                           // Test pattern
    staticRefInCase89,                                // Input image
    staticRefOutCase89,                               // Output image
    VXLIB_INT16,                                      // data type
    128,                                              // width of image
    128,                                              // height of image
    192 * sizeof (int16_t),                           // stride of image
    256 * sizeof (int16_t),                           // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    89,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 90))
   {
    STATIC,                                           // Test pattern
    staticRefInCase90,                                // Input image
    staticRefOutCase90,                               // Output image
    VXLIB_INT16,                                      // data type
    144,                                              // width of image
    128,                                              // height of image
    144 * sizeof (int16_t),                           // stride of image
    256 * sizeof (int16_t),                           // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    90,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 91))
   {
    STATIC,                                           // Test pattern
    staticRefInCase91,                                // Input image
    staticRefOutCase91,                               // Output image
    VXLIB_INT16,                                      // data type
    10,                                               // width of image
    120,                                              // height of image
    10 * sizeof (int16_t),                            // stride of image
    10 * sizeof (int16_t),                            // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    91,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 92))
   {
    STATIC,                                           // Test pattern
    staticRefInCase92,                                // Input image
    staticRefOutCase92,                               // Output image
    VXLIB_INT16,                                      // data type
    1,                                                // width of image
    1200,                                             // height of image
    10 * sizeof (int16_t),                            // stride of image
    10 * sizeof (int16_t),                            // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    92,                                               // test ID
    },
#endif

};

/*
 *  Sends the test parameter structure and number of tests
 */
void
VXLIB_not_getTestParams (VXLIB_not_testParams_t ** params, int32_t * numTests)
{
   *params = testParams;
   *numTests = sizeof (testParams) / sizeof (VXLIB_not_testParams_t);
}
