/******************************************************************************/
/* Copyright (C) 2023 Texas Instruments Incorporated - http://www.ti.com/
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 ******************************************************************************/

#include "VXLIB_addWeight_idat.h"
/*This file is autogenerated*/
/*Please do not edit*/

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
#include "test_data/staticRefCase1.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
#include "test_data/staticRefCase2.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
#include "test_data/staticRefCase3.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
#include "test_data/staticRefCase4.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
#include "test_data/staticRefCase5.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
#include "test_data/staticRefCase6.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
#include "test_data/staticRefCase7.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
#include "test_data/staticRefCase8.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
#include "test_data/staticRefCase9.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
#include "test_data/staticRefCase10.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
#include "test_data/staticRefCase11.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12))
#include "test_data/staticRefCase12.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 13))
#include "test_data/staticRefCase13.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 14))
#include "test_data/staticRefCase14.h"
#endif

static VXLIB_addWeight_testParams_t testParams[] = {
#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
   STATIC,                                            // Test pattern
   staticRefIn0Case1,                                 // Input vector 0
   VXLIB_UINT8,                                       // data type in0
   staticRefIn1Case1,                                 // Input vector 1
   VXLIB_UINT8,                                       // data type in1
   staticRefOutCase1,                                 // Output vector
   VXLIB_UINT8,                                       // data type out
   0.2973552986974789,                                // Alpha scalar
   256,                                               // width of image
   256,                                               // height of image
   256 * sizeof (uint8_t),                            // strideIn0
   256 * sizeof (uint8_t),                            // strideIn1
   256 * sizeof (uint8_t),                            // strideOut
   VXLIB_TEST_OUTPUT_MSMC,                            // Output data location
   1,                                                 // number of reps.
   1,                                                 // test ID
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
   STATIC,                                            // Test pattern
   staticRefIn0Case2,                                 // Input vector 0
   VXLIB_UINT8,                                       // data type in0
   staticRefIn1Case2,                                 // Input vector 1
   VXLIB_UINT8,                                       // data type in1
   staticRefOutCase2,                                 // Output vector
   VXLIB_UINT8,                                       // data type out
   0.2635112804061174,                                // Alpha scalar
   128,                                               // width of image
   128,                                               // height of image
   128 * sizeof (uint8_t),                            // strideIn0
   128 * sizeof (uint8_t),                            // strideIn1
   128 * sizeof (uint8_t),                            // strideOut
   VXLIB_TEST_OUTPUT_MSMC,                            // Output data location
   1,                                                 // number of reps.
   2,                                                 // test ID
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
   STATIC,                                            // Test pattern
   staticRefIn0Case3,                                 // Input vector 0
   VXLIB_UINT8,                                       // data type in0
   staticRefIn1Case3,                                 // Input vector 1
   VXLIB_UINT8,                                       // data type in1
   staticRefOutCase3,                                 // Output vector
   VXLIB_UINT8,                                       // data type out
   0.43886776419494655,                               // Alpha scalar
   64,                                                // width of image
   64,                                                // height of image
   64 * sizeof (uint8_t),                             // strideIn0
   64 * sizeof (uint8_t),                             // strideIn1
   64 * sizeof (uint8_t),                             // strideOut
   VXLIB_TEST_OUTPUT_MSMC,                            // Output data location
   1,                                                 // number of reps.
   3,                                                 // test ID
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
   STATIC,                                            // Test pattern
   staticRefIn0Case4,                                 // Input vector 0
   VXLIB_UINT8,                                       // data type in0
   staticRefIn1Case4,                                 // Input vector 1
   VXLIB_UINT8,                                       // data type in1
   staticRefOutCase4,                                 // Output vector
   VXLIB_UINT8,                                       // data type out
   0.5152138104383917,                                // Alpha scalar
   32,                                                // width of image
   32,                                                // height of image
   32 * sizeof (uint8_t),                             // strideIn0
   32 * sizeof (uint8_t),                             // strideIn1
   32 * sizeof (uint8_t),                             // strideOut
   VXLIB_TEST_OUTPUT_MSMC,                            // Output data location
   1,                                                 // number of reps.
   4,                                                 // test ID
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
   STATIC,                                            // Test pattern
   staticRefIn0Case5,                                 // Input vector 0
   VXLIB_UINT8,                                       // data type in0
   staticRefIn1Case5,                                 // Input vector 1
   VXLIB_UINT8,                                       // data type in1
   staticRefOutCase5,                                 // Output vector
   VXLIB_UINT8,                                       // data type out
   0.03461886627740751,                               // Alpha scalar
   16,                                                // width of image
   16,                                                // height of image
   16 * sizeof (uint8_t),                             // strideIn0
   16 * sizeof (uint8_t),                             // strideIn1
   16 * sizeof (uint8_t),                             // strideOut
   VXLIB_TEST_OUTPUT_MSMC,                            // Output data location
   1,                                                 // number of reps.
   5,                                                 // test ID
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
   STATIC,                                            // Test pattern
   staticRefIn0Case6,                                 // Input vector 0
   VXLIB_UINT8,                                       // data type in0
   staticRefIn1Case6,                                 // Input vector 1
   VXLIB_UINT8,                                       // data type in1
   staticRefOutCase6,                                 // Output vector
   VXLIB_UINT8,                                       // data type out
   0.4603192180527146,                                // Alpha scalar
   8,                                                 // width of image
   8,                                                 // height of image
   8 * sizeof (uint8_t),                              // strideIn0
   8 * sizeof (uint8_t),                              // strideIn1
   8 * sizeof (uint8_t),                              // strideOut
   VXLIB_TEST_OUTPUT_MSMC,                            // Output data location
   1,                                                 // number of reps.
   6,                                                 // test ID
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
   STATIC,                                            // Test pattern
   staticRefIn0Case7,                                 // Input vector 0
   VXLIB_UINT8,                                       // data type in0
   staticRefIn1Case7,                                 // Input vector 1
   VXLIB_UINT8,                                       // data type in1
   staticRefOutCase7,                                 // Output vector
   VXLIB_UINT8,                                       // data type out
   0.8828520735472989,                                // Alpha scalar
   128,                                               // width of image
   32,                                                // height of image
   160 * sizeof (uint8_t),                            // strideIn0
   160 * sizeof (uint8_t),                            // strideIn1
   160 * sizeof (uint8_t),                            // strideOut
   VXLIB_TEST_OUTPUT_MSMC,                            // Output data location
   1,                                                 // number of reps.
   7,                                                 // test ID
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
   STATIC,                                            // Test pattern
   staticRefIn0Case8,                                 // Input vector 0
   VXLIB_UINT8,                                       // data type in0
   staticRefIn1Case8,                                 // Input vector 1
   VXLIB_UINT8,                                       // data type in1
   staticRefOutCase8,                                 // Output vector
   VXLIB_UINT8,                                       // data type out
   0.44654534154265446,                               // Alpha scalar
   130,                                               // width of image
   32,                                                // height of image
   178 * sizeof (uint8_t),                            // strideIn0
   178 * sizeof (uint8_t),                            // strideIn1
   178 * sizeof (uint8_t),                            // strideOut
   VXLIB_TEST_OUTPUT_MSMC,                            // Output data location
   1,                                                 // number of reps.
   8,                                                 // test ID
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
   STATIC,                                            // Test pattern
   staticRefIn0Case9,                                 // Input vector 0
   VXLIB_UINT8,                                       // data type in0
   staticRefIn1Case9,                                 // Input vector 1
   VXLIB_UINT8,                                       // data type in1
   staticRefOutCase9,                                 // Output vector
   VXLIB_UINT8,                                       // data type out
   0.3958255092680437,                                // Alpha scalar
   78,                                                // width of image
   32,                                                // height of image
   78 * sizeof (uint8_t),                             // strideIn0
   78 * sizeof (uint8_t),                             // strideIn1
   100 * sizeof (uint8_t),                            // strideOut
   VXLIB_TEST_OUTPUT_MSMC,                            // Output data location
   1,                                                 // number of reps.
   9,                                                 // test ID
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
   STATIC,                                            // Test pattern
   staticRefIn0Case10,                                // Input vector 0
   VXLIB_UINT8,                                       // data type in0
   staticRefIn1Case10,                                // Input vector 1
   VXLIB_UINT8,                                       // data type in1
   staticRefOutCase10,                                // Output vector
   VXLIB_UINT8,                                       // data type out
   0.6470302170408839,                                // Alpha scalar
   128,                                               // width of image
   64,                                                // height of image
   160 * sizeof (uint8_t),                            // strideIn0
   130 * sizeof (uint8_t),                            // strideIn1
   178 * sizeof (uint8_t),                            // strideOut
   VXLIB_TEST_OUTPUT_MSMC,                            // Output data location
   1,                                                 // number of reps.
   10,                                                // test ID
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
   STATIC,                                            // Test pattern
   staticRefIn0Case11,                                // Input vector 0
   VXLIB_UINT8,                                       // data type in0
   staticRefIn1Case11,                                // Input vector 1
   VXLIB_UINT8,                                       // data type in1
   staticRefOutCase11,                                // Output vector
   VXLIB_UINT8,                                       // data type out
   0.6741270995718258,                                // Alpha scalar
   78,                                                // width of image
   32,                                                // height of image
   83 * sizeof (uint8_t),                             // strideIn0
   96 * sizeof (uint8_t),                             // strideIn1
   100 * sizeof (uint8_t),                            // strideOut
   VXLIB_TEST_OUTPUT_MSMC,                            // Output data location
   1,                                                 // number of reps.
   11,                                                // test ID
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12))
   STATIC,                                            // Test pattern
   staticRefIn0Case12,                                // Input vector 0
   VXLIB_UINT8,                                       // data type in0
   staticRefIn1Case12,                                // Input vector 1
   VXLIB_UINT8,                                       // data type in1
   staticRefOutCase12,                                // Output vector
   VXLIB_UINT8,                                       // data type out
   0.6791775871148741,                                // Alpha scalar
   1,                                                 // width of image
   2,                                                 // height of image
   1 * sizeof (uint8_t),                              // strideIn0
   1 * sizeof (uint8_t),                              // strideIn1
   1 * sizeof (uint8_t),                              // strideOut
   VXLIB_TEST_OUTPUT_MSMC,                            // Output data location
   1,                                                 // number of reps.
   12,                                                // test ID
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 13))
   STATIC,                                            // Test pattern
   staticRefIn0Case13,                                // Input vector 0
   VXLIB_UINT8,                                       // data type in0
   staticRefIn1Case13,                                // Input vector 1
   VXLIB_UINT8,                                       // data type in1
   staticRefOutCase13,                                // Output vector
   VXLIB_UINT8,                                       // data type out
   0.8842614202001936,                                // Alpha scalar
   1,                                                 // width of image
   1,                                                 // height of image
   32 * sizeof (uint8_t),                             // strideIn0
   64 * sizeof (uint8_t),                             // strideIn1
   128 * sizeof (uint8_t),                            // strideOut
   VXLIB_TEST_OUTPUT_MSMC,                            // Output data location
   1,                                                 // number of reps.
   13,                                                // test ID
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 14))
   STATIC,                                            // Test pattern
   staticRefIn0Case14,                                // Input vector 0
   VXLIB_UINT8,                                       // data type in0
   staticRefIn1Case14,                                // Input vector 1
   VXLIB_UINT8,                                       // data type in1
   staticRefOutCase14,                                // Output vector
   VXLIB_UINT8,                                       // data type out
   0.25519929818969467,                               // Alpha scalar
   3,                                                 // width of image
   3,                                                 // height of image
   64 * sizeof (uint8_t),                             // strideIn0
   32 * sizeof (uint8_t),                             // strideIn1
   16 * sizeof (uint8_t),                             // strideOut
   VXLIB_TEST_OUTPUT_MSMC,                            // Output data location
   1,                                                 // number of reps.
   14,                                                // test ID
#endif

};

/*
 *  Sends the test parameter structure and number of tests
 */
void
VXLIB_addWeight_getTestParams (VXLIB_addWeight_testParams_t ** params, int32_t * numTests)
{
   *params = testParams;
   *numTests = sizeof (testParams) / sizeof (VXLIB_addWeight_testParams_t);
}
