from __future__ import print_function
from subprocess import call
from sys import platform

import sys
import numpy as np
import csv


sys.path.append("../common")
import VXLIB_utils
import file_io


def gen_testCaseParams(testParamsFile, currPrm):
    """Generate and write test case parameters to idat file

    Args:
        param1 (file object): Input file object to idat.c file
        param2 (dict object): Dict object with test case parameter

    """

    testId = currPrm["ID"]
    dTypeIn0 = currPrm["dTypeIn0"]
    width = currPrm["width"]
    height = currPrm["height"]
    strideIn0 = currPrm["strideIn0"]
    strideIn1 = currPrm["strideIn1"]
    strideOut = currPrm["strideOut"]
    testType = currPrm["testType"]
    demoCase = currPrm["demoCase"]
    numReps = currPrm["numReps"]
    outputDataLocation = currPrm["outputDataLocation"]

    if testType == "STATIC":
        in0 = "staticRefIn0Case" + testId
        in1 = "staticRefIn1Case" + testId
        out = "staticRefOutCase" + testId
    else:
        in0 = "NULL"
        in1 = "NULL"
        out = "NULL"

    if demoCase == "true":
        testParamsFile.write(
            "#if (defined(ALL_TEST_CASES) || (TEST_CASE == %d) || defined(DEMO_CASE))\n"
            % (int(testId))
        )
    else:
        testParamsFile.write(
            "#if (defined(ALL_TEST_CASES) || (TEST_CASE == %d))\n" % (int(testId))
        )

    idatFile.write("{\n")
    idatFile.write("%s, // Test pattern \n" % ((testType)))
    idatFile.write("%s, // Input image 0 \n" % ((in0)))
    idatFile.write("%s, // Input image 1 \n" % ((in1)))
    idatFile.write("%s, // Output image \n" % ((out)))
    idatFile.write("%s, // data type \n" % (VXLIB_utils.resolveVXLIBDType(dTypeIn0)))
    idatFile.write("%d, // width of image \n" % ((width)))
    idatFile.write("%d, // height of image \n" % ((height)))
    idatFile.write(
        "%d* sizeof(%s), // stride of image 0 \n" % ((strideIn0), (dTypeIn0))
    )
    idatFile.write(
        "%d* sizeof(%s), // stride of image 1 \n" % ((strideIn1), (dTypeIn0))
    )
    idatFile.write(
        "%d* sizeof(%s), // stride of output image \n" % ((strideOut), (dTypeIn0))
    )
    idatFile.write("%s, // Output data location \n" % (outputDataLocation))
    idatFile.write("%d, // number of reps. \n" % (int(numReps)))
    idatFile.write("%d, // test ID\n" % int(testId))
    idatFile.write("},\n")
    idatFile.write("#endif")
    idatFile.write("\n\n")


def gen_idat_file(idatFile, testCases):
    """Generate the idat file

    Args:
        param1 (file object): Input file object to idat.c file
        param2 (dict object): Dict object with test case parameter

    """

    fIn = open("../common/ti_lice_header_idat.txt", "r")
    lines = fIn.readlines()
    fIn.close()
    idatFile.writelines(lines)
    includeString = '#include "VXLIB_and_idat.h"'
    idatFile.writelines(includeString)
    idatFile.write("\n")
    idatFile.write("/*This file is autogenerated*/\n")
    idatFile.write("/*Please do not edit*/\n")
    idatFile.write("\n\n")
    # generate ifdefs for header files
    for testCase in testCases:
        if testCase["testType"] == "STATIC":
            VXLIB_utils.gen_ifdefs(idatFile, testCase)

    # generate parameters for test cases
    idatFile.write("static VXLIB_and_testParams_t testParams[] =  ")
    idatFile.write("{\n")

    for testCase in testCases:
        gen_testCaseParams(idatFile, testCase)

    idatFile.write("};\n\n")
    fIn = open("test_param_function.txt", "r")
    lines = fIn.readlines()

    idatFile.writelines(lines)


def process_test_case(testCase):
    """Convert str to int for necessary parameters

    Args:
        Param1(:obj: dict) : Dictionary object with test case parameters

    Returns:
        Obj: Dictionary object with necessary parameters converted to int

    """

    # print(testCase.keys())
    testCase["testId"] = int(testCase["ID"])
    testCase["width"] = int(testCase["width"])
    testCase["height"] = int(testCase["height"])
    testCase["strideIn0"] = int(testCase["strideIn0"])
    testCase["strideIn1"] = int(testCase["strideIn1"])
    testCase["strideOut"] = int(testCase["strideOut"])

    return testCase


def gen_test_case_header_file(testCase):
    """Generate test case and write out input, filter, and output tensor
    into a header file usable in C/C++ code.

    Args:
        param1 (:obj: dict): A dict object with all the test case
        parameters

    Returns:
        [int int]: Minimum and maximum value in output feature tensor

    """

    ##############################
    # Get test parameter of case #
    ##############################

    testId = testCase["ID"]
    width = testCase["width"]
    height = testCase["height"]
    dTypeIn0 = testCase["dTypeIn0"]

    [minValIn, maxValIn] = VXLIB_utils.resolveDTypeLimits(dTypeIn0)

    in0 = np.random.uniform(low=minValIn, high=maxValIn, size=(height, width)).astype(
        np.uint8
    )
    in1 = np.random.uniform(low=minValIn, high=maxValIn, size=(height, width)).astype(
        np.uint8
    )

    out = np.bitwise_and(in0, in1)

    headerFileName = "staticRefCase" + str(testId) + ".h"
    file_io.write_header_file(in0, in1, out, testCase, headerFileName)

    return [np.min(out), np.max(out)]


# CSV file with paratmeters for all test cases
testCasesCsvFile = "test_cases_list.csv"
testIdList = []  # list of test IDs that we want to generate test data
testIdList += range(1, 38)

myArgs = VXLIB_utils.getCmdLineArgs()


def gen_test_case(testCase):
    if testCase["testType"] == "STATIC":
        [minY, maxY] = gen_test_case_header_file(testCase)
        print(
            "Test case generation completed for test ID",
            testCase["ID"],
            "w/ min:",
            minY,
            "and max",
            maxY,
        )
    else:
        print(
            "Skipping test case generation for test ID",
            testCase["ID"],
            "as tesType is RANDOM",
        )


#############################################################################
# Open CSV file with test cases and generate header file with test data for #
# test cases of interest; based on testIdList                               #
#############################################################################

with open(testCasesCsvFile, encoding="utf-8-sig") as csv_file:
    testCaseReader = csv.DictReader(csv_file)
    testCases = list(testCaseReader)

    for testCase in testCases:
        testCase = process_test_case(testCase)

    for testCase in testCases:
        if myArgs.allCases == True:
            gen_test_case(testCase)
        elif int(testCase["ID"]) in testIdList:
            gen_test_case(testCase)

idatFileName = "../../VXLIB_and/VXLIB_and_idat.c"


##########################################################################
# Generate idat.cpp file by parsing all the test cases in the CSV file # #
##########################################################################


with open(idatFileName, "w") as idatFile:
    gen_idat_file(idatFile, testCases)


if platform == "linux" or platform == "linux2":
    call(["clang-format", "-style=file", "-i", idatFileName])
    call(["indent", "-nut", "-i3", "-c55", "-l200", idatFileName])
    call(["rm", idatFileName + "~"])  # remove backup file


print("Idat file generation completed")
