/********************************************************************
*
* COMPUTE_CLUSTER0_DRU INTERRUPT MAP. header file
*
* Copyright (C) 2015-2020 Texas Instruments Incorporated.
*  Redistribution and use in source and binary forms, with or without
*  modification, are permitted provided that the following conditions
*  are met:
*
*    Redistributions of source code must retain the above copyright
*    notice, this list of conditions and the following disclaimer.
*
*    Redistributions in binary form must reproduce the above copyright
*    notice, this list of conditions and the following disclaimer in the
*    documentation and/or other materials provided with the
*    distribution.
*
*    Neither the name of Texas Instruments Incorporated nor the names of
*    its contributors may be used to endorse or promote products derived
*    from this software without specific prior written permission.
*
*  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
*  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
*  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
*  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
*  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
*  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
*  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
*  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
*  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
*  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
*  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
*/
#ifndef SDLR_COMPUTE_CLUSTER0_DRU_INTERRUPT_MAP_H_
#define SDLR_COMPUTE_CLUSTER0_DRU_INTERRUPT_MAP_H_

#include <sdlr.h>
#include <tistdtypes.h>
#ifdef __cplusplus
extern "C"
{
#endif

/*
* List of intr sources for receiver: COMPUTE_CLUSTER0_DRU
*/

#define SDLR_COMPUTE_CLUSTER0_DRU_DRU_LOCAL_IN_EVENT_COMPUTE_CLUSTER0_CLEC_DRU_LOCALIN_EVENT_OUT_0 (0U)
#define SDLR_COMPUTE_CLUSTER0_DRU_DRU_LOCAL_IN_EVENT_COMPUTE_CLUSTER0_CLEC_DRU_LOCALIN_EVENT_OUT_1 (1U)
#define SDLR_COMPUTE_CLUSTER0_DRU_DRU_LOCAL_IN_EVENT_COMPUTE_CLUSTER0_CLEC_DRU_LOCALIN_EVENT_OUT_2 (2U)
#define SDLR_COMPUTE_CLUSTER0_DRU_DRU_LOCAL_IN_EVENT_COMPUTE_CLUSTER0_CLEC_DRU_LOCALIN_EVENT_OUT_3 (3U)
#define SDLR_COMPUTE_CLUSTER0_DRU_DRU_LOCAL_IN_EVENT_COMPUTE_CLUSTER0_CLEC_DRU_LOCALIN_EVENT_OUT_4 (4U)
#define SDLR_COMPUTE_CLUSTER0_DRU_DRU_LOCAL_IN_EVENT_COMPUTE_CLUSTER0_CLEC_DRU_LOCALIN_EVENT_OUT_5 (5U)
#define SDLR_COMPUTE_CLUSTER0_DRU_DRU_LOCAL_IN_EVENT_COMPUTE_CLUSTER0_CLEC_DRU_LOCALIN_EVENT_OUT_6 (6U)
#define SDLR_COMPUTE_CLUSTER0_DRU_DRU_LOCAL_IN_EVENT_COMPUTE_CLUSTER0_CLEC_DRU_LOCALIN_EVENT_OUT_7 (7U)
#define SDLR_COMPUTE_CLUSTER0_DRU_DRU_LOCAL_IN_EVENT_COMPUTE_CLUSTER0_CLEC_DRU_LOCALIN_EVENT_OUT_8 (8U)
#define SDLR_COMPUTE_CLUSTER0_DRU_DRU_LOCAL_IN_EVENT_COMPUTE_CLUSTER0_CLEC_DRU_LOCALIN_EVENT_OUT_9 (9U)
#define SDLR_COMPUTE_CLUSTER0_DRU_DRU_LOCAL_IN_EVENT_COMPUTE_CLUSTER0_CLEC_DRU_LOCALIN_EVENT_OUT_10 (10U)
#define SDLR_COMPUTE_CLUSTER0_DRU_DRU_LOCAL_IN_EVENT_COMPUTE_CLUSTER0_CLEC_DRU_LOCALIN_EVENT_OUT_11 (11U)
#define SDLR_COMPUTE_CLUSTER0_DRU_DRU_LOCAL_IN_EVENT_COMPUTE_CLUSTER0_CLEC_DRU_LOCALIN_EVENT_OUT_12 (12U)
#define SDLR_COMPUTE_CLUSTER0_DRU_DRU_LOCAL_IN_EVENT_COMPUTE_CLUSTER0_CLEC_DRU_LOCALIN_EVENT_OUT_13 (13U)
#define SDLR_COMPUTE_CLUSTER0_DRU_DRU_LOCAL_IN_EVENT_COMPUTE_CLUSTER0_CLEC_DRU_LOCALIN_EVENT_OUT_14 (14U)
#define SDLR_COMPUTE_CLUSTER0_DRU_DRU_LOCAL_IN_EVENT_COMPUTE_CLUSTER0_CLEC_DRU_LOCALIN_EVENT_OUT_15 (15U)
#define SDLR_COMPUTE_CLUSTER0_DRU_DRU_LOCAL_IN_EVENT_COMPUTE_CLUSTER0_CLEC_DRU_LOCALIN_EVENT_OUT_16 (16U)
#define SDLR_COMPUTE_CLUSTER0_DRU_DRU_LOCAL_IN_EVENT_COMPUTE_CLUSTER0_CLEC_DRU_LOCALIN_EVENT_OUT_17 (17U)
#define SDLR_COMPUTE_CLUSTER0_DRU_DRU_LOCAL_IN_EVENT_COMPUTE_CLUSTER0_CLEC_DRU_LOCALIN_EVENT_OUT_18 (18U)
#define SDLR_COMPUTE_CLUSTER0_DRU_DRU_LOCAL_IN_EVENT_COMPUTE_CLUSTER0_CLEC_DRU_LOCALIN_EVENT_OUT_19 (19U)
#define SDLR_COMPUTE_CLUSTER0_DRU_DRU_LOCAL_IN_EVENT_COMPUTE_CLUSTER0_CLEC_DRU_LOCALIN_EVENT_OUT_20 (20U)
#define SDLR_COMPUTE_CLUSTER0_DRU_DRU_LOCAL_IN_EVENT_COMPUTE_CLUSTER0_CLEC_DRU_LOCALIN_EVENT_OUT_21 (21U)
#define SDLR_COMPUTE_CLUSTER0_DRU_DRU_LOCAL_IN_EVENT_COMPUTE_CLUSTER0_CLEC_DRU_LOCALIN_EVENT_OUT_22 (22U)
#define SDLR_COMPUTE_CLUSTER0_DRU_DRU_LOCAL_IN_EVENT_COMPUTE_CLUSTER0_CLEC_DRU_LOCALIN_EVENT_OUT_23 (23U)
#define SDLR_COMPUTE_CLUSTER0_DRU_DRU_LOCAL_IN_EVENT_COMPUTE_CLUSTER0_CLEC_DRU_LOCALIN_EVENT_OUT_24 (24U)
#define SDLR_COMPUTE_CLUSTER0_DRU_DRU_LOCAL_IN_EVENT_COMPUTE_CLUSTER0_CLEC_DRU_LOCALIN_EVENT_OUT_25 (25U)
#define SDLR_COMPUTE_CLUSTER0_DRU_DRU_LOCAL_IN_EVENT_COMPUTE_CLUSTER0_CLEC_DRU_LOCALIN_EVENT_OUT_26 (26U)
#define SDLR_COMPUTE_CLUSTER0_DRU_DRU_LOCAL_IN_EVENT_COMPUTE_CLUSTER0_CLEC_DRU_LOCALIN_EVENT_OUT_27 (27U)
#define SDLR_COMPUTE_CLUSTER0_DRU_DRU_LOCAL_IN_EVENT_COMPUTE_CLUSTER0_CLEC_DRU_LOCALIN_EVENT_OUT_28 (28U)
#define SDLR_COMPUTE_CLUSTER0_DRU_DRU_LOCAL_IN_EVENT_COMPUTE_CLUSTER0_CLEC_DRU_LOCALIN_EVENT_OUT_29 (29U)
#define SDLR_COMPUTE_CLUSTER0_DRU_DRU_LOCAL_IN_EVENT_COMPUTE_CLUSTER0_CLEC_DRU_LOCALIN_EVENT_OUT_30 (30U)
#define SDLR_COMPUTE_CLUSTER0_DRU_DRU_LOCAL_IN_EVENT_COMPUTE_CLUSTER0_CLEC_DRU_LOCALIN_EVENT_OUT_31 (31U)

#ifdef __cplusplus
}
#endif
#endif /* SDLR_COMPUTE_CLUSTER0_DRU_INTERRUPT_MAP_H_ */

