/********************************************************************
*
* WKUP_ESM0 INTERRUPT MAP. header file
*
* Copyright (C) 2015-2020 Texas Instruments Incorporated.
*  Redistribution and use in source and binary forms, with or without
*  modification, are permitted provided that the following conditions
*  are met:
*
*    Redistributions of source code must retain the above copyright
*    notice, this list of conditions and the following disclaimer.
*
*    Redistributions in binary form must reproduce the above copyright
*    notice, this list of conditions and the following disclaimer in the
*    documentation and/or other materials provided with the
*    distribution.
*
*    Neither the name of Texas Instruments Incorporated nor the names of
*    its contributors may be used to endorse or promote products derived
*    from this software without specific prior written permission.
*
*  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
*  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
*  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
*  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
*  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
*  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
*  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
*  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
*  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
*  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
*  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
*/
#ifndef SDLR_WKUP_ESM0_INTERRUPT_MAP_H_
#define SDLR_WKUP_ESM0_INTERRUPT_MAP_H_

#include <sdlr.h>
#include <tistdtypes.h>
#ifdef __cplusplus
extern "C"
{
#endif

/*
* List of intr sources for receiver: WKUP_ESM0
*/

#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_WKUP_SMS0_DMTIMER_0_INTR_PEND_0                               (0U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_WKUP_SMS0_DMTIMER_1_INTR_PEND_0                               (1U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_WKUP_SMS0_DMTIMER_2_INTR_PEND_0                               (2U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_WKUP_SMS0_DMTIMER_3_INTR_PEND_0                               (3U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_WKUP_SMS0_RTI_0_WDG_INTR_4                                    (4U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_WKUP_SMS0_RAT_0_EXP_INTR_0                                    (5U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_WKUP_SMS0_ECC_AGGR_0_ECC_CORRECTED_LEVEL_0                    (6U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_WKUP_SMS0_ECC_AGGR_0_ECC_UNCORRECTED_LEVEL_0                  (7U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_WKUP_VTM0_THERM_LVL_GT_TH1_INTR_0                             (8U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_WKUP_VTM0_THERM_LVL_LT_TH0_INTR_0                             (9U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_WKUP_VTM0_THERM_LVL_GT_TH2_INTR_0                             (10U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_WKUP_VTM0_CORR_LEVEL_0                                        (11U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_WKUP_VTM0_UNCORR_LEVEL_0                                      (12U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_GLUELOGIC_HFOSC0_CLKLOSS_GLUE_REF_CLK_LOSS_DETECT_OUT_0       (13U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_WKUP_ECC_AGGR0_CORR_LEVEL_0                                   (14U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_WKUP_ECC_AGGR0_UNCORR_LEVEL_0                                 (15U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_WKUP_VDC_INFRA_VBUSP_32B_SRC_SAFEG0_INFRA_SAFEG_TRANS_ERR_LVL_0 (16U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_WKUP_PORZ_SYNC0_PORZ_TIMEOUT_0                                (17U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_MCU_SA3_SS0_DMSS_ECCAGGR_0_DMSS_ECC_SEC_PEND_0                (18U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_MCU_SA3_SS0_DMSS_ECCAGGR_0_DMSS_ECC_DED_PEND_0                (19U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_WKUPM_WAKEUP0_VDD_MCU_GLDTC_STAT_THRESH_LOW_FLAG_IPCFG_0      (20U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_WKUPM_WAKEUP0_VDD_MCU_GLDTC_STAT_THRESH_HI_FLAG_IPCFG_0       (21U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_WKUPM_WAKEUP0_VDDR_MCU_GLDTC_STAT_THRESH_LOW_FLAG_IPCFG_0     (22U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_WKUPM_WAKEUP0_VDDR_MCU_GLDTC_STAT_THRESH_HI_FLAG_IPCFG_0      (23U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_AM_MAIN0_VDD_CORE_GLDTC_STAT_THRESH_LOW_FLAG_IPCFG_0          (24U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_AM_MAIN0_VDD_CORE_GLDTC_STAT_THRESH_HI_FLAG_IPCFG_0           (25U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_AM_MAIN0_VDDR_CORE_GLDTC_STAT_THRESH_LOW_FLAG_IPCFG_0         (26U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_AM_MAIN0_VDDR_CORE_GLDTC_STAT_THRESH_HI_FLAG_IPCFG_0          (27U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_AM_BOLT_PGD0_VDD_CPU_GLDTC_STAT_THRESH_LOW_FLAG_IPCFG_0       (28U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_AM_BOLT_PGD0_VDD_CPU_GLDTC_STAT_THRESH_HI_FLAG_IPCFG_0        (29U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_AM_BOLT_PGD0_VDDR_CPU_GLDTC_STAT_THRESH_LOW_FLAG_IPCFG_0      (30U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_AM_BOLT_PGD0_VDDR_CPU_GLDTC_STAT_THRESH_HI_FLAG_IPCFG_0       (31U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_WKUP_PSC0_PSC_MOD_WKLP_WKUP_ALWAYSON_CS1_CLKSTOP_REQ_0        (32U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_WKUP_PSC0_PSC_MOD_WKLP_DMSC_CS1_CLKSTOP_REQ_0                 (33U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_WKUP_PSC0_PSC_MOD_WKLP_DEBUG2DMSC_CS1_CLKSTOP_REQ_0           (34U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_WKUP_PSC0_PSC_MOD_WKLP_WKUP_GPIO_CS1_CLKSTOP_REQ_0            (35U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_WKUP_PSC0_PSC_MOD_WKLP_WKUPMCU2MAIN_CS1_CLKSTOP_REQ_0         (36U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_WKUP_PSC0_PSC_MOD_WKLP_MAIN2WKUPMCU_CS1_CLKSTOP_REQ_0         (37U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_WKUP_PSC0_PSC_MOD_WKLP_MCU_TEST_CS1_CLKSTOP_REQ_0             (38U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_WKUP_PSC0_PSC_MOD_WKLP_MCU_DEBUG_CS1_CLKSTOP_REQ_0            (39U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_WKUP_PSC0_PSC_MOD_WKLP_MCU_MCAN_0_CS1_CLKSTOP_REQ_0           (40U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_WKUP_PSC0_PSC_MOD_WKLP_MCU_MCAN_1_CS1_CLKSTOP_REQ_0           (41U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_WKUP_PSC0_PSC_MOD_WKLP_MCU_OSPI_0_CS1_CLKSTOP_REQ_0           (42U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_WKUP_PSC0_PSC_MOD_WKLP_MCU_OSPI_1_CS1_CLKSTOP_REQ_0           (43U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_WKUP_PSC0_PSC_MOD_WKLP_MCU_HYPERBUS_CS1_CLKSTOP_REQ_0         (44U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_WKUP_PSC0_PSC_MOD_WKLP_MCU_I3C_0_CS1_CLKSTOP_REQ_0            (45U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_WKUP_PSC0_PSC_MOD_WKLP_MCU_I3C_1_CS1_CLKSTOP_REQ_0            (46U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_WKUP_PSC0_PSC_MOD_WKLP_MCU_ADC_0_CS1_CLKSTOP_REQ_0            (47U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_WKUP_PSC0_PSC_MOD_WKLP_MCU_ADC_1_CS1_CLKSTOP_REQ_0            (48U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_WKUP_PSC0_PSC_MOD_WKLP_WKUP_SPARE0_CS1_CLKSTOP_REQ_0          (49U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_WKUP_PSC0_PSC_MOD_WKLP_WKUP_SPARE1_CS1_CLKSTOP_REQ_0          (50U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_WKUP_PSC0_PSC_MOD_WKLP_MCU_R5_0_CS1_CLKSTOP_REQ_0             (51U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_WKUP_PSC0_PSC_MOD_WKLP_MCU_R5_1_CS1_CLKSTOP_REQ_0             (52U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_WKUP_PSC0_PSC_MOD_WKLP_MCU_PULSAR_PBIST_0_CS1_CLKSTOP_REQ_0   (53U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_WKUP_SMS0_RTI_1_WDG_INTR_4                                    (54U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_WKUP_SMS0_RAT_1_EXP_INTR_0                                    (55U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_WKUP_SMS0_ECC_AGGR_1_ECC_CORRECTED_LEVEL_0                    (56U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_WKUP_SMS0_ECC_AGGR_1_ECC_UNCORRECTED_LEVEL_0                  (57U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_MCU_SA3_SS0_SA_UL_0_SA_UL_ECC_CORR_LEVEL_0                    (58U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_MCU_SA3_SS0_SA_UL_0_SA_UL_ECC_UNCORR_LEVEL_0                  (59U)
#define SDLR_WKUP_ESM0_ESM_LVL_EVENT_GLUELOGIC_ESM_MCU_ERR_GLUE_ERROR_N_0                          (63U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT0_WKUP_PRG_MCU_3POKS0_POK_PGOOD_UV_OUT_N_TO_ESM_0              (64U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT1_WKUP_PRG_MCU_3POKS0_POK_PGOOD_UV_OUT_N_TO_ESM_0              (64U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT2_WKUP_PRG_MCU_3POKS0_POK_PGOOD_UV_OUT_N_TO_ESM_0              (64U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT0_WKUP_PRG_MCU_3POKS0_POK_PGOOD_OV_OUT_N_TO_ESM_0              (65U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT1_WKUP_PRG_MCU_3POKS0_POK_PGOOD_OV_OUT_N_TO_ESM_0              (65U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT2_WKUP_PRG_MCU_3POKS0_POK_PGOOD_OV_OUT_N_TO_ESM_0              (65U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT0_WKUP_PRG_MCU_3POKS0_POK_PGOOD_UV_OUT_N_TO_ESM_1              (66U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT1_WKUP_PRG_MCU_3POKS0_POK_PGOOD_UV_OUT_N_TO_ESM_1              (66U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT2_WKUP_PRG_MCU_3POKS0_POK_PGOOD_UV_OUT_N_TO_ESM_1              (66U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT0_WKUP_PRG_MCU_3POKS0_POK_PGOOD_OV_OUT_N_TO_ESM_1              (67U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT1_WKUP_PRG_MCU_3POKS0_POK_PGOOD_OV_OUT_N_TO_ESM_1              (67U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT2_WKUP_PRG_MCU_3POKS0_POK_PGOOD_OV_OUT_N_TO_ESM_1              (67U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT0_WKUP_PRG_MCU_3POKS0_POK_PGOOD_UV_OUT_N_TO_ESM_2              (68U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT1_WKUP_PRG_MCU_3POKS0_POK_PGOOD_UV_OUT_N_TO_ESM_2              (68U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT2_WKUP_PRG_MCU_3POKS0_POK_PGOOD_UV_OUT_N_TO_ESM_2              (68U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT0_WKUP_PRG_MCU_3POKS0_POK_PGOOD_OV_OUT_N_TO_ESM_2              (69U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT1_WKUP_PRG_MCU_3POKS0_POK_PGOOD_OV_OUT_N_TO_ESM_2              (69U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT2_WKUP_PRG_MCU_3POKS0_POK_PGOOD_OV_OUT_N_TO_ESM_2              (69U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT0_WKUP_PRG_MCU0_POK_PGOOD_UV_OUT_N_TO_ESM_0                    (72U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT1_WKUP_PRG_MCU0_POK_PGOOD_UV_OUT_N_TO_ESM_0                    (72U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT2_WKUP_PRG_MCU0_POK_PGOOD_UV_OUT_N_TO_ESM_0                    (72U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT0_WKUP_PRG_MCU0_POK_PGOOD_UV_OUT_N_TO_ESM_1                    (74U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT1_WKUP_PRG_MCU0_POK_PGOOD_UV_OUT_N_TO_ESM_1                    (74U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT2_WKUP_PRG_MCU0_POK_PGOOD_UV_OUT_N_TO_ESM_1                    (74U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT0_WKUP_PRG_MCU0_POK_PGOOD_UV_OUT_N_TO_ESM_2                    (76U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT1_WKUP_PRG_MCU0_POK_PGOOD_UV_OUT_N_TO_ESM_2                    (76U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT2_WKUP_PRG_MCU0_POK_PGOOD_UV_OUT_N_TO_ESM_2                    (76U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT0_WKUP_PRG_MCU0_POK_PGOOD_UV_OUT_N_TO_ESM_3                    (78U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT1_WKUP_PRG_MCU0_POK_PGOOD_UV_OUT_N_TO_ESM_3                    (78U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT2_WKUP_PRG_MCU0_POK_PGOOD_UV_OUT_N_TO_ESM_3                    (78U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT0_WKUP_PRG_MCU0_POK_PGOOD_UV_OUT_N_TO_ESM_4                    (80U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT1_WKUP_PRG_MCU0_POK_PGOOD_UV_OUT_N_TO_ESM_4                    (80U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT2_WKUP_PRG_MCU0_POK_PGOOD_UV_OUT_N_TO_ESM_4                    (80U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT0_WKUP_PRG0_POK_PGOOD_UV_OUT_N_TO_ESM_0                        (88U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT1_WKUP_PRG0_POK_PGOOD_UV_OUT_N_TO_ESM_0                        (88U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT2_WKUP_PRG0_POK_PGOOD_UV_OUT_N_TO_ESM_0                        (88U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT0_WKUP_PRG0_POK_PGOOD_OV_OUT_N_TO_ESM_0                        (89U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT1_WKUP_PRG0_POK_PGOOD_OV_OUT_N_TO_ESM_0                        (89U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT2_WKUP_PRG0_POK_PGOOD_OV_OUT_N_TO_ESM_0                        (89U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT0_WKUP_PRG0_POK_PGOOD_UV_OUT_N_TO_ESM_1                        (90U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT1_WKUP_PRG0_POK_PGOOD_UV_OUT_N_TO_ESM_1                        (90U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT2_WKUP_PRG0_POK_PGOOD_UV_OUT_N_TO_ESM_1                        (90U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT0_WKUP_PRG0_POK_PGOOD_OV_OUT_N_TO_ESM_1                        (91U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT1_WKUP_PRG0_POK_PGOOD_OV_OUT_N_TO_ESM_1                        (91U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT2_WKUP_PRG0_POK_PGOOD_OV_OUT_N_TO_ESM_1                        (91U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT0_WKUP_PRG0_POK_PGOOD_UV_OUT_N_TO_ESM_2                        (92U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT1_WKUP_PRG0_POK_PGOOD_UV_OUT_N_TO_ESM_2                        (92U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT2_WKUP_PRG0_POK_PGOOD_UV_OUT_N_TO_ESM_2                        (92U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT0_WKUP_PRG0_POK_PGOOD_OV_OUT_N_TO_ESM_2                        (93U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT1_WKUP_PRG0_POK_PGOOD_OV_OUT_N_TO_ESM_2                        (93U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT2_WKUP_PRG0_POK_PGOOD_OV_OUT_N_TO_ESM_2                        (93U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT0_WKUP_PRG0_POK_PGOOD_UV_OUT_N_TO_ESM_3                        (94U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT1_WKUP_PRG0_POK_PGOOD_UV_OUT_N_TO_ESM_3                        (94U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT2_WKUP_PRG0_POK_PGOOD_UV_OUT_N_TO_ESM_3                        (94U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT0_WKUP_PRG0_POK_PGOOD_OV_OUT_N_TO_ESM_3                        (95U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT1_WKUP_PRG0_POK_PGOOD_OV_OUT_N_TO_ESM_3                        (95U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT2_WKUP_PRG0_POK_PGOOD_OV_OUT_N_TO_ESM_3                        (95U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT0_WKUP_PRG0_POK_PGOOD_UV_OUT_N_TO_ESM_4                        (96U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT1_WKUP_PRG0_POK_PGOOD_UV_OUT_N_TO_ESM_4                        (96U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT2_WKUP_PRG0_POK_PGOOD_UV_OUT_N_TO_ESM_4                        (96U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT0_WKUP_PRG0_POK_PGOOD_OV_OUT_N_TO_ESM_4                        (97U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT1_WKUP_PRG0_POK_PGOOD_OV_OUT_N_TO_ESM_4                        (97U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT2_WKUP_PRG0_POK_PGOOD_OV_OUT_N_TO_ESM_4                        (97U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT0_WKUP_PRG0_POK_PGOOD_UV_OUT_N_TO_ESM_5                        (98U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT1_WKUP_PRG0_POK_PGOOD_UV_OUT_N_TO_ESM_5                        (98U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT2_WKUP_PRG0_POK_PGOOD_UV_OUT_N_TO_ESM_5                        (98U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT0_WKUP_PRG0_POK_PGOOD_OV_OUT_N_TO_ESM_5                        (99U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT1_WKUP_PRG0_POK_PGOOD_OV_OUT_N_TO_ESM_5                        (99U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT2_WKUP_PRG0_POK_PGOOD_OV_OUT_N_TO_ESM_5                        (99U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT0_WKUP_PRG0_POK_PGOOD_UV_OUT_N_TO_ESM_6                        (100U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT1_WKUP_PRG0_POK_PGOOD_UV_OUT_N_TO_ESM_6                        (100U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT2_WKUP_PRG0_POK_PGOOD_UV_OUT_N_TO_ESM_6                        (100U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT0_WKUP_PRG0_POK_PGOOD_OV_OUT_N_TO_ESM_6                        (101U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT1_WKUP_PRG0_POK_PGOOD_OV_OUT_N_TO_ESM_6                        (101U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT2_WKUP_PRG0_POK_PGOOD_OV_OUT_N_TO_ESM_6                        (101U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT0_WKUP_GPIOMUX_INTRTR0_OUTP_8                                  (120U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT1_WKUP_GPIOMUX_INTRTR0_OUTP_8                                  (120U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT2_WKUP_GPIOMUX_INTRTR0_OUTP_8                                  (120U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT0_WKUP_GPIOMUX_INTRTR0_OUTP_9                                  (121U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT1_WKUP_GPIOMUX_INTRTR0_OUTP_9                                  (121U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT2_WKUP_GPIOMUX_INTRTR0_OUTP_9                                  (121U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT0_WKUP_GPIOMUX_INTRTR0_OUTP_10                                 (122U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT1_WKUP_GPIOMUX_INTRTR0_OUTP_10                                 (122U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT2_WKUP_GPIOMUX_INTRTR0_OUTP_10                                 (122U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT0_WKUP_GPIOMUX_INTRTR0_OUTP_11                                 (123U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT1_WKUP_GPIOMUX_INTRTR0_OUTP_11                                 (123U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT2_WKUP_GPIOMUX_INTRTR0_OUTP_11                                 (123U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT0_WKUP_GPIOMUX_INTRTR0_OUTP_12                                 (124U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT1_WKUP_GPIOMUX_INTRTR0_OUTP_12                                 (124U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT2_WKUP_GPIOMUX_INTRTR0_OUTP_12                                 (124U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT0_WKUP_GPIOMUX_INTRTR0_OUTP_13                                 (125U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT1_WKUP_GPIOMUX_INTRTR0_OUTP_13                                 (125U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT2_WKUP_GPIOMUX_INTRTR0_OUTP_13                                 (125U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT0_WKUP_GPIOMUX_INTRTR0_OUTP_14                                 (126U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT1_WKUP_GPIOMUX_INTRTR0_OUTP_14                                 (126U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT2_WKUP_GPIOMUX_INTRTR0_OUTP_14                                 (126U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT0_WKUP_GPIOMUX_INTRTR0_OUTP_15                                 (127U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT1_WKUP_GPIOMUX_INTRTR0_OUTP_15                                 (127U)
#define SDLR_WKUP_ESM0_ESM_PLS_EVENT2_WKUP_GPIOMUX_INTRTR0_OUTP_15                                 (127U)

#ifdef __cplusplus
}
#endif
#endif /* SDLR_WKUP_ESM0_INTERRUPT_MAP_H_ */

