/********************************************************************
*
* R5FSS1_CORE1 INTERRUPT MAP. header file
*
* Copyright (C) 2015-2020 Texas Instruments Incorporated.
*  Redistribution and use in source and binary forms, with or without
*  modification, are permitted provided that the following conditions
*  are met:
*
*    Redistributions of source code must retain the above copyright
*    notice, this list of conditions and the following disclaimer.
*
*    Redistributions in binary form must reproduce the above copyright
*    notice, this list of conditions and the following disclaimer in the
*    documentation and/or other materials provided with the
*    distribution.
*
*    Neither the name of Texas Instruments Incorporated nor the names of
*    its contributors may be used to endorse or promote products derived
*    from this software without specific prior written permission.
*
*  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
*  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
*  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
*  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
*  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
*  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
*  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
*  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
*  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
*  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
*  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
*/
#ifndef SDLR_R5FSS1_CORE1_INTERRUPT_MAP_H_
#define SDLR_R5FSS1_CORE1_INTERRUPT_MAP_H_

#include <sdlr.h>
#include <tistdtypes.h>
#ifdef __cplusplus
extern "C"
{
#endif

/*
* List of intr sources for receiver: R5FSS1_CORE1
*/

#define SDLR_R5FSS1_CORE1_INTR_CTRL_MMR0_IPC_SET18_IPC_SET_IPCFG_0                                 (0U)
#define SDLR_R5FSS1_CORE1_INTR_CTRL_MMR0_IPC_SET19_IPC_SET_IPCFG_0                                 (1U)
#define SDLR_R5FSS1_CORE1_INTR_RTI30_INTR_WWD_0                                                    (2U)
#define SDLR_R5FSS1_CORE1_INTR_RTI31_INTR_WWD_0                                                    (3U)
#define SDLR_R5FSS1_CORE1_INTR_R5FSS1_COMMON0_COMMRX_LEVEL_1_0                                     (4U)
#define SDLR_R5FSS1_CORE1_INTR_R5FSS1_COMMON0_COMMTX_LEVEL_1_0                                     (5U)
#define SDLR_R5FSS1_CORE1_INTR_R5FSS1_CORE1_VALFIQ_0                                               (6U)
#define SDLR_R5FSS1_CORE1_INTR_R5FSS1_CORE1_VALIRQ_0                                               (7U)
#define SDLR_R5FSS1_CORE1_INTR_R5FSS1_CORE0_CTI_0                                                  (8U)
#define SDLR_R5FSS1_CORE1_INTR_R5FSS1_CORE1_CTI_0                                                  (9U)
#define SDLR_R5FSS1_CORE1_INTR_ESM0_ESM_INT_LOW_LVL_0                                              (10U)
#define SDLR_R5FSS1_CORE1_INTR_ESM0_ESM_INT_HI_LVL_0                                               (11U)
#define SDLR_R5FSS1_CORE1_INTR_ESM0_ESM_INT_CFG_LVL_0                                              (12U)
#define SDLR_R5FSS1_CORE1_INTR_GLUELOGIC_EXT_INTN_GLUE_EXT_INT_LVL_0                               (13U)
#define SDLR_R5FSS1_CORE1_INTR_PSC0_PSC_ALLINT_0                                                   (15U)
#define SDLR_R5FSS1_CORE1_INTR_R5FSS1_CORE0_EXP_INTR_0                                             (16U)
#define SDLR_R5FSS1_CORE1_INTR_R5FSS1_CORE1_EXP_INTR_0                                             (17U)
#define SDLR_R5FSS1_CORE1_INTR_R5FSS1_CORE0_PMU_0                                                  (18U)
#define SDLR_R5FSS1_CORE1_INTR_R5FSS1_CORE1_PMU_0                                                  (19U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN14_MCANSS_MCAN_LVL_INT_0                                        (20U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN14_MCANSS_MCAN_LVL_INT_1                                        (21U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN14_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                             (22U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN15_MCANSS_MCAN_LVL_INT_0                                        (23U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN15_MCANSS_MCAN_LVL_INT_1                                        (24U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN15_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                             (25U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN16_MCANSS_MCAN_LVL_INT_0                                        (26U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN16_MCANSS_MCAN_LVL_INT_1                                        (27U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN16_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                             (28U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN17_MCANSS_MCAN_LVL_INT_0                                        (29U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN17_MCANSS_MCAN_LVL_INT_1                                        (30U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN17_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                             (31U)
#define SDLR_R5FSS1_CORE1_INTR_DMPAC0_INTD_0_SYSTEM_INTR_LEVEL_0                                   (32U)
#define SDLR_R5FSS1_CORE1_INTR_DMPAC0_INTD_0_SYSTEM_INTR_LEVEL_1                                   (33U)
#define SDLR_R5FSS1_CORE1_INTR_VPAC0_VPAC_LEVEL_0                                                  (34U)
#define SDLR_R5FSS1_CORE1_INTR_VPAC0_VPAC_LEVEL_1                                                  (35U)
#define SDLR_R5FSS1_CORE1_INTR_VPAC0_VPAC_LEVEL_2                                                  (36U)
#define SDLR_R5FSS1_CORE1_INTR_VPAC0_VPAC_LEVEL_3                                                  (37U)
#define SDLR_R5FSS1_CORE1_INTR_VPAC0_VPAC_LEVEL_4                                                  (38U)
#define SDLR_R5FSS1_CORE1_INTR_VPAC0_VPAC_LEVEL_5                                                  (39U)
#define SDLR_R5FSS1_CORE1_INTR_AEP_GPU_BXS464_WRAP0_COMMON_0_OS_IRQ_0                              (40U)
#define SDLR_R5FSS1_CORE1_INTR_AEP_GPU_BXS464_WRAP0_COMMON_0_OS_IRQ_1                              (41U)
#define SDLR_R5FSS1_CORE1_INTR_AEP_GPU_BXS464_WRAP0_COMMON_0_OS_IRQ_2                              (42U)
#define SDLR_R5FSS1_CORE1_INTR_AEP_GPU_BXS464_WRAP0_COMMON_0_OS_IRQ_3                              (43U)
#define SDLR_R5FSS1_CORE1_INTR_AEP_GPU_BXS464_WRAP0_GPU_PWRCTRL_REQ_0                              (44U)
#define SDLR_R5FSS1_CORE1_INTR_GLUELOGIC_GPU_GPIO_INT_GLUE_GPU_GPIO_REQINTOR_LVL_0                 (48U)
#define SDLR_R5FSS1_CORE1_INTR_GLUELOGIC_GPU_GPIO_INT_GLUE_GPU_GPIO_ACKINTOR_LVL_0                 (49U)
#define SDLR_R5FSS1_CORE1_INTR_SA2_UL0_SA_UL_PKA_0                                                 (50U)
#define SDLR_R5FSS1_CORE1_INTR_SA2_UL0_SA_UL_TRNG_0                                                (51U)
#define SDLR_R5FSS1_CORE1_INTR_DSS0_DSS_INST0_DISPC_FUNC_IRQ_PROC0_0                               (52U)
#define SDLR_R5FSS1_CORE1_INTR_DSS0_DSS_INST0_DISPC_FUNC_IRQ_PROC1_0                               (53U)
#define SDLR_R5FSS1_CORE1_INTR_DSS0_DSS_INST0_DISPC_SAFETY_ERROR_IRQ_PROC0_0                       (54U)
#define SDLR_R5FSS1_CORE1_INTR_DSS0_DSS_INST0_DISPC_SAFETY_ERROR_IRQ_PROC1_0                       (55U)
#define SDLR_R5FSS1_CORE1_INTR_DSS0_DSS_INST0_DISPC_SECURE_IRQ_PROC0_0                             (56U)
#define SDLR_R5FSS1_CORE1_INTR_DSS0_DSS_INST0_DISPC_SECURE_IRQ_PROC1_0                             (57U)
#define SDLR_R5FSS1_CORE1_INTR_DSS_EDP0_INTR_0                                                     (64U)
#define SDLR_R5FSS1_CORE1_INTR_DSS_EDP0_INTR_1                                                     (65U)
#define SDLR_R5FSS1_CORE1_INTR_DSS_EDP0_INTR_2                                                     (66U)
#define SDLR_R5FSS1_CORE1_INTR_DSS_EDP0_INTR_3                                                     (67U)
#define SDLR_R5FSS1_CORE1_INTR_CSI_TX_IF_V2_0_CSI_INTERRUPT_0                                      (72U)
#define SDLR_R5FSS1_CORE1_INTR_CSI_TX_IF_V2_0_CSI_LEVEL_0                                          (73U)
#define SDLR_R5FSS1_CORE1_INTR_CSI_TX_IF_V2_1_CSI_INTERRUPT_0                                      (74U)
#define SDLR_R5FSS1_CORE1_INTR_CSI_TX_IF_V2_1_CSI_LEVEL_0                                          (75U)
#define SDLR_R5FSS1_CORE1_INTR_DSS_DSI0_DSI_0_FUNC_INTR_0                                          (76U)
#define SDLR_R5FSS1_CORE1_INTR_DSS_DSI1_DSI_0_FUNC_INTR_0                                          (77U)
#define SDLR_R5FSS1_CORE1_INTR_CSI_RX_IF0_CSI_ERR_IRQ_0                                            (78U)
#define SDLR_R5FSS1_CORE1_INTR_CSI_RX_IF0_CSI_IRQ_0                                                (79U)
#define SDLR_R5FSS1_CORE1_INTR_CSI_RX_IF0_CSI_LEVEL_0                                              (80U)
#define SDLR_R5FSS1_CORE1_INTR_CSI_RX_IF1_CSI_ERR_IRQ_0                                            (81U)
#define SDLR_R5FSS1_CORE1_INTR_CSI_RX_IF1_CSI_IRQ_0                                                (82U)
#define SDLR_R5FSS1_CORE1_INTR_CSI_RX_IF1_CSI_LEVEL_0                                              (83U)
#define SDLR_R5FSS1_CORE1_INTR_K3_VPU_WAVE521CL0_VPU_WAVE521CL_INTR_0                              (89U)
#define SDLR_R5FSS1_CORE1_INTR_MMCSD0_EMMCSS_INTR_0                                                (99U)
#define SDLR_R5FSS1_CORE1_INTR_CPSW1_STAT_PEND_0                                                   (100U)
#define SDLR_R5FSS1_CORE1_INTR_CPSW1_MDIO_PEND_0                                                   (101U)
#define SDLR_R5FSS1_CORE1_INTR_CPSW1_EVNT_PEND_0                                                   (102U)
#define SDLR_R5FSS1_CORE1_INTR_EPWM0_EPWM_ETINT_0                                                  (104U)
#define SDLR_R5FSS1_CORE1_INTR_EPWM1_EPWM_ETINT_0                                                  (105U)
#define SDLR_R5FSS1_CORE1_INTR_EPWM2_EPWM_ETINT_0                                                  (106U)
#define SDLR_R5FSS1_CORE1_INTR_EPWM3_EPWM_ETINT_0                                                  (107U)
#define SDLR_R5FSS1_CORE1_INTR_EPWM4_EPWM_ETINT_0                                                  (108U)
#define SDLR_R5FSS1_CORE1_INTR_EPWM5_EPWM_ETINT_0                                                  (109U)
#define SDLR_R5FSS1_CORE1_INTR_EPWM0_EPWM_TRIPZINT_0                                               (110U)
#define SDLR_R5FSS1_CORE1_INTR_EPWM1_EPWM_TRIPZINT_0                                               (111U)
#define SDLR_R5FSS1_CORE1_INTR_EPWM2_EPWM_TRIPZINT_0                                               (112U)
#define SDLR_R5FSS1_CORE1_INTR_EPWM3_EPWM_TRIPZINT_0                                               (113U)
#define SDLR_R5FSS1_CORE1_INTR_EPWM4_EPWM_TRIPZINT_0                                               (114U)
#define SDLR_R5FSS1_CORE1_INTR_EPWM5_EPWM_TRIPZINT_0                                               (115U)
#define SDLR_R5FSS1_CORE1_INTR_EQEP0_EQEP_INT_0                                                    (116U)
#define SDLR_R5FSS1_CORE1_INTR_EQEP1_EQEP_INT_0                                                    (117U)
#define SDLR_R5FSS1_CORE1_INTR_EQEP2_EQEP_INT_0                                                    (118U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN0_MCANSS_MCAN_LVL_INT_0                                         (120U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN0_MCANSS_MCAN_LVL_INT_1                                         (121U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN0_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                              (122U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN1_MCANSS_MCAN_LVL_INT_0                                         (123U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN1_MCANSS_MCAN_LVL_INT_1                                         (124U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN1_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                              (125U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN2_MCANSS_MCAN_LVL_INT_0                                         (126U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN2_MCANSS_MCAN_LVL_INT_1                                         (127U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN2_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                              (128U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN3_MCANSS_MCAN_LVL_INT_0                                         (129U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN3_MCANSS_MCAN_LVL_INT_1                                         (130U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN3_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                              (131U)
#define SDLR_R5FSS1_CORE1_INTR_MCASP0_XMIT_INTR_PEND_0                                             (132U)
#define SDLR_R5FSS1_CORE1_INTR_MCASP0_REC_INTR_PEND_0                                              (133U)
#define SDLR_R5FSS1_CORE1_INTR_MCASP1_XMIT_INTR_PEND_0                                             (134U)
#define SDLR_R5FSS1_CORE1_INTR_MCASP1_REC_INTR_PEND_0                                              (135U)
#define SDLR_R5FSS1_CORE1_INTR_MCU_SA3_SS0_INTAGGR_0_INTAGGR_VINTR_4                               (148U)
#define SDLR_R5FSS1_CORE1_INTR_MCU_SA3_SS0_INTAGGR_0_INTAGGR_VINTR_5                               (149U)
#define SDLR_R5FSS1_CORE1_INTR_I2C0_POINTRPEND_0                                                   (150U)
#define SDLR_R5FSS1_CORE1_INTR_I2C1_POINTRPEND_0                                                   (151U)
#define SDLR_R5FSS1_CORE1_INTR_MCSPI0_INTR_SPI_0                                                   (152U)
#define SDLR_R5FSS1_CORE1_INTR_MCSPI1_INTR_SPI_0                                                   (153U)
#define SDLR_R5FSS1_CORE1_INTR_MCASP3_XMIT_INTR_PEND_0                                             (154U)
#define SDLR_R5FSS1_CORE1_INTR_MCASP3_REC_INTR_PEND_0                                              (155U)
#define SDLR_R5FSS1_CORE1_INTR_MCASP4_XMIT_INTR_PEND_0                                             (156U)
#define SDLR_R5FSS1_CORE1_INTR_MCASP4_REC_INTR_PEND_0                                              (157U)
#define SDLR_R5FSS1_CORE1_INTR_UART0_USART_IRQ_0                                                   (158U)
#define SDLR_R5FSS1_CORE1_INTR_UART1_USART_IRQ_0                                                   (159U)
#define SDLR_R5FSS1_CORE1_INTR_UART2_USART_IRQ_0                                                   (160U)
#define SDLR_R5FSS1_CORE1_INTR_VUSR_DUAL0_V0_VUSR_INTLVL_0                                         (162U)
#define SDLR_R5FSS1_CORE1_INTR_VUSR_DUAL0_V0_MCP_LO_INTLVL_0                                       (163U)
#define SDLR_R5FSS1_CORE1_INTR_VUSR_DUAL0_V0_MCP_HI_INTLVL_0                                       (164U)
#define SDLR_R5FSS1_CORE1_INTR_VUSR_DUAL0_V1_VUSR_INTLVL_0                                         (165U)
#define SDLR_R5FSS1_CORE1_INTR_VUSR_DUAL0_V1_MCP_LO_INTLVL_0                                       (166U)
#define SDLR_R5FSS1_CORE1_INTR_VUSR_DUAL0_V1_MCP_HI_INTLVL_0                                       (167U)
#define SDLR_R5FSS1_CORE1_INTR_TIMER12_INTR_PEND_0                                                 (168U)
#define SDLR_R5FSS1_CORE1_INTR_TIMER13_INTR_PEND_0                                                 (169U)
#define SDLR_R5FSS1_CORE1_INTR_TIMER14_INTR_PEND_0                                                 (170U)
#define SDLR_R5FSS1_CORE1_INTR_TIMER15_INTR_PEND_0                                                 (171U)
#define SDLR_R5FSS1_CORE1_INTR_TIMER16_INTR_PEND_0                                                 (172U)
#define SDLR_R5FSS1_CORE1_INTR_TIMER17_INTR_PEND_0                                                 (173U)
#define SDLR_R5FSS1_CORE1_INTR_TIMER18_INTR_PEND_0                                                 (174U)
#define SDLR_R5FSS1_CORE1_INTR_TIMER19_INTR_PEND_0                                                 (175U)
#define SDLR_R5FSS1_CORE1_INTR_GPIOMUX_INTRTR0_OUTP_16                                             (176U)
#define SDLR_R5FSS1_CORE1_INTR_GPIOMUX_INTRTR0_OUTP_17                                             (177U)
#define SDLR_R5FSS1_CORE1_INTR_GPIOMUX_INTRTR0_OUTP_18                                             (178U)
#define SDLR_R5FSS1_CORE1_INTR_GPIOMUX_INTRTR0_OUTP_19                                             (179U)
#define SDLR_R5FSS1_CORE1_INTR_GPIOMUX_INTRTR0_OUTP_20                                             (180U)
#define SDLR_R5FSS1_CORE1_INTR_GPIOMUX_INTRTR0_OUTP_21                                             (181U)
#define SDLR_R5FSS1_CORE1_INTR_GPIOMUX_INTRTR0_OUTP_22                                             (182U)
#define SDLR_R5FSS1_CORE1_INTR_GPIOMUX_INTRTR0_OUTP_23                                             (183U)
#define SDLR_R5FSS1_CORE1_INTR_GPIOMUX_INTRTR0_OUTP_24                                             (184U)
#define SDLR_R5FSS1_CORE1_INTR_GPIOMUX_INTRTR0_OUTP_25                                             (185U)
#define SDLR_R5FSS1_CORE1_INTR_GPIOMUX_INTRTR0_OUTP_26                                             (186U)
#define SDLR_R5FSS1_CORE1_INTR_GPIOMUX_INTRTR0_OUTP_27                                             (187U)
#define SDLR_R5FSS1_CORE1_INTR_GPIOMUX_INTRTR0_OUTP_28                                             (188U)
#define SDLR_R5FSS1_CORE1_INTR_GPIOMUX_INTRTR0_OUTP_29                                             (189U)
#define SDLR_R5FSS1_CORE1_INTR_GPIOMUX_INTRTR0_OUTP_30                                             (190U)
#define SDLR_R5FSS1_CORE1_INTR_GPIOMUX_INTRTR0_OUTP_31                                             (191U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN4_MCANSS_MCAN_LVL_INT_0                                         (192U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN4_MCANSS_MCAN_LVL_INT_1                                         (193U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN4_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                              (194U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN5_MCANSS_MCAN_LVL_INT_0                                         (195U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN5_MCANSS_MCAN_LVL_INT_1                                         (196U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN5_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                              (197U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN6_MCANSS_MCAN_LVL_INT_0                                         (198U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN6_MCANSS_MCAN_LVL_INT_1                                         (199U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN6_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                              (200U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN7_MCANSS_MCAN_LVL_INT_0                                         (201U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN7_MCANSS_MCAN_LVL_INT_1                                         (202U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN7_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                              (203U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN8_MCANSS_MCAN_LVL_INT_0                                         (204U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN8_MCANSS_MCAN_LVL_INT_1                                         (205U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN8_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                              (206U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN9_MCANSS_MCAN_LVL_INT_0                                         (207U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN9_MCANSS_MCAN_LVL_INT_1                                         (208U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN9_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                              (209U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN10_MCANSS_MCAN_LVL_INT_0                                        (210U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN10_MCANSS_MCAN_LVL_INT_1                                        (211U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN10_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                             (212U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN11_MCANSS_MCAN_LVL_INT_0                                        (213U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN11_MCANSS_MCAN_LVL_INT_1                                        (214U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN11_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                             (215U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN12_MCANSS_MCAN_LVL_INT_0                                        (216U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN12_MCANSS_MCAN_LVL_INT_1                                        (217U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN12_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                             (218U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN13_MCANSS_MCAN_LVL_INT_0                                        (219U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN13_MCANSS_MCAN_LVL_INT_1                                        (220U)
#define SDLR_R5FSS1_CORE1_INTR_MCAN13_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                             (221U)
#define SDLR_R5FSS1_CORE1_INTR_NAVSS0_INTR_0_OUTL_INTR_288                                         (224U)
#define SDLR_R5FSS1_CORE1_INTR_NAVSS0_INTR_0_OUTL_INTR_289                                         (225U)
#define SDLR_R5FSS1_CORE1_INTR_NAVSS0_INTR_0_OUTL_INTR_290                                         (226U)
#define SDLR_R5FSS1_CORE1_INTR_NAVSS0_INTR_0_OUTL_INTR_291                                         (227U)
#define SDLR_R5FSS1_CORE1_INTR_NAVSS0_INTR_0_OUTL_INTR_292                                         (228U)
#define SDLR_R5FSS1_CORE1_INTR_NAVSS0_INTR_0_OUTL_INTR_293                                         (229U)
#define SDLR_R5FSS1_CORE1_INTR_NAVSS0_INTR_0_OUTL_INTR_294                                         (230U)
#define SDLR_R5FSS1_CORE1_INTR_NAVSS0_INTR_0_OUTL_INTR_295                                         (231U)
#define SDLR_R5FSS1_CORE1_INTR_NAVSS0_INTR_0_OUTL_INTR_296                                         (232U)
#define SDLR_R5FSS1_CORE1_INTR_NAVSS0_INTR_0_OUTL_INTR_297                                         (233U)
#define SDLR_R5FSS1_CORE1_INTR_NAVSS0_INTR_0_OUTL_INTR_298                                         (234U)
#define SDLR_R5FSS1_CORE1_INTR_NAVSS0_INTR_0_OUTL_INTR_299                                         (235U)
#define SDLR_R5FSS1_CORE1_INTR_NAVSS0_INTR_0_OUTL_INTR_300                                         (236U)
#define SDLR_R5FSS1_CORE1_INTR_NAVSS0_INTR_0_OUTL_INTR_301                                         (237U)
#define SDLR_R5FSS1_CORE1_INTR_NAVSS0_INTR_0_OUTL_INTR_302                                         (238U)
#define SDLR_R5FSS1_CORE1_INTR_NAVSS0_INTR_0_OUTL_INTR_303                                         (239U)
#define SDLR_R5FSS1_CORE1_INTR_NAVSS0_INTR_0_OUTL_INTR_304                                         (240U)
#define SDLR_R5FSS1_CORE1_INTR_NAVSS0_INTR_0_OUTL_INTR_305                                         (241U)
#define SDLR_R5FSS1_CORE1_INTR_NAVSS0_INTR_0_OUTL_INTR_306                                         (242U)
#define SDLR_R5FSS1_CORE1_INTR_NAVSS0_INTR_0_OUTL_INTR_307                                         (243U)
#define SDLR_R5FSS1_CORE1_INTR_NAVSS0_INTR_0_OUTL_INTR_308                                         (244U)
#define SDLR_R5FSS1_CORE1_INTR_NAVSS0_INTR_0_OUTL_INTR_309                                         (245U)
#define SDLR_R5FSS1_CORE1_INTR_NAVSS0_INTR_0_OUTL_INTR_310                                         (246U)
#define SDLR_R5FSS1_CORE1_INTR_NAVSS0_INTR_0_OUTL_INTR_311                                         (247U)
#define SDLR_R5FSS1_CORE1_INTR_NAVSS0_INTR_0_OUTL_INTR_312                                         (248U)
#define SDLR_R5FSS1_CORE1_INTR_NAVSS0_INTR_0_OUTL_INTR_313                                         (249U)
#define SDLR_R5FSS1_CORE1_INTR_NAVSS0_INTR_0_OUTL_INTR_314                                         (250U)
#define SDLR_R5FSS1_CORE1_INTR_NAVSS0_INTR_0_OUTL_INTR_315                                         (251U)
#define SDLR_R5FSS1_CORE1_INTR_NAVSS0_INTR_0_OUTL_INTR_316                                         (252U)
#define SDLR_R5FSS1_CORE1_INTR_NAVSS0_INTR_0_OUTL_INTR_317                                         (253U)
#define SDLR_R5FSS1_CORE1_INTR_NAVSS0_INTR_0_OUTL_INTR_318                                         (254U)
#define SDLR_R5FSS1_CORE1_INTR_NAVSS0_INTR_0_OUTL_INTR_319                                         (255U)
#define SDLR_R5FSS1_CORE1_INTR_I2C2_POINTRPEND_0                                                   (256U)
#define SDLR_R5FSS1_CORE1_INTR_I2C3_POINTRPEND_0                                                   (257U)
#define SDLR_R5FSS1_CORE1_INTR_I2C4_POINTRPEND_0                                                   (258U)
#define SDLR_R5FSS1_CORE1_INTR_I2C5_POINTRPEND_0                                                   (259U)
#define SDLR_R5FSS1_CORE1_INTR_I2C6_POINTRPEND_0                                                   (260U)
#define SDLR_R5FSS1_CORE1_INTR_UART3_USART_IRQ_0                                                   (261U)
#define SDLR_R5FSS1_CORE1_INTR_UART4_USART_IRQ_0                                                   (262U)
#define SDLR_R5FSS1_CORE1_INTR_UART5_USART_IRQ_0                                                   (263U)
#define SDLR_R5FSS1_CORE1_INTR_UART6_USART_IRQ_0                                                   (264U)
#define SDLR_R5FSS1_CORE1_INTR_UART7_USART_IRQ_0                                                   (265U)
#define SDLR_R5FSS1_CORE1_INTR_UART8_USART_IRQ_0                                                   (266U)
#define SDLR_R5FSS1_CORE1_INTR_UART9_USART_IRQ_0                                                   (267U)
#define SDLR_R5FSS1_CORE1_INTR_MCSPI2_INTR_SPI_0                                                   (268U)
#define SDLR_R5FSS1_CORE1_INTR_MCSPI3_INTR_SPI_0                                                   (269U)
#define SDLR_R5FSS1_CORE1_INTR_MCSPI4_INTR_SPI_0                                                   (270U)
#define SDLR_R5FSS1_CORE1_INTR_MCSPI5_INTR_SPI_0                                                   (271U)
#define SDLR_R5FSS1_CORE1_INTR_MCSPI6_INTR_SPI_0                                                   (272U)
#define SDLR_R5FSS1_CORE1_INTR_MCSPI7_INTR_SPI_0                                                   (273U)
#define SDLR_R5FSS1_CORE1_INTR_MCASP2_XMIT_INTR_PEND_0                                             (276U)
#define SDLR_R5FSS1_CORE1_INTR_MCASP2_REC_INTR_PEND_0                                              (277U)
#define SDLR_R5FSS1_CORE1_INTR_GPMC0_GPMC_SINTERRUPT_0                                             (278U)
#define SDLR_R5FSS1_CORE1_INTR_ELM0_ELM_POROCPSINTERRUPT_LVL_0                                     (279U)
#define SDLR_R5FSS1_CORE1_INTR_USB0_OTGIRQ_0                                                       (280U)
#define SDLR_R5FSS1_CORE1_INTR_USB0_IRQ_0                                                          (281U)
#define SDLR_R5FSS1_CORE1_INTR_USB0_IRQ_1                                                          (282U)
#define SDLR_R5FSS1_CORE1_INTR_USB0_IRQ_2                                                          (283U)
#define SDLR_R5FSS1_CORE1_INTR_USB0_IRQ_3                                                          (284U)
#define SDLR_R5FSS1_CORE1_INTR_USB0_IRQ_4                                                          (285U)
#define SDLR_R5FSS1_CORE1_INTR_USB0_IRQ_5                                                          (286U)
#define SDLR_R5FSS1_CORE1_INTR_USB0_IRQ_6                                                          (287U)
#define SDLR_R5FSS1_CORE1_INTR_USB0_IRQ_7                                                          (288U)
#define SDLR_R5FSS1_CORE1_INTR_TIMER0_INTR_PEND_0                                                  (289U)
#define SDLR_R5FSS1_CORE1_INTR_TIMER1_INTR_PEND_0                                                  (290U)
#define SDLR_R5FSS1_CORE1_INTR_TIMER2_INTR_PEND_0                                                  (291U)
#define SDLR_R5FSS1_CORE1_INTR_TIMER3_INTR_PEND_0                                                  (292U)
#define SDLR_R5FSS1_CORE1_INTR_TIMER4_INTR_PEND_0                                                  (293U)
#define SDLR_R5FSS1_CORE1_INTR_TIMER5_INTR_PEND_0                                                  (294U)
#define SDLR_R5FSS1_CORE1_INTR_TIMER6_INTR_PEND_0                                                  (295U)
#define SDLR_R5FSS1_CORE1_INTR_TIMER7_INTR_PEND_0                                                  (296U)
#define SDLR_R5FSS1_CORE1_INTR_TIMER8_INTR_PEND_0                                                  (297U)
#define SDLR_R5FSS1_CORE1_INTR_TIMER9_INTR_PEND_0                                                  (298U)
#define SDLR_R5FSS1_CORE1_INTR_TIMER10_INTR_PEND_0                                                 (299U)
#define SDLR_R5FSS1_CORE1_INTR_TIMER11_INTR_PEND_0                                                 (300U)
#define SDLR_R5FSS1_CORE1_INTR_PCIE1_PCIE_LEGACY_PULSE_0                                           (301U)
#define SDLR_R5FSS1_CORE1_INTR_PCIE1_PCIE_DOWNSTREAM_PULSE_0                                       (302U)
#define SDLR_R5FSS1_CORE1_INTR_PCIE1_PCIE_FLR_PULSE_0                                              (303U)
#define SDLR_R5FSS1_CORE1_INTR_PCIE1_PCIE_PHY_LEVEL_0                                              (304U)
#define SDLR_R5FSS1_CORE1_INTR_PCIE1_PCIE_LOCAL_LEVEL_0                                            (305U)
#define SDLR_R5FSS1_CORE1_INTR_PCIE1_PCIE_ERROR_PULSE_0                                            (306U)
#define SDLR_R5FSS1_CORE1_INTR_PCIE1_PCIE_LINK_STATE_PULSE_0                                       (307U)
#define SDLR_R5FSS1_CORE1_INTR_PCIE1_PCIE_PWR_STATE_PULSE_0                                        (308U)
#define SDLR_R5FSS1_CORE1_INTR_PCIE1_PCIE_PTM_VALID_PULSE_0                                        (309U)
#define SDLR_R5FSS1_CORE1_INTR_PCIE1_PCIE_HOT_RESET_PULSE_0                                        (310U)
#define SDLR_R5FSS1_CORE1_INTR_PCIE1_PCIE_CPTS_PEND_0                                              (311U)
#define SDLR_R5FSS1_CORE1_INTR_PCIE1_PCIE_DPA_PULSE_0                                              (312U)
#define SDLR_R5FSS1_CORE1_INTR_DDR0_DDRSS_CONTROLLER_0                                             (313U)
#define SDLR_R5FSS1_CORE1_INTR_DDR0_DDRSS_V2A_OTHER_ERR_LVL_0                                      (314U)
#define SDLR_R5FSS1_CORE1_INTR_DDR0_DDRSS_HS_PHY_GLOBAL_ERROR_0                                    (315U)
#define SDLR_R5FSS1_CORE1_INTR_DDR0_DDRSS_PLL_FREQ_CHANGE_REQ_0                                    (316U)
#define SDLR_R5FSS1_CORE1_INTR_WKUP_SMS0_RAT_0_EXP_INTR_0                                          (317U)
#define SDLR_R5FSS1_CORE1_INTR_DCC0_INTR_DONE_LEVEL_0                                              (318U)
#define SDLR_R5FSS1_CORE1_INTR_DCC1_INTR_DONE_LEVEL_0                                              (319U)
#define SDLR_R5FSS1_CORE1_INTR_DCC2_INTR_DONE_LEVEL_0                                              (320U)
#define SDLR_R5FSS1_CORE1_INTR_DCC3_INTR_DONE_LEVEL_0                                              (321U)
#define SDLR_R5FSS1_CORE1_INTR_DCC4_INTR_DONE_LEVEL_0                                              (322U)
#define SDLR_R5FSS1_CORE1_INTR_DCC5_INTR_DONE_LEVEL_0                                              (323U)
#define SDLR_R5FSS1_CORE1_INTR_DCC6_INTR_DONE_LEVEL_0                                              (324U)
#define SDLR_R5FSS1_CORE1_INTR_DCC7_INTR_DONE_LEVEL_0                                              (325U)
#define SDLR_R5FSS1_CORE1_INTR_CMPEVENT_INTRTR0_OUTP_8                                             (326U)
#define SDLR_R5FSS1_CORE1_INTR_CMPEVENT_INTRTR0_OUTP_9                                             (327U)
#define SDLR_R5FSS1_CORE1_INTR_CMPEVENT_INTRTR0_OUTP_10                                            (328U)
#define SDLR_R5FSS1_CORE1_INTR_CMPEVENT_INTRTR0_OUTP_11                                            (329U)
#define SDLR_R5FSS1_CORE1_INTR_DCC8_INTR_DONE_LEVEL_0                                              (339U)
#define SDLR_R5FSS1_CORE1_INTR_DCC9_INTR_DONE_LEVEL_0                                              (340U)
#define SDLR_R5FSS1_CORE1_INTR_DEBUGSS0_AQCMPINTR_LEVEL_0                                          (342U)
#define SDLR_R5FSS1_CORE1_INTR_DEBUGSS0_CTM_LEVEL_0                                                (343U)
#define SDLR_R5FSS1_CORE1_INTR_CCDEBUGSS0_AQCMPINTR_LEVEL_0                                        (344U)
#define SDLR_R5FSS1_CORE1_INTR_CCDEBUGSS1_AQCMPINTR_LEVEL_0                                        (345U)
#define SDLR_R5FSS1_CORE1_INTR_MMCSD1_EMMCSDSS_INTR_0                                              (348U)
#define SDLR_R5FSS1_CORE1_INTR_DDR1_DDRSS_CONTROLLER_0                                             (350U)
#define SDLR_R5FSS1_CORE1_INTR_DDR1_DDRSS_V2A_OTHER_ERR_LVL_0                                      (351U)
#define SDLR_R5FSS1_CORE1_INTR_DDR1_DDRSS_HS_PHY_GLOBAL_ERROR_0                                    (352U)
#define SDLR_R5FSS1_CORE1_INTR_DDR1_DDRSS_PLL_FREQ_CHANGE_REQ_0                                    (353U)
#define SDLR_R5FSS1_CORE1_INTR_ECAP0_ECAP_INT_0                                                    (354U)
#define SDLR_R5FSS1_CORE1_INTR_ECAP1_ECAP_INT_0                                                    (355U)
#define SDLR_R5FSS1_CORE1_INTR_ECAP2_ECAP_INT_0                                                    (356U)
#define SDLR_R5FSS1_CORE1_INTR_GLUELOGIC_SOCA_INT_GLUE_SOCA_INT_0                                  (357U)
#define SDLR_R5FSS1_CORE1_INTR_GLUELOGIC_SOCB_INT_GLUE_SOCB_INT_0                                  (358U)
#define SDLR_R5FSS1_CORE1_INTR_USB0_HOST_SYSTEM_ERROR_0                                            (361U)
#define SDLR_R5FSS1_CORE1_INTR_GLUELOGIC_MAIN_CBASS_INTR_OR_GLUE_MAIN_CBASS_AGG_ERR_INTR_0         (362U)
#define SDLR_R5FSS1_CORE1_INTR_MAIN_CBASS0_DEFAULT_ERR_INTR_0                                      (363U)
#define SDLR_R5FSS1_CORE1_INTR_CBASS_INFRA_NON_SAFE0_DEFAULT_ERR_INTR_0                            (364U)
#define SDLR_R5FSS1_CORE1_INTR_CTRL_MMR0_ACCESS_ERR_0                                              (365U)
#define SDLR_R5FSS1_CORE1_INTR_WKUP_VTM0_THERM_LVL_GT_TH1_INTR_0                                   (366U)
#define SDLR_R5FSS1_CORE1_INTR_WKUP_VTM0_THERM_LVL_GT_TH2_INTR_0                                   (367U)
#define SDLR_R5FSS1_CORE1_INTR_WKUP_VTM0_THERM_LVL_LT_TH0_INTR_0                                   (368U)
#define SDLR_R5FSS1_CORE1_INTR_COMPUTE_CLUSTER0_GIC_OUTPUT_WAKER_GIC_PWR0_WAKE_REQUEST_0           (370U)
#define SDLR_R5FSS1_CORE1_INTR_COMPUTE_CLUSTER0_GIC_OUTPUT_WAKER_GIC_PWR0_WAKE_REQUEST_1           (371U)
#define SDLR_R5FSS1_CORE1_INTR_MCU_MCAN0_MCANSS_MCAN_LVL_INT_0                                     (374U)
#define SDLR_R5FSS1_CORE1_INTR_MCU_MCAN0_MCANSS_MCAN_LVL_INT_1                                     (375U)
#define SDLR_R5FSS1_CORE1_INTR_MCU_MCAN0_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                          (376U)
#define SDLR_R5FSS1_CORE1_INTR_MCU_MCAN1_MCANSS_MCAN_LVL_INT_0                                     (377U)
#define SDLR_R5FSS1_CORE1_INTR_MCU_MCAN1_MCANSS_MCAN_LVL_INT_1                                     (378U)
#define SDLR_R5FSS1_CORE1_INTR_MCU_MCAN1_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                          (379U)
#define SDLR_R5FSS1_CORE1_INTR_GPIOMUX_INTRTR0_OUTP_0                                              (396U)
#define SDLR_R5FSS1_CORE1_INTR_GPIOMUX_INTRTR0_OUTP_1                                              (397U)
#define SDLR_R5FSS1_CORE1_INTR_GPIOMUX_INTRTR0_OUTP_2                                              (398U)
#define SDLR_R5FSS1_CORE1_INTR_GPIOMUX_INTRTR0_OUTP_3                                              (399U)
#define SDLR_R5FSS1_CORE1_INTR_GPIOMUX_INTRTR0_OUTP_4                                              (400U)
#define SDLR_R5FSS1_CORE1_INTR_GPIOMUX_INTRTR0_OUTP_5                                              (401U)
#define SDLR_R5FSS1_CORE1_INTR_GPIOMUX_INTRTR0_OUTP_6                                              (402U)
#define SDLR_R5FSS1_CORE1_INTR_GPIOMUX_INTRTR0_OUTP_7                                              (403U)
#define SDLR_R5FSS1_CORE1_INTR_GPIOMUX_INTRTR0_OUTP_8                                              (404U)
#define SDLR_R5FSS1_CORE1_INTR_GPIOMUX_INTRTR0_OUTP_9                                              (405U)
#define SDLR_R5FSS1_CORE1_INTR_GPIOMUX_INTRTR0_OUTP_10                                             (406U)
#define SDLR_R5FSS1_CORE1_INTR_GPIOMUX_INTRTR0_OUTP_11                                             (407U)
#define SDLR_R5FSS1_CORE1_INTR_GPIOMUX_INTRTR0_OUTP_12                                             (408U)
#define SDLR_R5FSS1_CORE1_INTR_GPIOMUX_INTRTR0_OUTP_13                                             (409U)
#define SDLR_R5FSS1_CORE1_INTR_GPIOMUX_INTRTR0_OUTP_14                                             (410U)
#define SDLR_R5FSS1_CORE1_INTR_GPIOMUX_INTRTR0_OUTP_15                                             (411U)
#define SDLR_R5FSS1_CORE1_INTR_COMPUTE_CLUSTER0_CLEC_SOC_EVENTS_OUT_LEVEL_0                        (412U)
#define SDLR_R5FSS1_CORE1_INTR_COMPUTE_CLUSTER0_CLEC_SOC_EVENTS_OUT_LEVEL_1                        (413U)
#define SDLR_R5FSS1_CORE1_INTR_COMPUTE_CLUSTER0_CLEC_SOC_EVENTS_OUT_LEVEL_2                        (414U)
#define SDLR_R5FSS1_CORE1_INTR_COMPUTE_CLUSTER0_CLEC_SOC_EVENTS_OUT_LEVEL_3                        (415U)
#define SDLR_R5FSS1_CORE1_INTR_COMPUTE_CLUSTER0_CLEC_SOC_EVENTS_OUT_LEVEL_4                        (416U)
#define SDLR_R5FSS1_CORE1_INTR_COMPUTE_CLUSTER0_CLEC_SOC_EVENTS_OUT_LEVEL_5                        (417U)
#define SDLR_R5FSS1_CORE1_INTR_COMPUTE_CLUSTER0_CLEC_SOC_EVENTS_OUT_LEVEL_6                        (418U)
#define SDLR_R5FSS1_CORE1_INTR_COMPUTE_CLUSTER0_CLEC_SOC_EVENTS_OUT_LEVEL_7                        (419U)
#define SDLR_R5FSS1_CORE1_INTR_COMPUTE_CLUSTER0_CLEC_SOC_EVENTS_OUT_LEVEL_8                        (420U)
#define SDLR_R5FSS1_CORE1_INTR_COMPUTE_CLUSTER0_CLEC_SOC_EVENTS_OUT_LEVEL_9                        (421U)
#define SDLR_R5FSS1_CORE1_INTR_COMPUTE_CLUSTER0_CLEC_SOC_EVENTS_OUT_LEVEL_10                       (422U)
#define SDLR_R5FSS1_CORE1_INTR_COMPUTE_CLUSTER0_CLEC_SOC_EVENTS_OUT_LEVEL_11                       (423U)
#define SDLR_R5FSS1_CORE1_INTR_COMPUTE_CLUSTER0_CLEC_SOC_EVENTS_OUT_LEVEL_12                       (424U)
#define SDLR_R5FSS1_CORE1_INTR_COMPUTE_CLUSTER0_CLEC_SOC_EVENTS_OUT_LEVEL_13                       (425U)
#define SDLR_R5FSS1_CORE1_INTR_COMPUTE_CLUSTER0_CLEC_SOC_EVENTS_OUT_LEVEL_14                       (426U)
#define SDLR_R5FSS1_CORE1_INTR_COMPUTE_CLUSTER0_CLEC_SOC_EVENTS_OUT_LEVEL_15                       (427U)
#define SDLR_R5FSS1_CORE1_INTR_WKUP_SMS0_COMMON_0_SMS_IOPM_IO_SWAKEUP_INTR_0                       (438U)
#define SDLR_R5FSS1_CORE1_INTR_WKUP_SMS0_COMMON_0_SMS_IOPM_IO_SWAKEUP_INTR_1                       (439U)
#define SDLR_R5FSS1_CORE1_INTR_WKUP_SMS0_COMMON_0_SMS_IOPM_DEBUG_ACTIVATED_INTR_0                  (440U)
#define SDLR_R5FSS1_CORE1_INTR_WKUP_SMS0_COMMON_0_SMS_IOPM_DEBUG_DEACTIVATED_INTR_0                (441U)
#define SDLR_R5FSS1_CORE1_INTR_WKUP_SMS0_COMMON_0_SMS_IOPM_DEBUG_FORCEACTIVE_INTR_0                (442U)
#define SDLR_R5FSS1_CORE1_INTR_MCU_ADC12FCC0_GEN_LEVEL_0                                           (444U)
#define SDLR_R5FSS1_CORE1_INTR_MCU_ADC12FCC1_GEN_LEVEL_0                                           (445U)
#define SDLR_R5FSS1_CORE1_INTR_MCU_CPSW0_STAT_PEND_0                                               (446U)
#define SDLR_R5FSS1_CORE1_INTR_MCU_CPSW0_MDIO_PEND_0                                               (447U)
#define SDLR_R5FSS1_CORE1_INTR_MCU_CPSW0_EVNT_PEND_0                                               (448U)
#define SDLR_R5FSS1_CORE1_INTR_MCU_DCC0_INTR_DONE_LEVEL_0                                          (449U)
#define SDLR_R5FSS1_CORE1_INTR_MCU_DCC1_INTR_DONE_LEVEL_0                                          (450U)
#define SDLR_R5FSS1_CORE1_INTR_MCU_DCC2_INTR_DONE_LEVEL_0                                          (451U)
#define SDLR_R5FSS1_CORE1_INTR_MCU_TIMER0_INTR_PEND_0                                              (452U)
#define SDLR_R5FSS1_CORE1_INTR_MCU_TIMER1_INTR_PEND_0                                              (453U)
#define SDLR_R5FSS1_CORE1_INTR_MCU_TIMER2_INTR_PEND_0                                              (454U)
#define SDLR_R5FSS1_CORE1_INTR_MCU_TIMER3_INTR_PEND_0                                              (455U)
#define SDLR_R5FSS1_CORE1_INTR_MCU_TIMER4_INTR_PEND_0                                              (456U)
#define SDLR_R5FSS1_CORE1_INTR_MCU_TIMER5_INTR_PEND_0                                              (457U)
#define SDLR_R5FSS1_CORE1_INTR_MCU_TIMER6_INTR_PEND_0                                              (458U)
#define SDLR_R5FSS1_CORE1_INTR_MCU_TIMER7_INTR_PEND_0                                              (459U)
#define SDLR_R5FSS1_CORE1_INTR_MCU_TIMER8_INTR_PEND_0                                              (460U)
#define SDLR_R5FSS1_CORE1_INTR_MCU_TIMER9_INTR_PEND_0                                              (461U)
#define SDLR_R5FSS1_CORE1_INTR_MCU_I2C0_POINTRPEND_0                                               (462U)
#define SDLR_R5FSS1_CORE1_INTR_MCU_I2C1_POINTRPEND_0                                               (463U)
#define SDLR_R5FSS1_CORE1_INTR_MCU_MCSPI0_INTR_SPI_0                                               (464U)
#define SDLR_R5FSS1_CORE1_INTR_MCU_MCSPI1_INTR_SPI_0                                               (465U)
#define SDLR_R5FSS1_CORE1_INTR_MCU_MCSPI2_INTR_SPI_0                                               (466U)
#define SDLR_R5FSS1_CORE1_INTR_MCU_UART0_USART_IRQ_0                                               (467U)
#define SDLR_R5FSS1_CORE1_INTR_MCU_I3C0_I3C__INT_0                                                 (468U)
#define SDLR_R5FSS1_CORE1_INTR_MCU_I3C1_I3C__INT_0                                                 (469U)
#define SDLR_R5FSS1_CORE1_INTR_MCU_FSS0_OSPI_0_OSPI_LVL_INTR_0                                     (470U)
#define SDLR_R5FSS1_CORE1_INTR_MCU_FSS0_OSPI_1_OSPI_LVL_INTR_0                                     (471U)
#define SDLR_R5FSS1_CORE1_INTR_MCU_FSS0_HYPERBUS1P0_0_HPB_INTR_0                                   (472U)
#define SDLR_R5FSS1_CORE1_INTR_MCU_FSS0_FSAS_0_OTFA_INTR_ERR_PEND_0                                (473U)
#define SDLR_R5FSS1_CORE1_INTR_MCU_FSS0_FSAS_0_ECC_INTR_ERR_PEND_0                                 (474U)
#define SDLR_R5FSS1_CORE1_INTR_MCU_SA3_SS0_SA_UL_0_SA_UL_PKA_0                                     (475U)
#define SDLR_R5FSS1_CORE1_INTR_MCU_SA3_SS0_SA_UL_0_SA_UL_TRNG_0                                    (476U)
#define SDLR_R5FSS1_CORE1_INTR_MCU_ESM0_ESM_INT_LOW_LVL_0                                          (477U)
#define SDLR_R5FSS1_CORE1_INTR_MCU_ESM0_ESM_INT_HI_LVL_0                                           (478U)
#define SDLR_R5FSS1_CORE1_INTR_MCU_ESM0_ESM_INT_CFG_LVL_0                                          (479U)
#define SDLR_R5FSS1_CORE1_INTR_MCU_CTRL_MMR0_ACCESS_ERR_0                                          (480U)
#define SDLR_R5FSS1_CORE1_INTR_MCU_CBASS0_DEFAULT_ERR_INTR_0                                       (481U)
#define SDLR_R5FSS1_CORE1_INTR_GLUELOGIC_DBG_CBASS_INTR_OR_GLUE_DBG_CBASS_AGG_ERR_INTR_0           (482U)
#define SDLR_R5FSS1_CORE1_INTR_GLUELOGIC_FW_CBASS_INTR_OR_GLUE_FW_CBASS_AGG_ERR_INTR_0             (483U)
#define SDLR_R5FSS1_CORE1_INTR_WKUP_CBASS0_DEFAULT_ERR_INTR_0                                      (485U)
#define SDLR_R5FSS1_CORE1_INTR_WKUP_I2C0_POINTRPEND_0                                              (486U)
#define SDLR_R5FSS1_CORE1_INTR_WKUP_UART0_USART_IRQ_0                                              (487U)
#define SDLR_R5FSS1_CORE1_INTR_WKUP_GPIOMUX_INTRTR0_OUTP_16                                        (488U)
#define SDLR_R5FSS1_CORE1_INTR_WKUP_GPIOMUX_INTRTR0_OUTP_17                                        (489U)
#define SDLR_R5FSS1_CORE1_INTR_WKUP_GPIOMUX_INTRTR0_OUTP_18                                        (490U)
#define SDLR_R5FSS1_CORE1_INTR_WKUP_GPIOMUX_INTRTR0_OUTP_19                                        (491U)
#define SDLR_R5FSS1_CORE1_INTR_WKUP_GPIOMUX_INTRTR0_OUTP_20                                        (492U)
#define SDLR_R5FSS1_CORE1_INTR_WKUP_GPIOMUX_INTRTR0_OUTP_21                                        (493U)
#define SDLR_R5FSS1_CORE1_INTR_WKUP_GPIOMUX_INTRTR0_OUTP_22                                        (494U)
#define SDLR_R5FSS1_CORE1_INTR_WKUP_GPIOMUX_INTRTR0_OUTP_23                                        (495U)
#define SDLR_R5FSS1_CORE1_INTR_WKUP_GPIOMUX_INTRTR0_OUTP_24                                        (496U)
#define SDLR_R5FSS1_CORE1_INTR_WKUP_GPIOMUX_INTRTR0_OUTP_25                                        (497U)
#define SDLR_R5FSS1_CORE1_INTR_WKUP_GPIOMUX_INTRTR0_OUTP_26                                        (498U)
#define SDLR_R5FSS1_CORE1_INTR_WKUP_GPIOMUX_INTRTR0_OUTP_27                                        (499U)
#define SDLR_R5FSS1_CORE1_INTR_WKUP_GPIOMUX_INTRTR0_OUTP_28                                        (500U)
#define SDLR_R5FSS1_CORE1_INTR_WKUP_GPIOMUX_INTRTR0_OUTP_29                                        (501U)
#define SDLR_R5FSS1_CORE1_INTR_WKUP_GPIOMUX_INTRTR0_OUTP_30                                        (502U)
#define SDLR_R5FSS1_CORE1_INTR_WKUP_GPIOMUX_INTRTR0_OUTP_31                                        (503U)
#define SDLR_R5FSS1_CORE1_INTR_WKUP_ESM0_ESM_INT_LOW_LVL_0                                         (504U)
#define SDLR_R5FSS1_CORE1_INTR_WKUP_ESM0_ESM_INT_HI_LVL_0                                          (505U)
#define SDLR_R5FSS1_CORE1_INTR_WKUP_ESM0_ESM_INT_CFG_LVL_0                                         (506U)
#define SDLR_R5FSS1_CORE1_INTR_WKUP_SMS0_TIFS_CBASS_0_FW_EXCEPTION_INTR_0                          (507U)
#define SDLR_R5FSS1_CORE1_INTR_WKUP_SMS0_COMMON_0_COMBINED_SEC_IN_0                                (508U)
#define SDLR_R5FSS1_CORE1_INTR_WKUP_SMS0_HSM_CBASS_0_FW_EXCEPTION_INTR_0                           (509U)

#ifdef __cplusplus
}
#endif
#endif /* SDLR_R5FSS1_CORE1_INTERRUPT_MAP_H_ */

