/********************************************************************
*
* SOC QOS PROPERTIES. header file
*
* Copyright (C) 2015-2019 Texas Instruments Incorporated.
*  Redistribution and use in source and binary forms, with or without
*  modification, are permitted provided that the following conditions
*  are met:
*
*    Redistributions of source code must retain the above copyright
*    notice, this list of conditions and the following disclaimer.
*
*    Redistributions in binary form must reproduce the above copyright
*    notice, this list of conditions and the following disclaimer in the
*    documentation and/or other materials provided with the
*    distribution.
*
*    Neither the name of Texas Instruments Incorporated nor the names of
*    its contributors may be used to endorse or promote products derived
*    from this software without specific prior written permission.
*
*  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
*  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
*  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
*  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
*  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
*  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
*  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
*  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
*  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
*  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
*  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
*/
#ifndef CSLR_SOC_QOS_H_
#define CSLR_SOC_QOS_H_

#include <ti/csl/cslr.h>
#include <ti/csl/tistdtypes.h>
#ifdef __cplusplus
extern "C"
{
#endif

/*
* Auto-generated CSL definitions for SoC QOS Instances:
*/


/* Properties of QOS in: WKUP_SMS0 */
#define CSL_QOS_WKUP_SMS0_TIFS_VBUSP_M_MMR_BASE                                                    (0x45d00000ul)
#define CSL_QOS_WKUP_SMS0_TIFS_VBUSP_M_CHANNEL_COUNT                                               (1U)
#define CSL_QOS_WKUP_SMS0_TIFS_VBUSP_M_QOS_CAPABLE                                                 (0U)
#define CSL_QOS_WKUP_SMS0_TIFS_VBUSP_M_VIRTID_CAPABLE                                              (0U)
#define CSL_QOS_WKUP_SMS0_TIFS_VBUSP_M_ORDERID_CAPABLE                                             (0U)
#define CSL_QOS_WKUP_SMS0_TIFS_VBUSP_M_EPRIORITY_CAPABLE                                           (1U)
#define CSL_QOS_WKUP_SMS0_TIFS_VBUSP_M_ATYPE_CAPABLE                                               (0U)
#define CSL_QOS_WKUP_SMS0_TIFS_VBUSP_M_ASEL_CAPABLE                                                (1U)
#define CSL_QOS_WKUP_SMS0_HSM_VBUSP_M_MMR_BASE                                                     (0x45d00400ul)
#define CSL_QOS_WKUP_SMS0_HSM_VBUSP_M_CHANNEL_COUNT                                                (1U)
#define CSL_QOS_WKUP_SMS0_HSM_VBUSP_M_QOS_CAPABLE                                                  (0U)
#define CSL_QOS_WKUP_SMS0_HSM_VBUSP_M_VIRTID_CAPABLE                                               (0U)
#define CSL_QOS_WKUP_SMS0_HSM_VBUSP_M_ORDERID_CAPABLE                                              (0U)
#define CSL_QOS_WKUP_SMS0_HSM_VBUSP_M_EPRIORITY_CAPABLE                                            (1U)
#define CSL_QOS_WKUP_SMS0_HSM_VBUSP_M_ATYPE_CAPABLE                                                (0U)
#define CSL_QOS_WKUP_SMS0_HSM_VBUSP_M_ASEL_CAPABLE                                                 (1U)

/* Properties of QOS in: MCU_R5FSS0 */
#define CSL_QOS_MCU_R5FSS0_CPU0_RMST_MMR_BASE                                                      (0x45d10000ul)
#define CSL_QOS_MCU_R5FSS0_CPU0_RMST_CHANNEL_COUNT                                                 (1U)
#define CSL_QOS_MCU_R5FSS0_CPU0_RMST_QOS_CAPABLE                                                   (0U)
#define CSL_QOS_MCU_R5FSS0_CPU0_RMST_VIRTID_CAPABLE                                                (1U)
#define CSL_QOS_MCU_R5FSS0_CPU0_RMST_ORDERID_CAPABLE                                               (1U)
#define CSL_QOS_MCU_R5FSS0_CPU0_RMST_EPRIORITY_CAPABLE                                             (1U)
#define CSL_QOS_MCU_R5FSS0_CPU0_RMST_ATYPE_CAPABLE                                                 (1U)
#define CSL_QOS_MCU_R5FSS0_CPU0_RMST_ASEL_CAPABLE                                                  (1U)
#define CSL_QOS_MCU_R5FSS0_CPU0_WMST_MMR_BASE                                                      (0x45d10400ul)
#define CSL_QOS_MCU_R5FSS0_CPU0_WMST_CHANNEL_COUNT                                                 (1U)
#define CSL_QOS_MCU_R5FSS0_CPU0_WMST_QOS_CAPABLE                                                   (0U)
#define CSL_QOS_MCU_R5FSS0_CPU0_WMST_VIRTID_CAPABLE                                                (1U)
#define CSL_QOS_MCU_R5FSS0_CPU0_WMST_ORDERID_CAPABLE                                               (1U)
#define CSL_QOS_MCU_R5FSS0_CPU0_WMST_EPRIORITY_CAPABLE                                             (1U)
#define CSL_QOS_MCU_R5FSS0_CPU0_WMST_ATYPE_CAPABLE                                                 (1U)
#define CSL_QOS_MCU_R5FSS0_CPU0_WMST_ASEL_CAPABLE                                                  (1U)
#define CSL_QOS_MCU_R5FSS0_CPU0_PMST_MMR_BASE                                                      (0x45d10800ul)
#define CSL_QOS_MCU_R5FSS0_CPU0_PMST_CHANNEL_COUNT                                                 (1U)
#define CSL_QOS_MCU_R5FSS0_CPU0_PMST_QOS_CAPABLE                                                   (0U)
#define CSL_QOS_MCU_R5FSS0_CPU0_PMST_VIRTID_CAPABLE                                                (0U)
#define CSL_QOS_MCU_R5FSS0_CPU0_PMST_ORDERID_CAPABLE                                               (1U)
#define CSL_QOS_MCU_R5FSS0_CPU0_PMST_EPRIORITY_CAPABLE                                             (1U)
#define CSL_QOS_MCU_R5FSS0_CPU0_PMST_ATYPE_CAPABLE                                                 (0U)
#define CSL_QOS_MCU_R5FSS0_CPU0_PMST_ASEL_CAPABLE                                                  (1U)
#define CSL_QOS_MCU_R5FSS0_CPU1_RMST_MMR_BASE                                                      (0x45d11000ul)
#define CSL_QOS_MCU_R5FSS0_CPU1_RMST_CHANNEL_COUNT                                                 (1U)
#define CSL_QOS_MCU_R5FSS0_CPU1_RMST_QOS_CAPABLE                                                   (0U)
#define CSL_QOS_MCU_R5FSS0_CPU1_RMST_VIRTID_CAPABLE                                                (1U)
#define CSL_QOS_MCU_R5FSS0_CPU1_RMST_ORDERID_CAPABLE                                               (1U)
#define CSL_QOS_MCU_R5FSS0_CPU1_RMST_EPRIORITY_CAPABLE                                             (1U)
#define CSL_QOS_MCU_R5FSS0_CPU1_RMST_ATYPE_CAPABLE                                                 (1U)
#define CSL_QOS_MCU_R5FSS0_CPU1_RMST_ASEL_CAPABLE                                                  (1U)
#define CSL_QOS_MCU_R5FSS0_CPU1_WMST_MMR_BASE                                                      (0x45d11400ul)
#define CSL_QOS_MCU_R5FSS0_CPU1_WMST_CHANNEL_COUNT                                                 (1U)
#define CSL_QOS_MCU_R5FSS0_CPU1_WMST_QOS_CAPABLE                                                   (0U)
#define CSL_QOS_MCU_R5FSS0_CPU1_WMST_VIRTID_CAPABLE                                                (1U)
#define CSL_QOS_MCU_R5FSS0_CPU1_WMST_ORDERID_CAPABLE                                               (1U)
#define CSL_QOS_MCU_R5FSS0_CPU1_WMST_EPRIORITY_CAPABLE                                             (1U)
#define CSL_QOS_MCU_R5FSS0_CPU1_WMST_ATYPE_CAPABLE                                                 (1U)
#define CSL_QOS_MCU_R5FSS0_CPU1_WMST_ASEL_CAPABLE                                                  (1U)
#define CSL_QOS_MCU_R5FSS0_CPU1_PMST_MMR_BASE                                                      (0x45d11800ul)
#define CSL_QOS_MCU_R5FSS0_CPU1_PMST_CHANNEL_COUNT                                                 (1U)
#define CSL_QOS_MCU_R5FSS0_CPU1_PMST_QOS_CAPABLE                                                   (0U)
#define CSL_QOS_MCU_R5FSS0_CPU1_PMST_VIRTID_CAPABLE                                                (0U)
#define CSL_QOS_MCU_R5FSS0_CPU1_PMST_ORDERID_CAPABLE                                               (1U)
#define CSL_QOS_MCU_R5FSS0_CPU1_PMST_EPRIORITY_CAPABLE                                             (1U)
#define CSL_QOS_MCU_R5FSS0_CPU1_PMST_ATYPE_CAPABLE                                                 (0U)
#define CSL_QOS_MCU_R5FSS0_CPU1_PMST_ASEL_CAPABLE                                                  (1U)

/* Properties of QOS in: MCU_SA3_SS0 */
#define CSL_QOS_MCU_SA3_SS0_CTXCACH_EXT_DMA_MMR_BASE                                               (0x45d13000ul)
#define CSL_QOS_MCU_SA3_SS0_CTXCACH_EXT_DMA_CHANNEL_COUNT                                          (1U)
#define CSL_QOS_MCU_SA3_SS0_CTXCACH_EXT_DMA_QOS_CAPABLE                                            (0U)
#define CSL_QOS_MCU_SA3_SS0_CTXCACH_EXT_DMA_VIRTID_CAPABLE                                         (0U)
#define CSL_QOS_MCU_SA3_SS0_CTXCACH_EXT_DMA_ORDERID_CAPABLE                                        (1U)
#define CSL_QOS_MCU_SA3_SS0_CTXCACH_EXT_DMA_EPRIORITY_CAPABLE                                      (1U)
#define CSL_QOS_MCU_SA3_SS0_CTXCACH_EXT_DMA_ATYPE_CAPABLE                                          (0U)
#define CSL_QOS_MCU_SA3_SS0_CTXCACH_EXT_DMA_ASEL_CAPABLE                                           (1U)

/* Properties of QOS in: MCU_NAVSS0_PROXY0 */
#define CSL_QOS_MCU_NAVSS0_PROXY0_DST_MMR_BASE                                                     (0x45d20000ul)
#define CSL_QOS_MCU_NAVSS0_PROXY0_DST_CHANNEL_COUNT                                                (1U)
#define CSL_QOS_MCU_NAVSS0_PROXY0_DST_QOS_CAPABLE                                                  (0U)
#define CSL_QOS_MCU_NAVSS0_PROXY0_DST_VIRTID_CAPABLE                                               (0U)
#define CSL_QOS_MCU_NAVSS0_PROXY0_DST_ORDERID_CAPABLE                                              (1U)
#define CSL_QOS_MCU_NAVSS0_PROXY0_DST_EPRIORITY_CAPABLE                                            (1U)
#define CSL_QOS_MCU_NAVSS0_PROXY0_DST_ATYPE_CAPABLE                                                (1U)
#define CSL_QOS_MCU_NAVSS0_PROXY0_DST_ASEL_CAPABLE                                                 (1U)

/* Properties of QOS in: MCU_NAVSS0_SEC_PROXY0 */
#define CSL_QOS_MCU_NAVSS0_SEC_PROXY0_DST_MMR_BASE                                                 (0x45d20400ul)
#define CSL_QOS_MCU_NAVSS0_SEC_PROXY0_DST_CHANNEL_COUNT                                            (1U)
#define CSL_QOS_MCU_NAVSS0_SEC_PROXY0_DST_QOS_CAPABLE                                              (0U)
#define CSL_QOS_MCU_NAVSS0_SEC_PROXY0_DST_VIRTID_CAPABLE                                           (0U)
#define CSL_QOS_MCU_NAVSS0_SEC_PROXY0_DST_ORDERID_CAPABLE                                          (0U)
#define CSL_QOS_MCU_NAVSS0_SEC_PROXY0_DST_EPRIORITY_CAPABLE                                        (1U)
#define CSL_QOS_MCU_NAVSS0_SEC_PROXY0_DST_ATYPE_CAPABLE                                            (1U)
#define CSL_QOS_MCU_NAVSS0_SEC_PROXY0_DST_ASEL_CAPABLE                                             (1U)

/* Properties of QOS in: MCU_NAVSS0_RINGACC0 */
#define CSL_QOS_MCU_NAVSS0_RINGACC0_RINGACC0_DST_MMR_BASE                                          (0x45d20c00ul)
#define CSL_QOS_MCU_NAVSS0_RINGACC0_RINGACC0_DST_CHANNEL_COUNT                                     (1U)
#define CSL_QOS_MCU_NAVSS0_RINGACC0_RINGACC0_DST_QOS_CAPABLE                                       (0U)
#define CSL_QOS_MCU_NAVSS0_RINGACC0_RINGACC0_DST_VIRTID_CAPABLE                                    (0U)
#define CSL_QOS_MCU_NAVSS0_RINGACC0_RINGACC0_DST_ORDERID_CAPABLE                                   (0U)
#define CSL_QOS_MCU_NAVSS0_RINGACC0_RINGACC0_DST_EPRIORITY_CAPABLE                                 (0U)
#define CSL_QOS_MCU_NAVSS0_RINGACC0_RINGACC0_DST_ATYPE_CAPABLE                                     (0U)
#define CSL_QOS_MCU_NAVSS0_RINGACC0_RINGACC0_DST_ASEL_CAPABLE                                      (0U)

/* Properties of QOS in: NAVSS0_PROXY_0 */
#define CSL_QOS_NAVSS0_PROXY_0_DST_MMR_BASE                                                        (0x45d40000ul)
#define CSL_QOS_NAVSS0_PROXY_0_DST_CHANNEL_COUNT                                                   (1U)
#define CSL_QOS_NAVSS0_PROXY_0_DST_QOS_CAPABLE                                                     (0U)
#define CSL_QOS_NAVSS0_PROXY_0_DST_VIRTID_CAPABLE                                                  (0U)
#define CSL_QOS_NAVSS0_PROXY_0_DST_ORDERID_CAPABLE                                                 (1U)
#define CSL_QOS_NAVSS0_PROXY_0_DST_EPRIORITY_CAPABLE                                               (1U)
#define CSL_QOS_NAVSS0_PROXY_0_DST_ATYPE_CAPABLE                                                   (1U)
#define CSL_QOS_NAVSS0_PROXY_0_DST_ASEL_CAPABLE                                                    (1U)

/* Properties of QOS in: NAVSS0_SEC_PROXY_0 */
#define CSL_QOS_NAVSS0_SEC_PROXY_0_DST_MMR_BASE                                                    (0x45d40400ul)
#define CSL_QOS_NAVSS0_SEC_PROXY_0_DST_CHANNEL_COUNT                                               (1U)
#define CSL_QOS_NAVSS0_SEC_PROXY_0_DST_QOS_CAPABLE                                                 (0U)
#define CSL_QOS_NAVSS0_SEC_PROXY_0_DST_VIRTID_CAPABLE                                              (0U)
#define CSL_QOS_NAVSS0_SEC_PROXY_0_DST_ORDERID_CAPABLE                                             (0U)
#define CSL_QOS_NAVSS0_SEC_PROXY_0_DST_EPRIORITY_CAPABLE                                           (1U)
#define CSL_QOS_NAVSS0_SEC_PROXY_0_DST_ATYPE_CAPABLE                                               (1U)
#define CSL_QOS_NAVSS0_SEC_PROXY_0_DST_ASEL_CAPABLE                                                (1U)

/* Properties of QOS in: R5FSS0 */
#define CSL_QOS_R5FSS0_PBDG_RMST0_MMR_BASE                                                         (0x45d78000ul)
#define CSL_QOS_R5FSS0_PBDG_RMST0_CHANNEL_COUNT                                                    (1U)
#define CSL_QOS_R5FSS0_PBDG_RMST0_QOS_CAPABLE                                                      (0U)
#define CSL_QOS_R5FSS0_PBDG_RMST0_VIRTID_CAPABLE                                                   (1U)
#define CSL_QOS_R5FSS0_PBDG_RMST0_ORDERID_CAPABLE                                                  (1U)
#define CSL_QOS_R5FSS0_PBDG_RMST0_EPRIORITY_CAPABLE                                                (1U)
#define CSL_QOS_R5FSS0_PBDG_RMST0_ATYPE_CAPABLE                                                    (1U)
#define CSL_QOS_R5FSS0_PBDG_RMST0_ASEL_CAPABLE                                                     (1U)
#define CSL_QOS_R5FSS0_PBDG_WMST0_MMR_BASE                                                         (0x45d78400ul)
#define CSL_QOS_R5FSS0_PBDG_WMST0_CHANNEL_COUNT                                                    (1U)
#define CSL_QOS_R5FSS0_PBDG_WMST0_QOS_CAPABLE                                                      (0U)
#define CSL_QOS_R5FSS0_PBDG_WMST0_VIRTID_CAPABLE                                                   (1U)
#define CSL_QOS_R5FSS0_PBDG_WMST0_ORDERID_CAPABLE                                                  (1U)
#define CSL_QOS_R5FSS0_PBDG_WMST0_EPRIORITY_CAPABLE                                                (1U)
#define CSL_QOS_R5FSS0_PBDG_WMST0_ATYPE_CAPABLE                                                    (1U)
#define CSL_QOS_R5FSS0_PBDG_WMST0_ASEL_CAPABLE                                                     (1U)
#define CSL_QOS_R5FSS0_PBDG_RMST1_MMR_BASE                                                         (0x45d78800ul)
#define CSL_QOS_R5FSS0_PBDG_RMST1_CHANNEL_COUNT                                                    (1U)
#define CSL_QOS_R5FSS0_PBDG_RMST1_QOS_CAPABLE                                                      (0U)
#define CSL_QOS_R5FSS0_PBDG_RMST1_VIRTID_CAPABLE                                                   (1U)
#define CSL_QOS_R5FSS0_PBDG_RMST1_ORDERID_CAPABLE                                                  (1U)
#define CSL_QOS_R5FSS0_PBDG_RMST1_EPRIORITY_CAPABLE                                                (1U)
#define CSL_QOS_R5FSS0_PBDG_RMST1_ATYPE_CAPABLE                                                    (1U)
#define CSL_QOS_R5FSS0_PBDG_RMST1_ASEL_CAPABLE                                                     (1U)
#define CSL_QOS_R5FSS0_PBDG_WMST1_MMR_BASE                                                         (0x45d78c00ul)
#define CSL_QOS_R5FSS0_PBDG_WMST1_CHANNEL_COUNT                                                    (1U)
#define CSL_QOS_R5FSS0_PBDG_WMST1_QOS_CAPABLE                                                      (0U)
#define CSL_QOS_R5FSS0_PBDG_WMST1_VIRTID_CAPABLE                                                   (1U)
#define CSL_QOS_R5FSS0_PBDG_WMST1_ORDERID_CAPABLE                                                  (1U)
#define CSL_QOS_R5FSS0_PBDG_WMST1_EPRIORITY_CAPABLE                                                (1U)
#define CSL_QOS_R5FSS0_PBDG_WMST1_ATYPE_CAPABLE                                                    (1U)
#define CSL_QOS_R5FSS0_PBDG_WMST1_ASEL_CAPABLE                                                     (1U)
#define CSL_QOS_R5FSS0_CPU0_RMST_MMR_BASE                                                          (0x45dc8000ul)
#define CSL_QOS_R5FSS0_CPU0_RMST_CHANNEL_COUNT                                                     (1U)
#define CSL_QOS_R5FSS0_CPU0_RMST_QOS_CAPABLE                                                       (0U)
#define CSL_QOS_R5FSS0_CPU0_RMST_VIRTID_CAPABLE                                                    (1U)
#define CSL_QOS_R5FSS0_CPU0_RMST_ORDERID_CAPABLE                                                   (1U)
#define CSL_QOS_R5FSS0_CPU0_RMST_EPRIORITY_CAPABLE                                                 (1U)
#define CSL_QOS_R5FSS0_CPU0_RMST_ATYPE_CAPABLE                                                     (1U)
#define CSL_QOS_R5FSS0_CPU0_RMST_ASEL_CAPABLE                                                      (1U)
#define CSL_QOS_R5FSS0_CPU0_WMST_MMR_BASE                                                          (0x45dc8400ul)
#define CSL_QOS_R5FSS0_CPU0_WMST_CHANNEL_COUNT                                                     (1U)
#define CSL_QOS_R5FSS0_CPU0_WMST_QOS_CAPABLE                                                       (0U)
#define CSL_QOS_R5FSS0_CPU0_WMST_VIRTID_CAPABLE                                                    (1U)
#define CSL_QOS_R5FSS0_CPU0_WMST_ORDERID_CAPABLE                                                   (1U)
#define CSL_QOS_R5FSS0_CPU0_WMST_EPRIORITY_CAPABLE                                                 (1U)
#define CSL_QOS_R5FSS0_CPU0_WMST_ATYPE_CAPABLE                                                     (1U)
#define CSL_QOS_R5FSS0_CPU0_WMST_ASEL_CAPABLE                                                      (1U)
#define CSL_QOS_R5FSS0_CPU1_RMST_MMR_BASE                                                          (0x45dc8800ul)
#define CSL_QOS_R5FSS0_CPU1_RMST_CHANNEL_COUNT                                                     (1U)
#define CSL_QOS_R5FSS0_CPU1_RMST_QOS_CAPABLE                                                       (0U)
#define CSL_QOS_R5FSS0_CPU1_RMST_VIRTID_CAPABLE                                                    (1U)
#define CSL_QOS_R5FSS0_CPU1_RMST_ORDERID_CAPABLE                                                   (1U)
#define CSL_QOS_R5FSS0_CPU1_RMST_EPRIORITY_CAPABLE                                                 (1U)
#define CSL_QOS_R5FSS0_CPU1_RMST_ATYPE_CAPABLE                                                     (1U)
#define CSL_QOS_R5FSS0_CPU1_RMST_ASEL_CAPABLE                                                      (1U)
#define CSL_QOS_R5FSS0_CPU1_WMST_MMR_BASE                                                          (0x45dc8c00ul)
#define CSL_QOS_R5FSS0_CPU1_WMST_CHANNEL_COUNT                                                     (1U)
#define CSL_QOS_R5FSS0_CPU1_WMST_QOS_CAPABLE                                                       (0U)
#define CSL_QOS_R5FSS0_CPU1_WMST_VIRTID_CAPABLE                                                    (1U)
#define CSL_QOS_R5FSS0_CPU1_WMST_ORDERID_CAPABLE                                                   (1U)
#define CSL_QOS_R5FSS0_CPU1_WMST_EPRIORITY_CAPABLE                                                 (1U)
#define CSL_QOS_R5FSS0_CPU1_WMST_ATYPE_CAPABLE                                                     (1U)
#define CSL_QOS_R5FSS0_CPU1_WMST_ASEL_CAPABLE                                                      (1U)

/* Properties of QOS in: MMCSD1 */
#define CSL_QOS_MMCSD1_EMMCSDSS_RD_MMR_BASE                                                        (0x45d82800ul)
#define CSL_QOS_MMCSD1_EMMCSDSS_RD_CHANNEL_COUNT                                                   (1U)
#define CSL_QOS_MMCSD1_EMMCSDSS_RD_QOS_CAPABLE                                                     (0U)
#define CSL_QOS_MMCSD1_EMMCSDSS_RD_VIRTID_CAPABLE                                                  (1U)
#define CSL_QOS_MMCSD1_EMMCSDSS_RD_ORDERID_CAPABLE                                                 (1U)
#define CSL_QOS_MMCSD1_EMMCSDSS_RD_EPRIORITY_CAPABLE                                               (1U)
#define CSL_QOS_MMCSD1_EMMCSDSS_RD_ATYPE_CAPABLE                                                   (1U)
#define CSL_QOS_MMCSD1_EMMCSDSS_RD_ASEL_CAPABLE                                                    (1U)
#define CSL_QOS_MMCSD1_EMMCSDSS_WR_MMR_BASE                                                        (0x45d82c00ul)
#define CSL_QOS_MMCSD1_EMMCSDSS_WR_CHANNEL_COUNT                                                   (1U)
#define CSL_QOS_MMCSD1_EMMCSDSS_WR_QOS_CAPABLE                                                     (0U)
#define CSL_QOS_MMCSD1_EMMCSDSS_WR_VIRTID_CAPABLE                                                  (1U)
#define CSL_QOS_MMCSD1_EMMCSDSS_WR_ORDERID_CAPABLE                                                 (1U)
#define CSL_QOS_MMCSD1_EMMCSDSS_WR_EPRIORITY_CAPABLE                                               (1U)
#define CSL_QOS_MMCSD1_EMMCSDSS_WR_ATYPE_CAPABLE                                                   (1U)
#define CSL_QOS_MMCSD1_EMMCSDSS_WR_ASEL_CAPABLE                                                    (1U)

/* Properties of QOS in: PCIE1 */
#define CSL_QOS_PCIE1_PCIE_MST_RD_MMR_BASE                                                         (0x45d99400ul)
#define CSL_QOS_PCIE1_PCIE_MST_RD_CHANNEL_COUNT                                                    (8U)
#define CSL_QOS_PCIE1_PCIE_MST_RD_QOS_CAPABLE                                                      (0U)
#define CSL_QOS_PCIE1_PCIE_MST_RD_VIRTID_CAPABLE                                                   (0U)
#define CSL_QOS_PCIE1_PCIE_MST_RD_ORDERID_CAPABLE                                                  (1U)
#define CSL_QOS_PCIE1_PCIE_MST_RD_EPRIORITY_CAPABLE                                                (1U)
#define CSL_QOS_PCIE1_PCIE_MST_RD_ATYPE_CAPABLE                                                    (0U)
#define CSL_QOS_PCIE1_PCIE_MST_RD_ASEL_CAPABLE                                                     (1U)
#define CSL_QOS_PCIE1_PCIE_MST_WR_MMR_BASE                                                         (0x45d99c00ul)
#define CSL_QOS_PCIE1_PCIE_MST_WR_CHANNEL_COUNT                                                    (8U)
#define CSL_QOS_PCIE1_PCIE_MST_WR_QOS_CAPABLE                                                      (0U)
#define CSL_QOS_PCIE1_PCIE_MST_WR_VIRTID_CAPABLE                                                   (0U)
#define CSL_QOS_PCIE1_PCIE_MST_WR_ORDERID_CAPABLE                                                  (1U)
#define CSL_QOS_PCIE1_PCIE_MST_WR_EPRIORITY_CAPABLE                                                (1U)
#define CSL_QOS_PCIE1_PCIE_MST_WR_ATYPE_CAPABLE                                                    (0U)
#define CSL_QOS_PCIE1_PCIE_MST_WR_ASEL_CAPABLE                                                     (1U)

/* Properties of QOS in: USB0 */
#define CSL_QOS_USB0_MSTR0_MMR_BASE                                                                (0x45d9a000ul)
#define CSL_QOS_USB0_MSTR0_CHANNEL_COUNT                                                           (8U)
#define CSL_QOS_USB0_MSTR0_QOS_CAPABLE                                                             (0U)
#define CSL_QOS_USB0_MSTR0_VIRTID_CAPABLE                                                          (1U)
#define CSL_QOS_USB0_MSTR0_ORDERID_CAPABLE                                                         (1U)
#define CSL_QOS_USB0_MSTR0_EPRIORITY_CAPABLE                                                       (1U)
#define CSL_QOS_USB0_MSTR0_ATYPE_CAPABLE                                                           (1U)
#define CSL_QOS_USB0_MSTR0_ASEL_CAPABLE                                                            (1U)
#define CSL_QOS_USB0_MSTW0_MMR_BASE                                                                (0x45d9a400ul)
#define CSL_QOS_USB0_MSTW0_CHANNEL_COUNT                                                           (8U)
#define CSL_QOS_USB0_MSTW0_QOS_CAPABLE                                                             (0U)
#define CSL_QOS_USB0_MSTW0_VIRTID_CAPABLE                                                          (1U)
#define CSL_QOS_USB0_MSTW0_ORDERID_CAPABLE                                                         (1U)
#define CSL_QOS_USB0_MSTW0_EPRIORITY_CAPABLE                                                       (1U)
#define CSL_QOS_USB0_MSTW0_ATYPE_CAPABLE                                                           (1U)
#define CSL_QOS_USB0_MSTW0_ASEL_CAPABLE                                                            (1U)

/* Properties of QOS in: MMCSD0 */
#define CSL_QOS_MMCSD0_EMMCSS_WR_MMR_BASE                                                          (0x45d9b400ul)
#define CSL_QOS_MMCSD0_EMMCSS_WR_CHANNEL_COUNT                                                     (1U)
#define CSL_QOS_MMCSD0_EMMCSS_WR_QOS_CAPABLE                                                       (0U)
#define CSL_QOS_MMCSD0_EMMCSS_WR_VIRTID_CAPABLE                                                    (1U)
#define CSL_QOS_MMCSD0_EMMCSS_WR_ORDERID_CAPABLE                                                   (1U)
#define CSL_QOS_MMCSD0_EMMCSS_WR_EPRIORITY_CAPABLE                                                 (1U)
#define CSL_QOS_MMCSD0_EMMCSS_WR_ATYPE_CAPABLE                                                     (1U)
#define CSL_QOS_MMCSD0_EMMCSS_WR_ASEL_CAPABLE                                                      (1U)
#define CSL_QOS_MMCSD0_EMMCSS_RD_MMR_BASE                                                          (0x45d9b800ul)
#define CSL_QOS_MMCSD0_EMMCSS_RD_CHANNEL_COUNT                                                     (1U)
#define CSL_QOS_MMCSD0_EMMCSS_RD_QOS_CAPABLE                                                       (0U)
#define CSL_QOS_MMCSD0_EMMCSS_RD_VIRTID_CAPABLE                                                    (1U)
#define CSL_QOS_MMCSD0_EMMCSS_RD_ORDERID_CAPABLE                                                   (1U)
#define CSL_QOS_MMCSD0_EMMCSS_RD_EPRIORITY_CAPABLE                                                 (1U)
#define CSL_QOS_MMCSD0_EMMCSS_RD_ATYPE_CAPABLE                                                     (1U)
#define CSL_QOS_MMCSD0_EMMCSS_RD_ASEL_CAPABLE                                                      (1U)

/* Properties of QOS in: SA2_UL0 */
#define CSL_QOS_SA2_UL0_CTXCACH_EXT_DMA_MMR_BASE                                                   (0x45d9bc00ul)
#define CSL_QOS_SA2_UL0_CTXCACH_EXT_DMA_CHANNEL_COUNT                                              (1U)
#define CSL_QOS_SA2_UL0_CTXCACH_EXT_DMA_QOS_CAPABLE                                                (0U)
#define CSL_QOS_SA2_UL0_CTXCACH_EXT_DMA_VIRTID_CAPABLE                                             (1U)
#define CSL_QOS_SA2_UL0_CTXCACH_EXT_DMA_ORDERID_CAPABLE                                            (1U)
#define CSL_QOS_SA2_UL0_CTXCACH_EXT_DMA_EPRIORITY_CAPABLE                                          (1U)
#define CSL_QOS_SA2_UL0_CTXCACH_EXT_DMA_ATYPE_CAPABLE                                              (1U)
#define CSL_QOS_SA2_UL0_CTXCACH_EXT_DMA_ASEL_CAPABLE                                               (1U)

/* Properties of QOS in: VUSR_DUAL0 */
#define CSL_QOS_VUSR_DUAL0_V0_M_MMR_BASE                                                           (0x45d9c000ul)
#define CSL_QOS_VUSR_DUAL0_V0_M_CHANNEL_COUNT                                                      (1U)
#define CSL_QOS_VUSR_DUAL0_V0_M_QOS_CAPABLE                                                        (0U)
#define CSL_QOS_VUSR_DUAL0_V0_M_VIRTID_CAPABLE                                                     (1U)
#define CSL_QOS_VUSR_DUAL0_V0_M_ORDERID_CAPABLE                                                    (1U)
#define CSL_QOS_VUSR_DUAL0_V0_M_EPRIORITY_CAPABLE                                                  (0U)
#define CSL_QOS_VUSR_DUAL0_V0_M_ATYPE_CAPABLE                                                      (1U)
#define CSL_QOS_VUSR_DUAL0_V0_M_ASEL_CAPABLE                                                       (1U)
#define CSL_QOS_VUSR_DUAL0_V1_M_MMR_BASE                                                           (0x45d9c400ul)
#define CSL_QOS_VUSR_DUAL0_V1_M_CHANNEL_COUNT                                                      (1U)
#define CSL_QOS_VUSR_DUAL0_V1_M_QOS_CAPABLE                                                        (0U)
#define CSL_QOS_VUSR_DUAL0_V1_M_VIRTID_CAPABLE                                                     (1U)
#define CSL_QOS_VUSR_DUAL0_V1_M_ORDERID_CAPABLE                                                    (1U)
#define CSL_QOS_VUSR_DUAL0_V1_M_EPRIORITY_CAPABLE                                                  (0U)
#define CSL_QOS_VUSR_DUAL0_V1_M_ATYPE_CAPABLE                                                      (1U)
#define CSL_QOS_VUSR_DUAL0_V1_M_ASEL_CAPABLE                                                       (1U)

/* Properties of QOS in: DEBUGSS_WRAP0 */
#define CSL_QOS_DEBUGSS_WRAP0_VBUSMR_MMR_BASE                                                      (0x45da0000ul)
#define CSL_QOS_DEBUGSS_WRAP0_VBUSMR_CHANNEL_COUNT                                                 (1U)
#define CSL_QOS_DEBUGSS_WRAP0_VBUSMR_QOS_CAPABLE                                                   (0U)
#define CSL_QOS_DEBUGSS_WRAP0_VBUSMR_VIRTID_CAPABLE                                                (0U)
#define CSL_QOS_DEBUGSS_WRAP0_VBUSMR_ORDERID_CAPABLE                                               (1U)
#define CSL_QOS_DEBUGSS_WRAP0_VBUSMR_EPRIORITY_CAPABLE                                             (1U)
#define CSL_QOS_DEBUGSS_WRAP0_VBUSMR_ATYPE_CAPABLE                                                 (0U)
#define CSL_QOS_DEBUGSS_WRAP0_VBUSMR_ASEL_CAPABLE                                                  (1U)
#define CSL_QOS_DEBUGSS_WRAP0_VBUSMW_MMR_BASE                                                      (0x45da0400ul)
#define CSL_QOS_DEBUGSS_WRAP0_VBUSMW_CHANNEL_COUNT                                                 (1U)
#define CSL_QOS_DEBUGSS_WRAP0_VBUSMW_QOS_CAPABLE                                                   (0U)
#define CSL_QOS_DEBUGSS_WRAP0_VBUSMW_VIRTID_CAPABLE                                                (0U)
#define CSL_QOS_DEBUGSS_WRAP0_VBUSMW_ORDERID_CAPABLE                                               (1U)
#define CSL_QOS_DEBUGSS_WRAP0_VBUSMW_EPRIORITY_CAPABLE                                             (1U)
#define CSL_QOS_DEBUGSS_WRAP0_VBUSMW_ATYPE_CAPABLE                                                 (0U)
#define CSL_QOS_DEBUGSS_WRAP0_VBUSMW_ASEL_CAPABLE                                                  (1U)

/* Properties of QOS in: R5FSS1 */
#define CSL_QOS_R5FSS1_CPU0_RMST_MMR_BASE                                                          (0x45da8000ul)
#define CSL_QOS_R5FSS1_CPU0_RMST_CHANNEL_COUNT                                                     (1U)
#define CSL_QOS_R5FSS1_CPU0_RMST_QOS_CAPABLE                                                       (0U)
#define CSL_QOS_R5FSS1_CPU0_RMST_VIRTID_CAPABLE                                                    (1U)
#define CSL_QOS_R5FSS1_CPU0_RMST_ORDERID_CAPABLE                                                   (1U)
#define CSL_QOS_R5FSS1_CPU0_RMST_EPRIORITY_CAPABLE                                                 (1U)
#define CSL_QOS_R5FSS1_CPU0_RMST_ATYPE_CAPABLE                                                     (1U)
#define CSL_QOS_R5FSS1_CPU0_RMST_ASEL_CAPABLE                                                      (1U)
#define CSL_QOS_R5FSS1_CPU0_WMST_MMR_BASE                                                          (0x45da8400ul)
#define CSL_QOS_R5FSS1_CPU0_WMST_CHANNEL_COUNT                                                     (1U)
#define CSL_QOS_R5FSS1_CPU0_WMST_QOS_CAPABLE                                                       (0U)
#define CSL_QOS_R5FSS1_CPU0_WMST_VIRTID_CAPABLE                                                    (1U)
#define CSL_QOS_R5FSS1_CPU0_WMST_ORDERID_CAPABLE                                                   (1U)
#define CSL_QOS_R5FSS1_CPU0_WMST_EPRIORITY_CAPABLE                                                 (1U)
#define CSL_QOS_R5FSS1_CPU0_WMST_ATYPE_CAPABLE                                                     (1U)
#define CSL_QOS_R5FSS1_CPU0_WMST_ASEL_CAPABLE                                                      (1U)
#define CSL_QOS_R5FSS1_CPU1_RMST_MMR_BASE                                                          (0x45da8800ul)
#define CSL_QOS_R5FSS1_CPU1_RMST_CHANNEL_COUNT                                                     (1U)
#define CSL_QOS_R5FSS1_CPU1_RMST_QOS_CAPABLE                                                       (0U)
#define CSL_QOS_R5FSS1_CPU1_RMST_VIRTID_CAPABLE                                                    (1U)
#define CSL_QOS_R5FSS1_CPU1_RMST_ORDERID_CAPABLE                                                   (1U)
#define CSL_QOS_R5FSS1_CPU1_RMST_EPRIORITY_CAPABLE                                                 (1U)
#define CSL_QOS_R5FSS1_CPU1_RMST_ATYPE_CAPABLE                                                     (1U)
#define CSL_QOS_R5FSS1_CPU1_RMST_ASEL_CAPABLE                                                      (1U)
#define CSL_QOS_R5FSS1_CPU1_WMST_MMR_BASE                                                          (0x45da8c00ul)
#define CSL_QOS_R5FSS1_CPU1_WMST_CHANNEL_COUNT                                                     (1U)
#define CSL_QOS_R5FSS1_CPU1_WMST_QOS_CAPABLE                                                       (0U)
#define CSL_QOS_R5FSS1_CPU1_WMST_VIRTID_CAPABLE                                                    (1U)
#define CSL_QOS_R5FSS1_CPU1_WMST_ORDERID_CAPABLE                                                   (1U)
#define CSL_QOS_R5FSS1_CPU1_WMST_EPRIORITY_CAPABLE                                                 (1U)
#define CSL_QOS_R5FSS1_CPU1_WMST_ATYPE_CAPABLE                                                     (1U)
#define CSL_QOS_R5FSS1_CPU1_WMST_ASEL_CAPABLE                                                      (1U)
#define CSL_QOS_R5FSS1_PBDG_RMST0_MMR_BASE                                                         (0x45dca000ul)
#define CSL_QOS_R5FSS1_PBDG_RMST0_CHANNEL_COUNT                                                    (1U)
#define CSL_QOS_R5FSS1_PBDG_RMST0_QOS_CAPABLE                                                      (0U)
#define CSL_QOS_R5FSS1_PBDG_RMST0_VIRTID_CAPABLE                                                   (1U)
#define CSL_QOS_R5FSS1_PBDG_RMST0_ORDERID_CAPABLE                                                  (1U)
#define CSL_QOS_R5FSS1_PBDG_RMST0_EPRIORITY_CAPABLE                                                (1U)
#define CSL_QOS_R5FSS1_PBDG_RMST0_ATYPE_CAPABLE                                                    (1U)
#define CSL_QOS_R5FSS1_PBDG_RMST0_ASEL_CAPABLE                                                     (1U)
#define CSL_QOS_R5FSS1_PBDG_WMST0_MMR_BASE                                                         (0x45dca400ul)
#define CSL_QOS_R5FSS1_PBDG_WMST0_CHANNEL_COUNT                                                    (1U)
#define CSL_QOS_R5FSS1_PBDG_WMST0_QOS_CAPABLE                                                      (0U)
#define CSL_QOS_R5FSS1_PBDG_WMST0_VIRTID_CAPABLE                                                   (1U)
#define CSL_QOS_R5FSS1_PBDG_WMST0_ORDERID_CAPABLE                                                  (1U)
#define CSL_QOS_R5FSS1_PBDG_WMST0_EPRIORITY_CAPABLE                                                (1U)
#define CSL_QOS_R5FSS1_PBDG_WMST0_ATYPE_CAPABLE                                                    (1U)
#define CSL_QOS_R5FSS1_PBDG_WMST0_ASEL_CAPABLE                                                     (1U)
#define CSL_QOS_R5FSS1_PBDG_RMST1_MMR_BASE                                                         (0x45dca800ul)
#define CSL_QOS_R5FSS1_PBDG_RMST1_CHANNEL_COUNT                                                    (1U)
#define CSL_QOS_R5FSS1_PBDG_RMST1_QOS_CAPABLE                                                      (0U)
#define CSL_QOS_R5FSS1_PBDG_RMST1_VIRTID_CAPABLE                                                   (1U)
#define CSL_QOS_R5FSS1_PBDG_RMST1_ORDERID_CAPABLE                                                  (1U)
#define CSL_QOS_R5FSS1_PBDG_RMST1_EPRIORITY_CAPABLE                                                (1U)
#define CSL_QOS_R5FSS1_PBDG_RMST1_ATYPE_CAPABLE                                                    (1U)
#define CSL_QOS_R5FSS1_PBDG_RMST1_ASEL_CAPABLE                                                     (1U)
#define CSL_QOS_R5FSS1_PBDG_WMST1_MMR_BASE                                                         (0x45dcac00ul)
#define CSL_QOS_R5FSS1_PBDG_WMST1_CHANNEL_COUNT                                                    (1U)
#define CSL_QOS_R5FSS1_PBDG_WMST1_QOS_CAPABLE                                                      (0U)
#define CSL_QOS_R5FSS1_PBDG_WMST1_VIRTID_CAPABLE                                                   (1U)
#define CSL_QOS_R5FSS1_PBDG_WMST1_ORDERID_CAPABLE                                                  (1U)
#define CSL_QOS_R5FSS1_PBDG_WMST1_EPRIORITY_CAPABLE                                                (1U)
#define CSL_QOS_R5FSS1_PBDG_WMST1_ATYPE_CAPABLE                                                    (1U)
#define CSL_QOS_R5FSS1_PBDG_WMST1_ASEL_CAPABLE                                                     (1U)

/* Properties of QOS in: DMPAC0 */
#define CSL_QOS_DMPAC0_DATA_MST_MMR_BASE                                                           (0x45dc0000ul)
#define CSL_QOS_DMPAC0_DATA_MST_CHANNEL_COUNT                                                      (32U)
#define CSL_QOS_DMPAC0_DATA_MST_QOS_CAPABLE                                                        (0U)
#define CSL_QOS_DMPAC0_DATA_MST_VIRTID_CAPABLE                                                     (1U)
#define CSL_QOS_DMPAC0_DATA_MST_ORDERID_CAPABLE                                                    (0U)
#define CSL_QOS_DMPAC0_DATA_MST_EPRIORITY_CAPABLE                                                  (0U)
#define CSL_QOS_DMPAC0_DATA_MST_ATYPE_CAPABLE                                                      (1U)
#define CSL_QOS_DMPAC0_DATA_MST_ASEL_CAPABLE                                                       (1U)

/* Properties of QOS in: K3_VPU_WAVE521CL0 */
#define CSL_QOS_K3_VPU_WAVE521CL0_SEC_M_VBUSM_R_ASYNC_MMR_BASE                                     (0x45dc0c00ul)
#define CSL_QOS_K3_VPU_WAVE521CL0_SEC_M_VBUSM_R_ASYNC_CHANNEL_COUNT                                (1U)
#define CSL_QOS_K3_VPU_WAVE521CL0_SEC_M_VBUSM_R_ASYNC_QOS_CAPABLE                                  (0U)
#define CSL_QOS_K3_VPU_WAVE521CL0_SEC_M_VBUSM_R_ASYNC_VIRTID_CAPABLE                               (1U)
#define CSL_QOS_K3_VPU_WAVE521CL0_SEC_M_VBUSM_R_ASYNC_ORDERID_CAPABLE                              (1U)
#define CSL_QOS_K3_VPU_WAVE521CL0_SEC_M_VBUSM_R_ASYNC_EPRIORITY_CAPABLE                            (1U)
#define CSL_QOS_K3_VPU_WAVE521CL0_SEC_M_VBUSM_R_ASYNC_ATYPE_CAPABLE                                (1U)
#define CSL_QOS_K3_VPU_WAVE521CL0_SEC_M_VBUSM_R_ASYNC_ASEL_CAPABLE                                 (1U)
#define CSL_QOS_K3_VPU_WAVE521CL0_SEC_M_VBUSM_W_ASYNC_MMR_BASE                                     (0x45dc1000ul)
#define CSL_QOS_K3_VPU_WAVE521CL0_SEC_M_VBUSM_W_ASYNC_CHANNEL_COUNT                                (1U)
#define CSL_QOS_K3_VPU_WAVE521CL0_SEC_M_VBUSM_W_ASYNC_QOS_CAPABLE                                  (0U)
#define CSL_QOS_K3_VPU_WAVE521CL0_SEC_M_VBUSM_W_ASYNC_VIRTID_CAPABLE                               (1U)
#define CSL_QOS_K3_VPU_WAVE521CL0_SEC_M_VBUSM_W_ASYNC_ORDERID_CAPABLE                              (1U)
#define CSL_QOS_K3_VPU_WAVE521CL0_SEC_M_VBUSM_W_ASYNC_EPRIORITY_CAPABLE                            (1U)
#define CSL_QOS_K3_VPU_WAVE521CL0_SEC_M_VBUSM_W_ASYNC_ATYPE_CAPABLE                                (1U)
#define CSL_QOS_K3_VPU_WAVE521CL0_SEC_M_VBUSM_W_ASYNC_ASEL_CAPABLE                                 (1U)
#define CSL_QOS_K3_VPU_WAVE521CL0_PRI_M_VBUSM_R_ASYNC_MMR_BASE                                     (0x45dc3400ul)
#define CSL_QOS_K3_VPU_WAVE521CL0_PRI_M_VBUSM_R_ASYNC_CHANNEL_COUNT                                (5U)
#define CSL_QOS_K3_VPU_WAVE521CL0_PRI_M_VBUSM_R_ASYNC_QOS_CAPABLE                                  (0U)
#define CSL_QOS_K3_VPU_WAVE521CL0_PRI_M_VBUSM_R_ASYNC_VIRTID_CAPABLE                               (1U)
#define CSL_QOS_K3_VPU_WAVE521CL0_PRI_M_VBUSM_R_ASYNC_ORDERID_CAPABLE                              (1U)
#define CSL_QOS_K3_VPU_WAVE521CL0_PRI_M_VBUSM_R_ASYNC_EPRIORITY_CAPABLE                            (1U)
#define CSL_QOS_K3_VPU_WAVE521CL0_PRI_M_VBUSM_R_ASYNC_ATYPE_CAPABLE                                (1U)
#define CSL_QOS_K3_VPU_WAVE521CL0_PRI_M_VBUSM_R_ASYNC_ASEL_CAPABLE                                 (1U)
#define CSL_QOS_K3_VPU_WAVE521CL0_PRI_M_VBUSM_W_ASYNC_MMR_BASE                                     (0x45dc3800ul)
#define CSL_QOS_K3_VPU_WAVE521CL0_PRI_M_VBUSM_W_ASYNC_CHANNEL_COUNT                                (5U)
#define CSL_QOS_K3_VPU_WAVE521CL0_PRI_M_VBUSM_W_ASYNC_QOS_CAPABLE                                  (0U)
#define CSL_QOS_K3_VPU_WAVE521CL0_PRI_M_VBUSM_W_ASYNC_VIRTID_CAPABLE                               (1U)
#define CSL_QOS_K3_VPU_WAVE521CL0_PRI_M_VBUSM_W_ASYNC_ORDERID_CAPABLE                              (1U)
#define CSL_QOS_K3_VPU_WAVE521CL0_PRI_M_VBUSM_W_ASYNC_EPRIORITY_CAPABLE                            (1U)
#define CSL_QOS_K3_VPU_WAVE521CL0_PRI_M_VBUSM_W_ASYNC_ATYPE_CAPABLE                                (1U)
#define CSL_QOS_K3_VPU_WAVE521CL0_PRI_M_VBUSM_W_ASYNC_ASEL_CAPABLE                                 (1U)

/* Properties of QOS in: VPAC0 */
#define CSL_QOS_VPAC0_DATA_MST_0_MMR_BASE                                                          (0x45dc1400ul)
#define CSL_QOS_VPAC0_DATA_MST_0_CHANNEL_COUNT                                                     (32U)
#define CSL_QOS_VPAC0_DATA_MST_0_QOS_CAPABLE                                                       (0U)
#define CSL_QOS_VPAC0_DATA_MST_0_VIRTID_CAPABLE                                                    (1U)
#define CSL_QOS_VPAC0_DATA_MST_0_ORDERID_CAPABLE                                                   (0U)
#define CSL_QOS_VPAC0_DATA_MST_0_EPRIORITY_CAPABLE                                                 (0U)
#define CSL_QOS_VPAC0_DATA_MST_0_ATYPE_CAPABLE                                                     (1U)
#define CSL_QOS_VPAC0_DATA_MST_0_ASEL_CAPABLE                                                      (1U)
#define CSL_QOS_VPAC0_DATA_MST_1_MMR_BASE                                                          (0x45dc1800ul)
#define CSL_QOS_VPAC0_DATA_MST_1_CHANNEL_COUNT                                                     (64U)
#define CSL_QOS_VPAC0_DATA_MST_1_QOS_CAPABLE                                                       (0U)
#define CSL_QOS_VPAC0_DATA_MST_1_VIRTID_CAPABLE                                                    (1U)
#define CSL_QOS_VPAC0_DATA_MST_1_ORDERID_CAPABLE                                                   (0U)
#define CSL_QOS_VPAC0_DATA_MST_1_EPRIORITY_CAPABLE                                                 (0U)
#define CSL_QOS_VPAC0_DATA_MST_1_ATYPE_CAPABLE                                                     (1U)
#define CSL_QOS_VPAC0_DATA_MST_1_ASEL_CAPABLE                                                      (1U)
#define CSL_QOS_VPAC0_LDC0_M_MST_MMR_BASE                                                          (0x45dc1c00ul)
#define CSL_QOS_VPAC0_LDC0_M_MST_CHANNEL_COUNT                                                     (3U)
#define CSL_QOS_VPAC0_LDC0_M_MST_QOS_CAPABLE                                                       (0U)
#define CSL_QOS_VPAC0_LDC0_M_MST_VIRTID_CAPABLE                                                    (1U)
#define CSL_QOS_VPAC0_LDC0_M_MST_ORDERID_CAPABLE                                                   (1U)
#define CSL_QOS_VPAC0_LDC0_M_MST_EPRIORITY_CAPABLE                                                 (1U)
#define CSL_QOS_VPAC0_LDC0_M_MST_ATYPE_CAPABLE                                                     (1U)
#define CSL_QOS_VPAC0_LDC0_M_MST_ASEL_CAPABLE                                                      (1U)

/* Properties of QOS in: DSS0 */
#define CSL_QOS_DSS0_DSS_INST0_VBUSM_DMA_MMR_BASE                                                  (0x45dc2000ul)
#define CSL_QOS_DSS0_DSS_INST0_VBUSM_DMA_CHANNEL_COUNT                                             (10U)
#define CSL_QOS_DSS0_DSS_INST0_VBUSM_DMA_QOS_CAPABLE                                               (0U)
#define CSL_QOS_DSS0_DSS_INST0_VBUSM_DMA_VIRTID_CAPABLE                                            (1U)
#define CSL_QOS_DSS0_DSS_INST0_VBUSM_DMA_ORDERID_CAPABLE                                           (1U)
#define CSL_QOS_DSS0_DSS_INST0_VBUSM_DMA_EPRIORITY_CAPABLE                                         (0U)
#define CSL_QOS_DSS0_DSS_INST0_VBUSM_DMA_ATYPE_CAPABLE                                             (1U)
#define CSL_QOS_DSS0_DSS_INST0_VBUSM_DMA_ASEL_CAPABLE                                              (1U)
#define CSL_QOS_DSS0_DSS_INST0_VBUSM_FBDC_MMR_BASE                                                 (0x45dc2400ul)
#define CSL_QOS_DSS0_DSS_INST0_VBUSM_FBDC_CHANNEL_COUNT                                            (10U)
#define CSL_QOS_DSS0_DSS_INST0_VBUSM_FBDC_QOS_CAPABLE                                              (0U)
#define CSL_QOS_DSS0_DSS_INST0_VBUSM_FBDC_VIRTID_CAPABLE                                           (1U)
#define CSL_QOS_DSS0_DSS_INST0_VBUSM_FBDC_ORDERID_CAPABLE                                          (1U)
#define CSL_QOS_DSS0_DSS_INST0_VBUSM_FBDC_EPRIORITY_CAPABLE                                        (0U)
#define CSL_QOS_DSS0_DSS_INST0_VBUSM_FBDC_ATYPE_CAPABLE                                            (1U)
#define CSL_QOS_DSS0_DSS_INST0_VBUSM_FBDC_ASEL_CAPABLE                                             (1U)

/* Properties of QOS in: AEP_GPU_BXS464_WRAP0 */
#define CSL_QOS_AEP_GPU_BXS464_WRAP0_M_VBUSM_R_SYNC_MMR_BASE                                       (0x45dc5000ul)
#define CSL_QOS_AEP_GPU_BXS464_WRAP0_M_VBUSM_R_SYNC_CHANNEL_COUNT                                  (160U)
#define CSL_QOS_AEP_GPU_BXS464_WRAP0_M_VBUSM_R_SYNC_QOS_CAPABLE                                    (0U)
#define CSL_QOS_AEP_GPU_BXS464_WRAP0_M_VBUSM_R_SYNC_VIRTID_CAPABLE                                 (1U)
#define CSL_QOS_AEP_GPU_BXS464_WRAP0_M_VBUSM_R_SYNC_ORDERID_CAPABLE                                (1U)
#define CSL_QOS_AEP_GPU_BXS464_WRAP0_M_VBUSM_R_SYNC_EPRIORITY_CAPABLE                              (1U)
#define CSL_QOS_AEP_GPU_BXS464_WRAP0_M_VBUSM_R_SYNC_ATYPE_CAPABLE                                  (1U)
#define CSL_QOS_AEP_GPU_BXS464_WRAP0_M_VBUSM_R_SYNC_ASEL_CAPABLE                                   (1U)
#define CSL_QOS_AEP_GPU_BXS464_WRAP0_M_VBUSM_W_SYNC_MMR_BASE                                       (0x45dc5800ul)
#define CSL_QOS_AEP_GPU_BXS464_WRAP0_M_VBUSM_W_SYNC_CHANNEL_COUNT                                  (160U)
#define CSL_QOS_AEP_GPU_BXS464_WRAP0_M_VBUSM_W_SYNC_QOS_CAPABLE                                    (0U)
#define CSL_QOS_AEP_GPU_BXS464_WRAP0_M_VBUSM_W_SYNC_VIRTID_CAPABLE                                 (1U)
#define CSL_QOS_AEP_GPU_BXS464_WRAP0_M_VBUSM_W_SYNC_ORDERID_CAPABLE                                (1U)
#define CSL_QOS_AEP_GPU_BXS464_WRAP0_M_VBUSM_W_SYNC_EPRIORITY_CAPABLE                              (1U)
#define CSL_QOS_AEP_GPU_BXS464_WRAP0_M_VBUSM_W_SYNC_ATYPE_CAPABLE                                  (1U)
#define CSL_QOS_AEP_GPU_BXS464_WRAP0_M_VBUSM_W_SYNC_ASEL_CAPABLE                                   (1U)

#ifdef __cplusplus
}
#endif
#endif /* CSLR_SOC_QOS_H_ */

