/********************************************************************
*
* NAVSS0_UDMASS_INTA_0 INTERRUPT MAP. header file
*
* Copyright (C) 2015-2020 Texas Instruments Incorporated.
*  Redistribution and use in source and binary forms, with or without
*  modification, are permitted provided that the following conditions
*  are met:
*
*    Redistributions of source code must retain the above copyright
*    notice, this list of conditions and the following disclaimer.
*
*    Redistributions in binary form must reproduce the above copyright
*    notice, this list of conditions and the following disclaimer in the
*    documentation and/or other materials provided with the
*    distribution.
*
*    Neither the name of Texas Instruments Incorporated nor the names of
*    its contributors may be used to endorse or promote products derived
*    from this software without specific prior written permission.
*
*  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
*  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
*  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
*  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
*  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
*  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
*  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
*  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
*  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
*  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
*  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
*/
#ifndef CSLR_NAVSS0_UDMASS_INTA_0_INTERRUPT_MAP_H_
#define CSLR_NAVSS0_UDMASS_INTA_0_INTERRUPT_MAP_H_

#include <ti/csl/cslr.h>
#include <ti/csl/tistdtypes.h>
#ifdef __cplusplus
extern "C"
{
#endif

/*
* List of intr sources for receiver: NAVSS0_UDMASS_INTA_0
*/

#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MCRC_0_DMA_EVENT_INTR_0                 (0U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MCRC_0_DMA_EVENT_INTR_1                 (1U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MCRC_0_DMA_EVENT_INTR_2                 (2U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MCRC_0_DMA_EVENT_INTR_3                 (3U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX1_0_PEND_INTR_0                  (4U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX1_0_PEND_INTR_1                  (5U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX1_0_PEND_INTR_2                  (6U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX1_0_PEND_INTR_3                  (7U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX1_1_PEND_INTR_0                  (8U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX1_1_PEND_INTR_1                  (9U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX1_1_PEND_INTR_2                  (10U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX1_1_PEND_INTR_3                  (11U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX1_2_PEND_INTR_0                  (12U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX1_2_PEND_INTR_1                  (13U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX1_2_PEND_INTR_2                  (14U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX1_2_PEND_INTR_3                  (15U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX1_3_PEND_INTR_0                  (16U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX1_3_PEND_INTR_1                  (17U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX1_3_PEND_INTR_2                  (18U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX1_3_PEND_INTR_3                  (19U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX1_4_PEND_INTR_0                  (20U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX1_4_PEND_INTR_1                  (21U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX1_4_PEND_INTR_2                  (22U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX1_4_PEND_INTR_3                  (23U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX1_5_PEND_INTR_0                  (24U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX1_5_PEND_INTR_1                  (25U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX1_5_PEND_INTR_2                  (26U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX1_5_PEND_INTR_3                  (27U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX1_6_PEND_INTR_0                  (28U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX1_6_PEND_INTR_1                  (29U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX1_6_PEND_INTR_2                  (30U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX1_6_PEND_INTR_3                  (31U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX1_7_PEND_INTR_0                  (32U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX1_7_PEND_INTR_1                  (33U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX1_7_PEND_INTR_2                  (34U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX1_7_PEND_INTR_3                  (35U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX1_8_PEND_INTR_0                  (36U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX1_8_PEND_INTR_1                  (37U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX1_8_PEND_INTR_2                  (38U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX1_8_PEND_INTR_3                  (39U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX1_9_PEND_INTR_0                  (40U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX1_9_PEND_INTR_1                  (41U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX1_9_PEND_INTR_2                  (42U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX1_9_PEND_INTR_3                  (43U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX1_10_PEND_INTR_0                 (44U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX1_10_PEND_INTR_1                 (45U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX1_10_PEND_INTR_2                 (46U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX1_10_PEND_INTR_3                 (47U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX1_11_PEND_INTR_0                 (48U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX1_11_PEND_INTR_1                 (49U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX1_11_PEND_INTR_2                 (50U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX1_11_PEND_INTR_3                 (51U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_0_PEND_INTR_0                   (52U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_0_PEND_INTR_1                   (53U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_0_PEND_INTR_2                   (54U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_0_PEND_INTR_3                   (55U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_1_PEND_INTR_0                   (56U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_1_PEND_INTR_1                   (57U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_1_PEND_INTR_2                   (58U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_1_PEND_INTR_3                   (59U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_2_PEND_INTR_0                   (60U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_2_PEND_INTR_1                   (61U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_2_PEND_INTR_2                   (62U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_2_PEND_INTR_3                   (63U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_3_PEND_INTR_0                   (64U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_3_PEND_INTR_1                   (65U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_3_PEND_INTR_2                   (66U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_3_PEND_INTR_3                   (67U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_4_PEND_INTR_0                   (68U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_4_PEND_INTR_1                   (69U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_4_PEND_INTR_2                   (70U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_4_PEND_INTR_3                   (71U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_5_PEND_INTR_0                   (72U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_5_PEND_INTR_1                   (73U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_5_PEND_INTR_2                   (74U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_5_PEND_INTR_3                   (75U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_6_PEND_INTR_0                   (76U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_6_PEND_INTR_1                   (77U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_6_PEND_INTR_2                   (78U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_6_PEND_INTR_3                   (79U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_7_PEND_INTR_0                   (80U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_7_PEND_INTR_1                   (81U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_7_PEND_INTR_2                   (82U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_7_PEND_INTR_3                   (83U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_8_PEND_INTR_0                   (84U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_8_PEND_INTR_1                   (85U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_8_PEND_INTR_2                   (86U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_8_PEND_INTR_3                   (87U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_9_PEND_INTR_0                   (88U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_9_PEND_INTR_1                   (89U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_9_PEND_INTR_2                   (90U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_9_PEND_INTR_3                   (91U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_10_PEND_INTR_0                  (92U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_10_PEND_INTR_1                  (93U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_10_PEND_INTR_2                  (94U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_10_PEND_INTR_3                  (95U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_11_PEND_INTR_0                  (96U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_11_PEND_INTR_1                  (97U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_11_PEND_INTR_2                  (98U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_NAVSS0_MAILBOX_11_PEND_INTR_3                  (99U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_TIMESYNC_INTRTR0_OUTL_40                       (100U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_TIMESYNC_INTRTR0_OUTL_41                       (101U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_TIMESYNC_INTRTR0_OUTL_42                       (102U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_TIMESYNC_INTRTR0_OUTL_43                       (103U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_TIMESYNC_INTRTR0_OUTL_44                       (104U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_TIMESYNC_INTRTR0_OUTL_45                       (105U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_TIMESYNC_INTRTR0_OUTL_46                       (106U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_TIMESYNC_INTRTR0_OUTL_47                       (107U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_CMPEVENT_INTRTR0_OUTP_12                       (108U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_CMPEVENT_INTRTR0_OUTP_13                       (109U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_CMPEVENT_INTRTR0_OUTP_14                       (110U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_CMPEVENT_INTRTR0_OUTP_15                       (111U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_GPIOMUX_INTRTR0_OUTP_16                        (116U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_GPIOMUX_INTRTR0_OUTP_17                        (117U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_GPIOMUX_INTRTR0_OUTP_18                        (118U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_GPIOMUX_INTRTR0_OUTP_19                        (119U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_GPIOMUX_INTRTR0_OUTP_20                        (120U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_GPIOMUX_INTRTR0_OUTP_21                        (121U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_GPIOMUX_INTRTR0_OUTP_22                        (122U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_GPIOMUX_INTRTR0_OUTP_23                        (123U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_GPIOMUX_INTRTR0_OUTP_24                        (124U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_GPIOMUX_INTRTR0_OUTP_25                        (125U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_GPIOMUX_INTRTR0_OUTP_26                        (126U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_GPIOMUX_INTRTR0_OUTP_27                        (127U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_GPIOMUX_INTRTR0_OUTP_28                        (128U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_GPIOMUX_INTRTR0_OUTP_29                        (129U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_GPIOMUX_INTRTR0_OUTP_30                        (130U)
#define CSLR_NAVSS0_UDMASS_INTA_0_INTAGGR_LEVI_PEND_GPIOMUX_INTRTR0_OUTP_31                        (131U)

#ifdef __cplusplus
}
#endif
#endif /* CSLR_NAVSS0_UDMASS_INTA_0_INTERRUPT_MAP_H_ */

