/******************************************************************************/
/* Copyright (C) 2023 Texas Instruments Incorporated - http://www.ti.com/
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 ******************************************************************************/
#include "DSPLIB_cholesky_idat.h"
/*This file is autogenerated*/
/*Please do not edit*/

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
#include "test_data/staticRefCase3.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
#include "test_data/staticRefCase4.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
#include "test_data/staticRefCase5.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
#include "test_data/staticRefCase6.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 13))
#include "test_data/staticRefCase13.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 21))
#include "test_data/staticRefCase21.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 29))
#include "test_data/staticRefCase29.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 38))
#include "test_data/staticRefCase38.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 43))
#include "test_data/staticRefCase43.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 44))
#include "test_data/staticRefCase44.h"
#endif

static DSPLIB_cholesky_testParams_t testParams[] = {
#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
   {
    SYMMETRIC,                                        // testPatternA
    SEQUENTIAL,                                       // testPatternB
    NULL,                                             // Input matrix
    NULL,                                             // Input array B
    NULL,                                             // Output matrix Upper Triangle Mat
    NULL,                                             // Output matrix X
    DSPLIB_FLOAT32,                                   // dataType
    4,                                                // order
    1,                                                // enableTest
    DSPLIB_CALC_STRIDE (4 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),        // stride of Inp matrix
    DSPLIB_CALC_STRIDE (4 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),        // stride of Out matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    1,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
   {
    SYMMETRIC,                                        // testPatternA
    SEQUENTIAL,                                       // testPatternB
    NULL,                                             // Input matrix
    NULL,                                             // Input array B
    NULL,                                             // Output matrix Upper Triangle Mat
    NULL,                                             // Output matrix X
    DSPLIB_FLOAT32,                                   // dataType
    4,                                                // order
    0,                                                // enableTest
    DSPLIB_CALC_STRIDE (4 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),        // stride of Inp matrix
    DSPLIB_CALC_STRIDE (4 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),        // stride of Out matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    2,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
   {
    STATIC,                                           // testPatternA
    SEQUENTIAL,                                       // testPatternB
    staticRefInCase3,                                 // Input matrix
    staticRefInBCase3,                                // Input array B
    staticRefOutCase3,                                // Output matrix Upper Triangle Mat
    staticRefOutXCase3,                               // Output matrix X
    DSPLIB_FLOAT32,                                   // dataType
    6,                                                // order
    1,                                                // enableTest
    DSPLIB_CALC_STRIDE (6 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),        // stride of Inp matrix
    DSPLIB_CALC_STRIDE (6 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),        // stride of Out matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    3,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
   {
    STATIC,                                           // testPatternA
    SEQUENTIAL,                                       // testPatternB
    staticRefInCase4,                                 // Input matrix
    staticRefInBCase4,                                // Input array B
    staticRefOutCase4,                                // Output matrix Upper Triangle Mat
    staticRefOutXCase4,                               // Output matrix X
    DSPLIB_FLOAT32,                                   // dataType
    6,                                                // order
    0,                                                // enableTest
    DSPLIB_CALC_STRIDE (6 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),        // stride of Inp matrix
    DSPLIB_CALC_STRIDE (6 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),        // stride of Out matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    4,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
   {
    STATIC,                                           // testPatternA
    STATIC,                                           // testPatternB
    staticRefInCase5,                                 // Input matrix
    staticRefInBCase5,                                // Input array B
    staticRefOutCase5,                                // Output matrix Upper Triangle Mat
    staticRefOutXCase5,                               // Output matrix X
    DSPLIB_FLOAT32,                                   // dataType
    8,                                                // order
    1,                                                // enableTest
    DSPLIB_CALC_STRIDE (8 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),        // stride of Inp matrix
    DSPLIB_CALC_STRIDE (8 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),        // stride of Out matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    5,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
   {
    STATIC,                                           // testPatternA
    STATIC,                                           // testPatternB
    staticRefInCase6,                                 // Input matrix
    staticRefInBCase6,                                // Input array B
    staticRefOutCase6,                                // Output matrix Upper Triangle Mat
    staticRefOutXCase6,                               // Output matrix X
    DSPLIB_FLOAT32,                                   // dataType
    8,                                                // order
    0,                                                // enableTest
    DSPLIB_CALC_STRIDE (8 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),        // stride of Inp matrix
    DSPLIB_CALC_STRIDE (8 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),        // stride of Out matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    6,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
   {
    SYMMETRIC,                                        // testPatternA
    SEQUENTIAL,                                       // testPatternB
    NULL,                                             // Input matrix
    NULL,                                             // Input array B
    NULL,                                             // Output matrix Upper Triangle Mat
    NULL,                                             // Output matrix X
    DSPLIB_FLOAT32,                                   // dataType
    12,                                               // order
    1,                                                // enableTest
    DSPLIB_CALC_STRIDE (12 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Inp matrix
    DSPLIB_CALC_STRIDE (12 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Out matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    7,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
   {
    SYMMETRIC,                                        // testPatternA
    SEQUENTIAL,                                       // testPatternB
    NULL,                                             // Input matrix
    NULL,                                             // Input array B
    NULL,                                             // Output matrix Upper Triangle Mat
    NULL,                                             // Output matrix X
    DSPLIB_FLOAT32,                                   // dataType
    12,                                               // order
    0,                                                // enableTest
    DSPLIB_CALC_STRIDE (12 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Inp matrix
    DSPLIB_CALC_STRIDE (12 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Out matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    8,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
   {
    SYMMETRIC,                                        // testPatternA
    SEQUENTIAL,                                       // testPatternB
    NULL,                                             // Input matrix
    NULL,                                             // Input array B
    NULL,                                             // Output matrix Upper Triangle Mat
    NULL,                                             // Output matrix X
    DSPLIB_FLOAT32,                                   // dataType
    16,                                               // order
    1,                                                // enableTest
    DSPLIB_CALC_STRIDE (16 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Inp matrix
    DSPLIB_CALC_STRIDE (16 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Out matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    9,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
   {
    SYMMETRIC,                                        // testPatternA
    SEQUENTIAL,                                       // testPatternB
    NULL,                                             // Input matrix
    NULL,                                             // Input array B
    NULL,                                             // Output matrix Upper Triangle Mat
    NULL,                                             // Output matrix X
    DSPLIB_FLOAT32,                                   // dataType
    16,                                               // order
    0,                                                // enableTest
    DSPLIB_CALC_STRIDE (16 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Inp matrix
    DSPLIB_CALC_STRIDE (16 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Out matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    10,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
   {
    SYMMETRIC,                                        // testPatternA
    SEQUENTIAL,                                       // testPatternB
    NULL,                                             // Input matrix
    NULL,                                             // Input array B
    NULL,                                             // Output matrix Upper Triangle Mat
    NULL,                                             // Output matrix X
    DSPLIB_FLOAT32,                                   // dataType
    20,                                               // order
    1,                                                // enableTest
    DSPLIB_CALC_STRIDE (20 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Inp matrix
    DSPLIB_CALC_STRIDE (20 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Out matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    11,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12))
   {
    SYMMETRIC,                                        // testPatternA
    SEQUENTIAL,                                       // testPatternB
    NULL,                                             // Input matrix
    NULL,                                             // Input array B
    NULL,                                             // Output matrix Upper Triangle Mat
    NULL,                                             // Output matrix X
    DSPLIB_FLOAT32,                                   // dataType
    24,                                               // order
    1,                                                // enableTest
    DSPLIB_CALC_STRIDE (24 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Inp matrix
    DSPLIB_CALC_STRIDE (24 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Out matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    12,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 13))
   {
    STATIC,                                           // testPatternA
    STATIC,                                           // testPatternB
    staticRefInCase13,                                // Input matrix
    staticRefInBCase13,                               // Input array B
    staticRefOutCase13,                               // Output matrix Upper Triangle Mat
    staticRefOutXCase13,                              // Output matrix X
    DSPLIB_FLOAT32,                                   // dataType
    28,                                               // order
    1,                                                // enableTest
    DSPLIB_CALC_STRIDE (28 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Inp matrix
    DSPLIB_CALC_STRIDE (28 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Out matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    13,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 14))
   {
    SYMMETRIC,                                        // testPatternA
    SEQUENTIAL,                                       // testPatternB
    NULL,                                             // Input matrix
    NULL,                                             // Input array B
    NULL,                                             // Output matrix Upper Triangle Mat
    NULL,                                             // Output matrix X
    DSPLIB_FLOAT32,                                   // dataType
    32,                                               // order
    1,                                                // enableTest
    DSPLIB_CALC_STRIDE (32 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Inp matrix
    DSPLIB_CALC_STRIDE (32 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Out matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    14,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 15))
   {
    SYMMETRIC,                                        // testPatternA
    SEQUENTIAL,                                       // testPatternB
    NULL,                                             // Input matrix
    NULL,                                             // Input array B
    NULL,                                             // Output matrix Upper Triangle Mat
    NULL,                                             // Output matrix X
    DSPLIB_FLOAT32,                                   // dataType
    32,                                               // order
    0,                                                // enableTest
    DSPLIB_CALC_STRIDE (32 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Inp matrix
    DSPLIB_CALC_STRIDE (32 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Out matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    15,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 16))
   {
    SYMMETRIC,                                        // testPatternA
    SEQUENTIAL,                                       // testPatternB
    NULL,                                             // Input matrix
    NULL,                                             // Input array B
    NULL,                                             // Output matrix Upper Triangle Mat
    NULL,                                             // Output matrix X
    DSPLIB_FLOAT32,                                   // dataType
    36,                                               // order
    1,                                                // enableTest
    DSPLIB_CALC_STRIDE (36 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Inp matrix
    DSPLIB_CALC_STRIDE (36 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Out matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    16,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 17))
   {
    SYMMETRIC,                                        // testPatternA
    SEQUENTIAL,                                       // testPatternB
    NULL,                                             // Input matrix
    NULL,                                             // Input array B
    NULL,                                             // Output matrix Upper Triangle Mat
    NULL,                                             // Output matrix X
    DSPLIB_FLOAT32,                                   // dataType
    37,                                               // order
    1,                                                // enableTest
    DSPLIB_CALC_STRIDE (37 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Inp matrix
    DSPLIB_CALC_STRIDE (37 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Out matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    17,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 18))
   {
    SYMMETRIC,                                        // testPatternA
    SEQUENTIAL,                                       // testPatternB
    NULL,                                             // Input matrix
    NULL,                                             // Input array B
    NULL,                                             // Output matrix Upper Triangle Mat
    NULL,                                             // Output matrix X
    DSPLIB_FLOAT32,                                   // dataType
    44,                                               // order
    1,                                                // enableTest
    DSPLIB_CALC_STRIDE (44 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Inp matrix
    DSPLIB_CALC_STRIDE (44 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Out matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    18,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 19))
   {
    SYMMETRIC,                                        // testPatternA
    SEQUENTIAL,                                       // testPatternB
    NULL,                                             // Input matrix
    NULL,                                             // Input array B
    NULL,                                             // Output matrix Upper Triangle Mat
    NULL,                                             // Output matrix X
    DSPLIB_FLOAT32,                                   // dataType
    48,                                               // order
    1,                                                // enableTest
    DSPLIB_CALC_STRIDE (48 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Inp matrix
    DSPLIB_CALC_STRIDE (48 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Out matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    19,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 20))
   {
    SYMMETRIC,                                        // testPatternA
    SEQUENTIAL,                                       // testPatternB
    NULL,                                             // Input matrix
    NULL,                                             // Input array B
    NULL,                                             // Output matrix Upper Triangle Mat
    NULL,                                             // Output matrix X
    DSPLIB_FLOAT32,                                   // dataType
    52,                                               // order
    1,                                                // enableTest
    DSPLIB_CALC_STRIDE (52 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Inp matrix
    DSPLIB_CALC_STRIDE (52 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Out matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    20,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 21))
   {
    STATIC,                                           // testPatternA
    STATIC,                                           // testPatternB
    staticRefInCase21,                                // Input matrix
    staticRefInBCase21,                               // Input array B
    staticRefOutCase21,                               // Output matrix Upper Triangle Mat
    staticRefOutXCase21,                              // Output matrix X
    DSPLIB_FLOAT32,                                   // dataType
    59,                                               // order
    1,                                                // enableTest
    DSPLIB_CALC_STRIDE (59 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Inp matrix
    DSPLIB_CALC_STRIDE (59 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Out matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    21,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 22))
   {
    SYMMETRIC,                                        // testPatternA
    SEQUENTIAL,                                       // testPatternB
    NULL,                                             // Input matrix
    NULL,                                             // Input array B
    NULL,                                             // Output matrix Upper Triangle Mat
    NULL,                                             // Output matrix X
    DSPLIB_FLOAT32,                                   // dataType
    60,                                               // order
    1,                                                // enableTest
    DSPLIB_CALC_STRIDE (60 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Inp matrix
    DSPLIB_CALC_STRIDE (60 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Out matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    22,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 23))
   {
    SYMMETRIC,                                        // testPatternA
    SEQUENTIAL,                                       // testPatternB
    NULL,                                             // Input matrix
    NULL,                                             // Input array B
    NULL,                                             // Output matrix Upper Triangle Mat
    NULL,                                             // Output matrix X
    DSPLIB_FLOAT32,                                   // dataType
    64,                                               // order
    1,                                                // enableTest
    DSPLIB_CALC_STRIDE (64 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Inp matrix
    DSPLIB_CALC_STRIDE (64 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Out matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    23,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 24))
   {
    SYMMETRIC,                                        // testPatternA
    SEQUENTIAL,                                       // testPatternB
    NULL,                                             // Input matrix
    NULL,                                             // Input array B
    NULL,                                             // Output matrix Upper Triangle Mat
    NULL,                                             // Output matrix X
    DSPLIB_FLOAT32,                                   // dataType
    64,                                               // order
    0,                                                // enableTest
    DSPLIB_CALC_STRIDE (64 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Inp matrix
    DSPLIB_CALC_STRIDE (64 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Out matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    24,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 25))
   {
    SYMMETRIC,                                        // testPatternA
    SEQUENTIAL,                                       // testPatternB
    NULL,                                             // Input matrix
    NULL,                                             // Input array B
    NULL,                                             // Output matrix Upper Triangle Mat
    NULL,                                             // Output matrix X
    DSPLIB_FLOAT32,                                   // dataType
    68,                                               // order
    1,                                                // enableTest
    DSPLIB_CALC_STRIDE (68 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Inp matrix
    DSPLIB_CALC_STRIDE (68 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Out matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    25,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 26))
   {
    SYMMETRIC,                                        // testPatternA
    SEQUENTIAL,                                       // testPatternB
    NULL,                                             // Input matrix
    NULL,                                             // Input array B
    NULL,                                             // Output matrix Upper Triangle Mat
    NULL,                                             // Output matrix X
    DSPLIB_FLOAT32,                                   // dataType
    72,                                               // order
    1,                                                // enableTest
    DSPLIB_CALC_STRIDE (72 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Inp matrix
    DSPLIB_CALC_STRIDE (72 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Out matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    26,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 27))
   {
    SYMMETRIC,                                        // testPatternA
    SEQUENTIAL,                                       // testPatternB
    NULL,                                             // Input matrix
    NULL,                                             // Input array B
    NULL,                                             // Output matrix Upper Triangle Mat
    NULL,                                             // Output matrix X
    DSPLIB_FLOAT32,                                   // dataType
    76,                                               // order
    1,                                                // enableTest
    DSPLIB_CALC_STRIDE (76 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Inp matrix
    DSPLIB_CALC_STRIDE (76 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Out matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    27,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 28))
   {
    SYMMETRIC,                                        // testPatternA
    SEQUENTIAL,                                       // testPatternB
    NULL,                                             // Input matrix
    NULL,                                             // Input array B
    NULL,                                             // Output matrix Upper Triangle Mat
    NULL,                                             // Output matrix X
    DSPLIB_FLOAT32,                                   // dataType
    80,                                               // order
    1,                                                // enableTest
    DSPLIB_CALC_STRIDE (80 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Inp matrix
    DSPLIB_CALC_STRIDE (80 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Out matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    28,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 29))
   {
    STATIC,                                           // testPatternA
    STATIC,                                           // testPatternB
    staticRefInCase29,                                // Input matrix
    staticRefInBCase29,                               // Input array B
    staticRefOutCase29,                               // Output matrix Upper Triangle Mat
    staticRefOutXCase29,                              // Output matrix X
    DSPLIB_FLOAT32,                                   // dataType
    84,                                               // order
    1,                                                // enableTest
    DSPLIB_CALC_STRIDE (84 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Inp matrix
    DSPLIB_CALC_STRIDE (84 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Out matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    29,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 30))
   {
    SYMMETRIC,                                        // testPatternA
    SEQUENTIAL,                                       // testPatternB
    NULL,                                             // Input matrix
    NULL,                                             // Input array B
    NULL,                                             // Output matrix Upper Triangle Mat
    NULL,                                             // Output matrix X
    DSPLIB_FLOAT32,                                   // dataType
    88,                                               // order
    1,                                                // enableTest
    DSPLIB_CALC_STRIDE (88 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Inp matrix
    DSPLIB_CALC_STRIDE (88 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Out matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    30,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 31))
   {
    SYMMETRIC,                                        // testPatternA
    SEQUENTIAL,                                       // testPatternB
    NULL,                                             // Input matrix
    NULL,                                             // Input array B
    NULL,                                             // Output matrix Upper Triangle Mat
    NULL,                                             // Output matrix X
    DSPLIB_FLOAT32,                                   // dataType
    88,                                               // order
    0,                                                // enableTest
    DSPLIB_CALC_STRIDE (88 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Inp matrix
    DSPLIB_CALC_STRIDE (88 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Out matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    31,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 32))
   {
    SYMMETRIC,                                        // testPatternA
    SEQUENTIAL,                                       // testPatternB
    NULL,                                             // Input matrix
    NULL,                                             // Input array B
    NULL,                                             // Output matrix Upper Triangle Mat
    NULL,                                             // Output matrix X
    DSPLIB_FLOAT32,                                   // dataType
    92,                                               // order
    1,                                                // enableTest
    DSPLIB_CALC_STRIDE (92 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Inp matrix
    DSPLIB_CALC_STRIDE (92 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Out matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    32,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 33))
   {
    SYMMETRIC,                                        // testPatternA
    SEQUENTIAL,                                       // testPatternB
    NULL,                                             // Input matrix
    NULL,                                             // Input array B
    NULL,                                             // Output matrix Upper Triangle Mat
    NULL,                                             // Output matrix X
    DSPLIB_FLOAT32,                                   // dataType
    92,                                               // order
    0,                                                // enableTest
    DSPLIB_CALC_STRIDE (92 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Inp matrix
    DSPLIB_CALC_STRIDE (92 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Out matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    33,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 34))
   {
    SYMMETRIC,                                        // testPatternA
    SEQUENTIAL,                                       // testPatternB
    NULL,                                             // Input matrix
    NULL,                                             // Input array B
    NULL,                                             // Output matrix Upper Triangle Mat
    NULL,                                             // Output matrix X
    DSPLIB_FLOAT32,                                   // dataType
    96,                                               // order
    1,                                                // enableTest
    DSPLIB_CALC_STRIDE (96 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Inp matrix
    DSPLIB_CALC_STRIDE (96 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),       // stride of Out matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    34,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 35))
   {
    SYMMETRIC,                                        // testPatternA
    SEQUENTIAL,                                       // testPatternB
    NULL,                                             // Input matrix
    NULL,                                             // Input array B
    NULL,                                             // Output matrix Upper Triangle Mat
    NULL,                                             // Output matrix X
    DSPLIB_FLOAT32,                                   // dataType
    101,                                              // order
    1,                                                // enableTest
    DSPLIB_CALC_STRIDE (101 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of Inp matrix
    DSPLIB_CALC_STRIDE (101 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of Out matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    35,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 36))
   {
    SYMMETRIC,                                        // testPatternA
    SEQUENTIAL,                                       // testPatternB
    NULL,                                             // Input matrix
    NULL,                                             // Input array B
    NULL,                                             // Output matrix Upper Triangle Mat
    NULL,                                             // Output matrix X
    DSPLIB_FLOAT32,                                   // dataType
    104,                                              // order
    1,                                                // enableTest
    DSPLIB_CALC_STRIDE (104 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of Inp matrix
    DSPLIB_CALC_STRIDE (104 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of Out matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    36,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 37))
   {
    SYMMETRIC,                                        // testPatternA
    SEQUENTIAL,                                       // testPatternB
    NULL,                                             // Input matrix
    NULL,                                             // Input array B
    NULL,                                             // Output matrix Upper Triangle Mat
    NULL,                                             // Output matrix X
    DSPLIB_FLOAT32,                                   // dataType
    108,                                              // order
    1,                                                // enableTest
    DSPLIB_CALC_STRIDE (108 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of Inp matrix
    DSPLIB_CALC_STRIDE (108 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of Out matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    37,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 38))
   {
    STATIC,                                           // testPatternA
    STATIC,                                           // testPatternB
    staticRefInCase38,                                // Input matrix
    staticRefInBCase38,                               // Input array B
    staticRefOutCase38,                               // Output matrix Upper Triangle Mat
    staticRefOutXCase38,                              // Output matrix X
    DSPLIB_FLOAT32,                                   // dataType
    112,                                              // order
    1,                                                // enableTest
    DSPLIB_CALC_STRIDE (112 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of Inp matrix
    DSPLIB_CALC_STRIDE (112 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of Out matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    38,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 39))
   {
    SYMMETRIC,                                        // testPatternA
    SEQUENTIAL,                                       // testPatternB
    NULL,                                             // Input matrix
    NULL,                                             // Input array B
    NULL,                                             // Output matrix Upper Triangle Mat
    NULL,                                             // Output matrix X
    DSPLIB_FLOAT32,                                   // dataType
    116,                                              // order
    1,                                                // enableTest
    DSPLIB_CALC_STRIDE (116 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of Inp matrix
    DSPLIB_CALC_STRIDE (116 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of Out matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    39,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 40))
   {
    SYMMETRIC,                                        // testPatternA
    SEQUENTIAL,                                       // testPatternB
    NULL,                                             // Input matrix
    NULL,                                             // Input array B
    NULL,                                             // Output matrix Upper Triangle Mat
    NULL,                                             // Output matrix X
    DSPLIB_FLOAT32,                                   // dataType
    120,                                              // order
    1,                                                // enableTest
    DSPLIB_CALC_STRIDE (120 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of Inp matrix
    DSPLIB_CALC_STRIDE (120 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of Out matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    40,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 41))
   {
    SYMMETRIC,                                        // testPatternA
    SEQUENTIAL,                                       // testPatternB
    NULL,                                             // Input matrix
    NULL,                                             // Input array B
    NULL,                                             // Output matrix Upper Triangle Mat
    NULL,                                             // Output matrix X
    DSPLIB_FLOAT32,                                   // dataType
    120,                                              // order
    0,                                                // enableTest
    DSPLIB_CALC_STRIDE (120 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of Inp matrix
    DSPLIB_CALC_STRIDE (120 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of Out matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    41,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 42))
   {
    SYMMETRIC,                                        // testPatternA
    SEQUENTIAL,                                       // testPatternB
    NULL,                                             // Input matrix
    NULL,                                             // Input array B
    NULL,                                             // Output matrix Upper Triangle Mat
    NULL,                                             // Output matrix X
    DSPLIB_FLOAT32,                                   // dataType
    124,                                              // order
    1,                                                // enableTest
    DSPLIB_CALC_STRIDE (124 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of Inp matrix
    DSPLIB_CALC_STRIDE (124 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of Out matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    42,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 43))
   {
    STATIC,                                           // testPatternA
    STATIC,                                           // testPatternB
    staticRefInCase43,                                // Input matrix
    staticRefInBCase43,                               // Input array B
    staticRefOutCase43,                               // Output matrix Upper Triangle Mat
    staticRefOutXCase43,                              // Output matrix X
    DSPLIB_FLOAT32,                                   // dataType
    128,                                              // order
    1,                                                // enableTest
    DSPLIB_CALC_STRIDE (128 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of Inp matrix
    DSPLIB_CALC_STRIDE (128 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of Out matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    43,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 44))
   {
    STATIC,                                           // testPatternA
    STATIC,                                           // testPatternB
    staticRefInCase44,                                // Input matrix
    staticRefInBCase44,                               // Input array B
    staticRefOutCase44,                               // Output matrix Upper Triangle Mat
    staticRefOutXCase44,                              // Output matrix X
    DSPLIB_FLOAT32,                                   // dataType
    128,                                              // order
    0,                                                // enableTest
    DSPLIB_CALC_STRIDE (128 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of Inp matrix
    DSPLIB_CALC_STRIDE (128 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of Out matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    44,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 45))
   {
    SYMMETRIC,                                        // testPatternA
    SEQUENTIAL,                                       // testPatternB
    NULL,                                             // Input matrix
    NULL,                                             // Input array B
    NULL,                                             // Output matrix Upper Triangle Mat
    NULL,                                             // Output matrix X
    DSPLIB_FLOAT32,                                   // dataType
    132,                                              // order
    1,                                                // enableTest
    DSPLIB_CALC_STRIDE (132 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of Inp matrix
    DSPLIB_CALC_STRIDE (132 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of Out matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    45,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 46))
   {
    SYMMETRIC,                                        // testPatternA
    SEQUENTIAL,                                       // testPatternB
    NULL,                                             // Input matrix
    NULL,                                             // Input array B
    NULL,                                             // Output matrix Upper Triangle Mat
    NULL,                                             // Output matrix X
    DSPLIB_FLOAT32,                                   // dataType
    136,                                              // order
    1,                                                // enableTest
    DSPLIB_CALC_STRIDE (136 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of Inp matrix
    DSPLIB_CALC_STRIDE (136 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of Out matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    46,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 47))
   {
    SYMMETRIC,                                        // testPatternA
    SEQUENTIAL,                                       // testPatternB
    NULL,                                             // Input matrix
    NULL,                                             // Input array B
    NULL,                                             // Output matrix Upper Triangle Mat
    NULL,                                             // Output matrix X
    DSPLIB_FLOAT32,                                   // dataType
    140,                                              // order
    1,                                                // enableTest
    DSPLIB_CALC_STRIDE (140 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of Inp matrix
    DSPLIB_CALC_STRIDE (140 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of Out matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    47,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 48))
   {
    SYMMETRIC,                                        // testPatternA
    SEQUENTIAL,                                       // testPatternB
    NULL,                                             // Input matrix
    NULL,                                             // Input array B
    NULL,                                             // Output matrix Upper Triangle Mat
    NULL,                                             // Output matrix X
    DSPLIB_FLOAT32,                                   // dataType
    256,                                              // order
    1,                                                // enableTest
    DSPLIB_CALC_STRIDE (256 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of Inp matrix
    DSPLIB_CALC_STRIDE (256 * sizeof (float), DSPLIB_ALIGN_SHIFT_64BYTES),      // stride of Out matrix
    0,                                                // shift
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    48,                                               // test ID
    },
#endif

};

/*
 *  Sends the test parameter structure and number of tests
 */
void
DSPLIB_cholesky_getTestParams (DSPLIB_cholesky_testParams_t ** params, int32_t * numTests)
{
   *params = testParams;
   *numTests = sizeof (testParams) / sizeof (DSPLIB_cholesky_testParams_t);
}
