/******************************************************************************/
/* Copyright (C) 2023 Texas Instruments Incorporated - http://www.ti.com/
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 ******************************************************************************/
#include "DSPLIB_add_idat.h"
/*This file is autogenerated*/
/*Please do not edit*/

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
#include "test_data/staticRefCase1.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
#include "test_data/staticRefCase2.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
#include "test_data/staticRefCase3.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
#include "test_data/staticRefCase4.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
#include "test_data/staticRefCase5.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
#include "test_data/staticRefCase6.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
#include "test_data/staticRefCase7.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
#include "test_data/staticRefCase8.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
#include "test_data/staticRefCase9.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
#include "test_data/staticRefCase10.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
#include "test_data/staticRefCase11.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12))
#include "test_data/staticRefCase12.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 13))
#include "test_data/staticRefCase13.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 14))
#include "test_data/staticRefCase14.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 15))
#include "test_data/staticRefCase15.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 16))
#include "test_data/staticRefCase16.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 17))
#include "test_data/staticRefCase17.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 18))
#include "test_data/staticRefCase18.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 19))
#include "test_data/staticRefCase19.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 20))
#include "test_data/staticRefCase20.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 21))
#include "test_data/staticRefCase21.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 22))
#include "test_data/staticRefCase22.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 23))
#include "test_data/staticRefCase23.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 24))
#include "test_data/staticRefCase24.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 25))
#include "test_data/staticRefCase25.h"
#endif

static DSPLIB_add_testParams_t testParams[] = {
#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case1,                                // Input vector 0
    staticRefIn1Case1,                                // Input vector 1
    staticRefOutCase1,                                // Output vector
    DSPLIB_FLOAT32,                                   // precision
    256,                                              // length of vector
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    1,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case2,                                // Input vector 0
    staticRefIn1Case2,                                // Input vector 1
    staticRefOutCase2,                                // Output vector
    DSPLIB_FLOAT32,                                   // precision
    512,                                              // length of vector
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    2,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case3,                                // Input vector 0
    staticRefIn1Case3,                                // Input vector 1
    staticRefOutCase3,                                // Output vector
    DSPLIB_FLOAT32,                                   // precision
    1024,                                             // length of vector
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    3,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case4,                                // Input vector 0
    staticRefIn1Case4,                                // Input vector 1
    staticRefOutCase4,                                // Output vector
    DSPLIB_FLOAT32,                                   // precision
    2048,                                             // length of vector
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    4,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case5,                                // Input vector 0
    staticRefIn1Case5,                                // Input vector 1
    staticRefOutCase5,                                // Output vector
    DSPLIB_FLOAT32,                                   // precision
    10240,                                            // length of vector
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    5,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case6,                                // Input vector 0
    staticRefIn1Case6,                                // Input vector 1
    staticRefOutCase6,                                // Output vector
    DSPLIB_FLOAT64,                                   // precision
    256,                                              // length of vector
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    6,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case7,                                // Input vector 0
    staticRefIn1Case7,                                // Input vector 1
    staticRefOutCase7,                                // Output vector
    DSPLIB_FLOAT64,                                   // precision
    512,                                              // length of vector
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    7,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case8,                                // Input vector 0
    staticRefIn1Case8,                                // Input vector 1
    staticRefOutCase8,                                // Output vector
    DSPLIB_FLOAT64,                                   // precision
    1024,                                             // length of vector
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    8,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case9,                                // Input vector 0
    staticRefIn1Case9,                                // Input vector 1
    staticRefOutCase9,                                // Output vector
    DSPLIB_FLOAT64,                                   // precision
    2048,                                             // length of vector
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    9,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case10,                               // Input vector 0
    staticRefIn1Case10,                               // Input vector 1
    staticRefOutCase10,                               // Output vector
    DSPLIB_FLOAT64,                                   // precision
    10240,                                            // length of vector
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    10,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case11,                               // Input vector 0
    staticRefIn1Case11,                               // Input vector 1
    staticRefOutCase11,                               // Output vector
    DSPLIB_INT32,                                     // precision
    256,                                              // length of vector
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    11,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case12,                               // Input vector 0
    staticRefIn1Case12,                               // Input vector 1
    staticRefOutCase12,                               // Output vector
    DSPLIB_INT32,                                     // precision
    512,                                              // length of vector
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    12,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 13))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case13,                               // Input vector 0
    staticRefIn1Case13,                               // Input vector 1
    staticRefOutCase13,                               // Output vector
    DSPLIB_INT32,                                     // precision
    1024,                                             // length of vector
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    13,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 14))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case14,                               // Input vector 0
    staticRefIn1Case14,                               // Input vector 1
    staticRefOutCase14,                               // Output vector
    DSPLIB_UINT32,                                    // precision
    2048,                                             // length of vector
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    14,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 15))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case15,                               // Input vector 0
    staticRefIn1Case15,                               // Input vector 1
    staticRefOutCase15,                               // Output vector
    DSPLIB_UINT32,                                    // precision
    10240,                                            // length of vector
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    15,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 16))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case16,                               // Input vector 0
    staticRefIn1Case16,                               // Input vector 1
    staticRefOutCase16,                               // Output vector
    DSPLIB_INT16,                                     // precision
    256,                                              // length of vector
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    16,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 17))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case17,                               // Input vector 0
    staticRefIn1Case17,                               // Input vector 1
    staticRefOutCase17,                               // Output vector
    DSPLIB_INT16,                                     // precision
    512,                                              // length of vector
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    17,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 18))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case18,                               // Input vector 0
    staticRefIn1Case18,                               // Input vector 1
    staticRefOutCase18,                               // Output vector
    DSPLIB_INT16,                                     // precision
    1024,                                             // length of vector
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    18,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 19))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case19,                               // Input vector 0
    staticRefIn1Case19,                               // Input vector 1
    staticRefOutCase19,                               // Output vector
    DSPLIB_UINT16,                                    // precision
    2048,                                             // length of vector
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    19,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 20))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case20,                               // Input vector 0
    staticRefIn1Case20,                               // Input vector 1
    staticRefOutCase20,                               // Output vector
    DSPLIB_UINT16,                                    // precision
    10240,                                            // length of vector
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    20,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 21))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case21,                               // Input vector 0
    staticRefIn1Case21,                               // Input vector 1
    staticRefOutCase21,                               // Output vector
    DSPLIB_INT8,                                      // precision
    256,                                              // length of vector
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    21,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 22))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case22,                               // Input vector 0
    staticRefIn1Case22,                               // Input vector 1
    staticRefOutCase22,                               // Output vector
    DSPLIB_INT8,                                      // precision
    512,                                              // length of vector
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    22,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 23))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case23,                               // Input vector 0
    staticRefIn1Case23,                               // Input vector 1
    staticRefOutCase23,                               // Output vector
    DSPLIB_INT8,                                      // precision
    1024,                                             // length of vector
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    23,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 24))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case24,                               // Input vector 0
    staticRefIn1Case24,                               // Input vector 1
    staticRefOutCase24,                               // Output vector
    DSPLIB_UINT8,                                     // precision
    2048,                                             // length of vector
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    24,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 25))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case25,                               // Input vector 0
    staticRefIn1Case25,                               // Input vector 1
    staticRefOutCase25,                               // Output vector
    DSPLIB_UINT8,                                     // precision
    10240,                                            // length of vector
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    25,                                               // test ID
    },
#endif

};

/*
 *  Sends the test parameter structure and number of tests
 */
void
DSPLIB_add_getTestParams (DSPLIB_add_testParams_t ** params, int32_t * numTests)
{
   *params = testParams;
   *numTests = sizeof (testParams) / sizeof (DSPLIB_add_testParams_t);
}
