from __future__ import print_function
from subprocess import call
from sys import platform

import sys
import numpy as np
import csv

sys.path.append("../common")
import VXLIB_utils
import file_io


def gen_testCaseParams(testParamsFile, currPrm):
    """Generate and write test case parameters to idat file

    Args:
        param1 (file object): Input file object to idat.c file
        param2 (dict object): Dict object with test case parameter

    """

    testId = currPrm["ID"]
    dTypeIn0 = currPrm["dTypeIn0"]
    dTypeIn1 = currPrm["dTypeIn1"]
    dTypeOut = currPrm["dTypeOut"]
    width = currPrm["width"]
    height = currPrm["height"]
    strideIn = currPrm["strideIn"]
    strideMask = currPrm["strideMask"]
    strideOut = currPrm["strideOut"]
    kernelType = currPrm["kernelType"]
    M = currPrm["M"]
    N = currPrm["N"]
    testType = currPrm["testType"]
    demoCase = currPrm["demoCase"]
    numReps = currPrm["numReps"]
    outputDataLocation = currPrm["outputDataLocation"]

    if testType == "STATIC":
        in0 = "staticRefIn0Case" + testId
        in1 = "staticRefIn1Case" + testId
        out = "staticRefOutCase" + testId
    else:
        in0 = "NULL"
        in1 = "NULL"
        out = "NULL"

    if demoCase == "true":
        testParamsFile.write(
            "#if (defined(ALL_TEST_CASES) || (TEST_CASE == %d) || defined(DEMO_CASE))\n"
            % (int(testId))
        )
    else:
        testParamsFile.write(
            "#if (defined(ALL_TEST_CASES) || (TEST_CASE == %d))\n" % (int(testId))
        )

    idatFile.write("{\n")
    idatFile.write("%s, // Test pattern \n" % ((testType)))
    idatFile.write("%s, // Input vector 0 \n" % ((in0)))
    idatFile.write(
        "%s, // data type in0 \n" % (VXLIB_utils.resolveVXLIBDType(dTypeIn0))
    )
    idatFile.write("%s, // Input MASK \n" % ((in1)))
    idatFile.write(
        "%s, // data type MASK \n" % (VXLIB_utils.resolveVXLIBDType(dTypeIn1))
    )
    idatFile.write("%s, // Output vector \n" % ((out)))
    idatFile.write(
        "%s, // data type out \n" % (VXLIB_utils.resolveVXLIBDType(dTypeOut))
    )

    idatFile.write("%d, // width of image \n" % ((width)))
    idatFile.write("%d, // height of image \n" % ((height)))
    idatFile.write("%d, // height of MASK \n" % ((M)))
    idatFile.write("%d, // width of MASK \n" % ((N)))
    idatFile.write("%d* sizeof(%s), // strideIn \n" % ((strideIn), (dTypeIn0)))
    idatFile.write("%d* sizeof(%s), // strideMask \n" % ((strideMask), (dTypeIn1)))
    idatFile.write("%d* sizeof(%s), // strideOut \n" % ((strideOut), (dTypeOut)))
    idatFile.write("%s, // kernelType \n" % ((kernelType)))
    idatFile.write("%s, // Output data location \n" % (outputDataLocation))
    idatFile.write("%d, // number of reps. \n" % (int(numReps)))
    idatFile.write("%d, // test ID\n" % int(testId))
    idatFile.write("},\n")
    idatFile.write("#endif")
    idatFile.write("\n\n")


def gen_idat_file(idatFile, testCases):
    """Generate the idat file

    Args:
        param1 (file object): Input file object to idat.c file
        param2 (dict object): Dict object with test case parameter

    """

    fIn = open("../common/ti_lice_header_idat.txt", "r")
    lines = fIn.readlines()
    fIn.close()
    idatFile.writelines(lines)
    includeString = '#include "VXLIB_median_idat.h"'
    idatFile.writelines(includeString)
    idatFile.write("\n")
    idatFile.write("/*This file is autogenerated*/\n")
    idatFile.write("/*Please do not edit*/\n")
    idatFile.write("\n\n")
    # generate ifdefs for header files
    for testCase in testCases:
        if testCase["testType"] == "STATIC":
            VXLIB_utils.gen_ifdefs(idatFile, testCase)

    # generate parameters for test cases
    idatFile.write("static VXLIB_median_testParams_t testParams[] =  ")
    idatFile.write("{\n")

    for testCase in testCases:
        gen_testCaseParams(idatFile, testCase)

    idatFile.write("};\n\n")
    fIn = open("test_param_function.txt", "r")
    lines = fIn.readlines()

    idatFile.writelines(lines)


def process_test_case(testCase):
    """Convert str to int for necessary parameters

    Args:
        Param1(:obj: dict) : Dictionary object with test case parameters

    Returns:
        Obj: Dictionary object with necessary parameters converted to int

    """

    # print(testCase.keys())
    testCase["testId"] = int(testCase["ID"])
    testCase["width"] = int(testCase["width"])
    testCase["height"] = int(testCase["height"])
    testCase["M"] = int(testCase["M"])
    testCase["N"] = int(testCase["N"])
    testCase["strideIn"] = int(testCase["strideIn"])
    testCase["strideMask"] = int(testCase["strideMask"])
    testCase["strideOut"] = int(testCase["strideOut"])
    testCase["kernelType"] = int(testCase["kernelType"])

    return testCase


def gen_test_case_header_file(testCase):
    """Generate test case and write out input, filter, and output tensor
    into a header file usable in C/C++ code.

    Args:
        param1 (:obj: dict): A dict object with all the test case
        parameters

    Returns:
        [int int]: Minimum and maximum value in output feature tensor

    """

    ##############################
    # Get test parameter of case #
    ##############################

    testId = testCase["ID"]
    width = testCase["width"]
    height = testCase["height"]
    M = testCase["M"]
    N = testCase["N"]
    dTypeIn0 = testCase["dTypeIn0"]
    dTypeIn1 = testCase["dTypeIn1"]
    dTypeOut = testCase["dTypeOut"]
    kernelType = testCase["kernelType"]

    [minValIn0, maxValIn0] = VXLIB_utils.resolveDTypeLimits(dTypeIn0)
    [minValIn1, maxValIn1] = VXLIB_utils.resolveDTypeLimits(dTypeIn1)
    [minValOut, maxValOut] = VXLIB_utils.resolveDTypeLimits(dTypeOut)

    in0 = np.random.uniform(low=minValIn0, high=maxValIn0, size=(height, width)).astype(
        np.int64
    )
    in1 = np.random.uniform(low=minValIn1, high=maxValIn1, size=(M, N)).astype(
        np.int64
    )
    if (dTypeIn1 == "uint8_t"):
        maskValTrue = 255
        maskValFalse = 0
    elif(dTypeIn1 == "int8_t"):
        maskValTrue = -1
        maskValFalse = 0
    elif (dTypeIn1 == "uint16_t"):
        maskValTrue = 65535
        maskValFalse = 0
    elif (dTypeIn1 == "int16_t"):
        maskValTrue = -1
        maskValFalse = 0
         
    for i in range(M):
        for j in range(N):
            maskCondition = np.random.randint(2)
            if (maskCondition == 1):
                in1[i][j] = maskValTrue
            else:
                in1[i][j] = maskValFalse
    in1[0][0] = maskValTrue
    out = np.zeros([height, width])
    if (kernelType == 0):
        for i in range(1, height - (M - 1) + 1):
            for j in range(1, width - (N - 1) + 1):
              temp = [in0[i-1,j-1],
                      in0[i-1,j],
                      in0[i-1,j+1],
                      in0[i,j-1],
                      in0[i,j],
                      in0[i,j+1],
                      in0[i+1,j-1],
                      in0[i+1,j],
                      in0[i+1,j+1]
                      ]
              temp = sorted(temp)
              out[i-1, j-1] = temp[4]
    else:
        heightOut = height - M + 1
        widthOut = width - N + 1
        for y in range(heightOut):
            for x in range(widthOut):
                cnt = 0
                # Extract M X N window into array
                inWindow = [] 
                for j in range(M):
                    for k in range(N):
                        if (in1[j][k] == maskValTrue):
                            # inWindow[cnt] = in0[y+j][x+k]
                            inWindow.append(in0[y + j][x + k])
                            cnt = cnt + 1
                
                # print(inWindow)
                inWindow = sorted(inWindow, reverse=True)
                # print(inWindow)
                out[y][x] = inWindow[int(cnt / 2)]
                    
        
    if (dTypeIn0 == "uint8_t"):
      out = out.astype(np.uint8)
    elif (dTypeIn0 == "int8_t"):
      out = out.astype(np.int8)
    elif (dTypeIn0 == "uint16_t"):
      out = out.astype(np.uint16)
    elif (dTypeIn0 == "int16_t"):
      out = out.astype(np.int16)

    # print(out)


    headerFileName = "staticRefCase" + str(testId) + ".h"
    file_io.write_header_file(in0, in1, out, testCase, headerFileName)

    return [np.min(out), np.max(out)]


# CSV file with paratmeters for all test cases
testCasesCsvFile = "test_cases_list.csv"
testIdList = []  # list of test IDs that we want to generate test data
testIdList += range(1, 200)
# testIdList = [31]

myArgs = VXLIB_utils.getCmdLineArgs()


def gen_test_case(testCase):
    if testCase["testType"] == "STATIC":
        [minY, maxY] = gen_test_case_header_file(testCase)
        print(
            "Test case generation completed for test ID",
            testCase["ID"],
            "w/ min:",
            minY,
            "and max",
            maxY,
        )
    else:
        print(
            "Skipping test case generation for test ID",
            testCase["ID"],
            "as tesType is RANDOM",
        )


#############################################################################
# Open CSV file with test cases and generate header file with test data for #
# test cases of interest; based on testIdList                               #
#############################################################################

with open(testCasesCsvFile, encoding="utf-8-sig") as csv_file:
    testCaseReader = csv.DictReader(csv_file)
    testCases = list(testCaseReader)

    for testCase in testCases:
        testCase = process_test_case(testCase)

    for testCase in testCases:
        if myArgs.allCases == True:
            gen_test_case(testCase)
        elif int(testCase["ID"]) in testIdList:
            gen_test_case(testCase)

idatFileName = "../../VXLIB_median/VXLIB_median_idat.c"


##########################################################################
# Generate idat.cpp file by parsing all the test cases in the CSV file # #
##########################################################################


with open(idatFileName, "w") as idatFile:
    gen_idat_file(idatFile, testCases)


if platform == "linux" or platform == "linux2":
    call(["clang-format", "-style=file", "-i", idatFileName])
    call(["indent", "-nut", "-i3", "-c55", "-l200", idatFileName])
    call(["rm", idatFileName + "~"])  # remove backup file


print("Idat file generation completed")
