/******************************************************************************/
/* Copyright (C) 2023 Texas Instruments Incorporated - http://www.ti.com/
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 ******************************************************************************/
#include "MATHLIB_atan2_testParams.h"
/*This file is autogenerated*/
/*Please do not edit*/


#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1) || defined(DEMO_CASE))
#include "test_data/staticRefCase1.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2) || defined(DEMO_CASE))
#include "test_data/staticRefCase2.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3) || defined(DEMO_CASE))
#include "test_data/staticRefCase3.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4) || defined(DEMO_CASE))
#include "test_data/staticRefCase4.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
#include "test_data/staticRefCase5.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
#include "test_data/staticRefCase6.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
#include "test_data/staticRefCase7.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
#include "test_data/staticRefCase8.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
#include "test_data/staticRefCase9.h"
#endif

static MATHLIB_atan2_testParams_t testParams[] = {
#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1) || defined(DEMO_CASE))
   {
    staticRefIn0Case1,                                // Input vector 0 
    staticRefIn1Case1,                                // Input vector 1 
    staticRefOutCase1,                                // Output vector 
    256,                                              // length of vector 
    MATHLIB_FLOAT32,                                  // precision 
    1,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2) || defined(DEMO_CASE))
   {
    staticRefIn0Case2,                                // Input vector 0 
    staticRefIn1Case2,                                // Input vector 1 
    staticRefOutCase2,                                // Output vector 
    512,                                              // length of vector 
    MATHLIB_FLOAT32,                                  // precision 
    2,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3) || defined(DEMO_CASE))
   {
    staticRefIn0Case3,                                // Input vector 0 
    staticRefIn1Case3,                                // Input vector 1 
    staticRefOutCase3,                                // Output vector 
    1024,                                             // length of vector 
    MATHLIB_FLOAT32,                                  // precision 
    3,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4) || defined(DEMO_CASE))
   {
    staticRefIn0Case4,                                // Input vector 0 
    staticRefIn1Case4,                                // Input vector 1 
    staticRefOutCase4,                                // Output vector 
    2048,                                             // length of vector 
    MATHLIB_FLOAT32,                                  // precision 
    4,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
   {
    staticRefIn0Case5,                                // Input vector 0 
    staticRefIn1Case5,                                // Input vector 1 
    staticRefOutCase5,                                // Output vector 
    10240,                                            // length of vector 
    MATHLIB_FLOAT32,                                  // precision 
    5,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
   {
    staticRefIn0Case6,                                // Input vector 0 
    staticRefIn1Case6,                                // Input vector 1 
    staticRefOutCase6,                                // Output vector 
    550,                                              // length of vector 
    MATHLIB_FLOAT32,                                  // precision 
    6,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
   {
    staticRefIn0Case7,                                // Input vector 0 
    staticRefIn1Case7,                                // Input vector 1 
    staticRefOutCase7,                                // Output vector 
    1090,                                             // length of vector 
    MATHLIB_FLOAT32,                                  // precision 
    7,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
   {
    staticRefIn0Case8,                                // Input vector 0 
    staticRefIn1Case8,                                // Input vector 1 
    staticRefOutCase8,                                // Output vector 
    2500,                                             // length of vector 
    MATHLIB_FLOAT32,                                  // precision 
    8,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
   {
    staticRefIn0Case9,                                // Input vector 0 
    staticRefIn1Case9,                                // Input vector 1 
    staticRefOutCase9,                                // Output vector 
    15,                                               // length of vector 
    MATHLIB_FLOAT32,                                  // precision 
    9,                                                // test ID
    },
#endif

};

/*
 *  Sends the test parameter structure and number of tests
 */
void
MATHLIB_atan2_getTestParams (MATHLIB_atan2_testParams_t ** params, int32_t * numTests)
{
   *params = testParams;
   *numTests = sizeof (testParams) / sizeof (MATHLIB_atan2_testParams_t);
}
