/******************************************************************************/
/* Copyright (C) 2023 Texas Instruments Incorporated - http://www.ti.com/
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 ******************************************************************************/

#include "VXLIB_normL1_idat.h"
/*This file is autogenerated*/
/*Please do not edit*/

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
#include "test_data/staticRefCase1.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
#include "test_data/staticRefCase2.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
#include "test_data/staticRefCase3.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
#include "test_data/staticRefCase4.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
#include "test_data/staticRefCase5.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
#include "test_data/staticRefCase6.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
#include "test_data/staticRefCase7.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
#include "test_data/staticRefCase8.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
#include "test_data/staticRefCase9.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
#include "test_data/staticRefCase10.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
#include "test_data/staticRefCase11.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12))
#include "test_data/staticRefCase12.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 13))
#include "test_data/staticRefCase13.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 14))
#include "test_data/staticRefCase14.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 15))
#include "test_data/staticRefCase15.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 16))
#include "test_data/staticRefCase16.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 17))
#include "test_data/staticRefCase17.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 18))
#include "test_data/staticRefCase18.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 19))
#include "test_data/staticRefCase19.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 20))
#include "test_data/staticRefCase20.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 21))
#include "test_data/staticRefCase21.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 22))
#include "test_data/staticRefCase22.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 23))
#include "test_data/staticRefCase23.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 24))
#include "test_data/staticRefCase24.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 25))
#include "test_data/staticRefCase25.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 26))
#include "test_data/staticRefCase26.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 27))
#include "test_data/staticRefCase27.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 28))
#include "test_data/staticRefCase28.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 29))
#include "test_data/staticRefCase29.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 30))
#include "test_data/staticRefCase30.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 31))
#include "test_data/staticRefCase31.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 32))
#include "test_data/staticRefCase32.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 33))
#include "test_data/staticRefCase33.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 34))
#include "test_data/staticRefCase34.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 35))
#include "test_data/staticRefCase35.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 36))
#include "test_data/staticRefCase36.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 37))
#include "test_data/staticRefCase37.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 38))
#include "test_data/staticRefCase38.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 39))
#include "test_data/staticRefCase39.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 40))
#include "test_data/staticRefCase40.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 41))
#include "test_data/staticRefCase41.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 42))
#include "test_data/staticRefCase42.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 43))
#include "test_data/staticRefCase43.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 44))
#include "test_data/staticRefCase44.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 45))
#include "test_data/staticRefCase45.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 46))
#include "test_data/staticRefCase46.h"
#endif

static VXLIB_normL1_testParams_t testParams[] = {
#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case1,                                // Input image 0
    staticRefIn1Case1,                                // Input image 1
    staticRefOutCase1,                                // Output image
    VXLIB_INT8,                                       // Input data type
    VXLIB_UINT8,                                      // Output data type
    3,                                                // width of image
    3,                                                // height of image
    3 * sizeof (int8_t),                              // stride of image 0
    3 * sizeof (int8_t),                              // stride of image 1
    3 * sizeof (uint8_t),                             // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    1,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case2,                                // Input image 0
    staticRefIn1Case2,                                // Input image 1
    staticRefOutCase2,                                // Output image
    VXLIB_INT8,                                       // Input data type
    VXLIB_UINT8,                                      // Output data type
    8,                                                // width of image
    8,                                                // height of image
    8 * sizeof (int8_t),                              // stride of image 0
    8 * sizeof (int8_t),                              // stride of image 1
    8 * sizeof (uint8_t),                             // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    2,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case3,                                // Input image 0
    staticRefIn1Case3,                                // Input image 1
    staticRefOutCase3,                                // Output image
    VXLIB_INT8,                                       // Input data type
    VXLIB_UINT8,                                      // Output data type
    16,                                               // width of image
    16,                                               // height of image
    16 * sizeof (int8_t),                             // stride of image 0
    16 * sizeof (int8_t),                             // stride of image 1
    16 * sizeof (uint8_t),                            // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    3,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case4,                                // Input image 0
    staticRefIn1Case4,                                // Input image 1
    staticRefOutCase4,                                // Output image
    VXLIB_INT8,                                       // Input data type
    VXLIB_UINT8,                                      // Output data type
    32,                                               // width of image
    32,                                               // height of image
    32 * sizeof (int8_t),                             // stride of image 0
    32 * sizeof (int8_t),                             // stride of image 1
    32 * sizeof (uint8_t),                            // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    4,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case5,                                // Input image 0
    staticRefIn1Case5,                                // Input image 1
    staticRefOutCase5,                                // Output image
    VXLIB_INT8,                                       // Input data type
    VXLIB_UINT8,                                      // Output data type
    64,                                               // width of image
    64,                                               // height of image
    64 * sizeof (int8_t),                             // stride of image 0
    64 * sizeof (int8_t),                             // stride of image 1
    64 * sizeof (uint8_t),                            // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    5,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case6,                                // Input image 0
    staticRefIn1Case6,                                // Input image 1
    staticRefOutCase6,                                // Output image
    VXLIB_INT8,                                       // Input data type
    VXLIB_UINT8,                                      // Output data type
    128,                                              // width of image
    128,                                              // height of image
    128 * sizeof (int8_t),                            // stride of image 0
    128 * sizeof (int8_t),                            // stride of image 1
    128 * sizeof (uint8_t),                           // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    6,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case7,                                // Input image 0
    staticRefIn1Case7,                                // Input image 1
    staticRefOutCase7,                                // Output image
    VXLIB_INT8,                                       // Input data type
    VXLIB_UINT8,                                      // Output data type
    256,                                              // width of image
    256,                                              // height of image
    256 * sizeof (int8_t),                            // stride of image 0
    256 * sizeof (int8_t),                            // stride of image 1
    256 * sizeof (uint8_t),                           // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    7,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case8,                                // Input image 0
    staticRefIn1Case8,                                // Input image 1
    staticRefOutCase8,                                // Output image
    VXLIB_INT8,                                       // Input data type
    VXLIB_UINT8,                                      // Output data type
    3,                                                // width of image
    3,                                                // height of image
    64 * sizeof (int8_t),                             // stride of image 0
    64 * sizeof (int8_t),                             // stride of image 1
    64 * sizeof (uint8_t),                            // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    8,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case9,                                // Input image 0
    staticRefIn1Case9,                                // Input image 1
    staticRefOutCase9,                                // Output image
    VXLIB_INT8,                                       // Input data type
    VXLIB_UINT8,                                      // Output data type
    8,                                                // width of image
    8,                                                // height of image
    64 * sizeof (int8_t),                             // stride of image 0
    64 * sizeof (int8_t),                             // stride of image 1
    64 * sizeof (uint8_t),                            // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    9,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case10,                               // Input image 0
    staticRefIn1Case10,                               // Input image 1
    staticRefOutCase10,                               // Output image
    VXLIB_INT8,                                       // Input data type
    VXLIB_UINT8,                                      // Output data type
    16,                                               // width of image
    16,                                               // height of image
    64 * sizeof (int8_t),                             // stride of image 0
    64 * sizeof (int8_t),                             // stride of image 1
    64 * sizeof (uint8_t),                            // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    10,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case11,                               // Input image 0
    staticRefIn1Case11,                               // Input image 1
    staticRefOutCase11,                               // Output image
    VXLIB_INT8,                                       // Input data type
    VXLIB_UINT8,                                      // Output data type
    32,                                               // width of image
    32,                                               // height of image
    64 * sizeof (int8_t),                             // stride of image 0
    64 * sizeof (int8_t),                             // stride of image 1
    64 * sizeof (uint8_t),                            // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    11,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case12,                               // Input image 0
    staticRefIn1Case12,                               // Input image 1
    staticRefOutCase12,                               // Output image
    VXLIB_INT8,                                       // Input data type
    VXLIB_UINT8,                                      // Output data type
    64,                                               // width of image
    64,                                               // height of image
    128 * sizeof (int8_t),                            // stride of image 0
    128 * sizeof (int8_t),                            // stride of image 1
    128 * sizeof (uint8_t),                           // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    12,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 13))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case13,                               // Input image 0
    staticRefIn1Case13,                               // Input image 1
    staticRefOutCase13,                               // Output image
    VXLIB_INT8,                                       // Input data type
    VXLIB_UINT8,                                      // Output data type
    128,                                              // width of image
    128,                                              // height of image
    192 * sizeof (int8_t),                            // stride of image 0
    192 * sizeof (int8_t),                            // stride of image 1
    192 * sizeof (uint8_t),                           // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    13,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 14))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case14,                               // Input image 0
    staticRefIn1Case14,                               // Input image 1
    staticRefOutCase14,                               // Output image
    VXLIB_INT8,                                       // Input data type
    VXLIB_UINT8,                                      // Output data type
    256,                                              // width of image
    256,                                              // height of image
    320 * sizeof (int8_t),                            // stride of image 0
    320 * sizeof (int8_t),                            // stride of image 1
    320 * sizeof (uint8_t),                           // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    14,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 15))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case15,                               // Input image 0
    staticRefIn1Case15,                               // Input image 1
    staticRefOutCase15,                               // Output image
    VXLIB_INT8,                                       // Input data type
    VXLIB_UINT8,                                      // Output data type
    4,                                                // width of image
    2,                                                // height of image
    64 * sizeof (int8_t),                             // stride of image 0
    64 * sizeof (int8_t),                             // stride of image 1
    64 * sizeof (uint8_t),                            // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    15,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 16))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case16,                               // Input image 0
    staticRefIn1Case16,                               // Input image 1
    staticRefOutCase16,                               // Output image
    VXLIB_INT8,                                       // Input data type
    VXLIB_UINT8,                                      // Output data type
    3,                                                // width of image
    33,                                               // height of image
    48 * sizeof (int8_t),                             // stride of image 0
    48 * sizeof (int8_t),                             // stride of image 1
    48 * sizeof (uint8_t),                            // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    16,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 17))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case17,                               // Input image 0
    staticRefIn1Case17,                               // Input image 1
    staticRefOutCase17,                               // Output image
    VXLIB_INT8,                                       // Input data type
    VXLIB_UINT8,                                      // Output data type
    65,                                               // width of image
    33,                                               // height of image
    65 * sizeof (int8_t),                             // stride of image 0
    65 * sizeof (int8_t),                             // stride of image 1
    65 * sizeof (uint8_t),                            // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    17,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 18))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case18,                               // Input image 0
    staticRefIn1Case18,                               // Input image 1
    staticRefOutCase18,                               // Output image
    VXLIB_INT8,                                       // Input data type
    VXLIB_UINT8,                                      // Output data type
    31,                                               // width of image
    31,                                               // height of image
    31 * sizeof (int8_t),                             // stride of image 0
    128 * sizeof (int8_t),                            // stride of image 1
    128 * sizeof (uint8_t),                           // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    18,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 19))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case19,                               // Input image 0
    staticRefIn1Case19,                               // Input image 1
    staticRefOutCase19,                               // Output image
    VXLIB_INT8,                                       // Input data type
    VXLIB_UINT8,                                      // Output data type
    65,                                               // width of image
    65,                                               // height of image
    65 * sizeof (int8_t),                             // stride of image 0
    128 * sizeof (int8_t),                            // stride of image 1
    65 * sizeof (uint8_t),                            // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    19,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 20))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case20,                               // Input image 0
    staticRefIn1Case20,                               // Input image 1
    staticRefOutCase20,                               // Output image
    VXLIB_INT8,                                       // Input data type
    VXLIB_UINT8,                                      // Output data type
    128,                                              // width of image
    128,                                              // height of image
    192 * sizeof (int8_t),                            // stride of image 0
    192 * sizeof (int8_t),                            // stride of image 1
    256 * sizeof (uint8_t),                           // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    20,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 21))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case21,                               // Input image 0
    staticRefIn1Case21,                               // Input image 1
    staticRefOutCase21,                               // Output image
    VXLIB_INT8,                                       // Input data type
    VXLIB_UINT8,                                      // Output data type
    144,                                              // width of image
    128,                                              // height of image
    144 * sizeof (int8_t),                            // stride of image 0
    192 * sizeof (int8_t),                            // stride of image 1
    256 * sizeof (uint8_t),                           // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    21,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 22))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case22,                               // Input image 0
    staticRefIn1Case22,                               // Input image 1
    staticRefOutCase22,                               // Output image
    VXLIB_INT8,                                       // Input data type
    VXLIB_UINT8,                                      // Output data type
    10,                                               // width of image
    120,                                              // height of image
    10 * sizeof (int8_t),                             // stride of image 0
    10 * sizeof (int8_t),                             // stride of image 1
    10 * sizeof (uint8_t),                            // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    22,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 23))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case23,                               // Input image 0
    staticRefIn1Case23,                               // Input image 1
    staticRefOutCase23,                               // Output image
    VXLIB_INT8,                                       // Input data type
    VXLIB_UINT8,                                      // Output data type
    1,                                                // width of image
    1200,                                             // height of image
    10 * sizeof (int8_t),                             // stride of image 0
    10 * sizeof (int8_t),                             // stride of image 1
    10 * sizeof (uint8_t),                            // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    23,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 24))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case24,                               // Input image 0
    staticRefIn1Case24,                               // Input image 1
    staticRefOutCase24,                               // Output image
    VXLIB_INT16,                                      // Input data type
    VXLIB_UINT16,                                     // Output data type
    3,                                                // width of image
    3,                                                // height of image
    3 * sizeof (int16_t),                             // stride of image 0
    3 * sizeof (int16_t),                             // stride of image 1
    3 * sizeof (uint16_t),                            // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    24,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 25))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case25,                               // Input image 0
    staticRefIn1Case25,                               // Input image 1
    staticRefOutCase25,                               // Output image
    VXLIB_INT16,                                      // Input data type
    VXLIB_UINT16,                                     // Output data type
    8,                                                // width of image
    8,                                                // height of image
    8 * sizeof (int16_t),                             // stride of image 0
    8 * sizeof (int16_t),                             // stride of image 1
    8 * sizeof (uint16_t),                            // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    25,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 26))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case26,                               // Input image 0
    staticRefIn1Case26,                               // Input image 1
    staticRefOutCase26,                               // Output image
    VXLIB_INT16,                                      // Input data type
    VXLIB_UINT16,                                     // Output data type
    16,                                               // width of image
    16,                                               // height of image
    16 * sizeof (int16_t),                            // stride of image 0
    16 * sizeof (int16_t),                            // stride of image 1
    16 * sizeof (uint16_t),                           // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    26,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 27))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case27,                               // Input image 0
    staticRefIn1Case27,                               // Input image 1
    staticRefOutCase27,                               // Output image
    VXLIB_INT16,                                      // Input data type
    VXLIB_UINT16,                                     // Output data type
    32,                                               // width of image
    32,                                               // height of image
    32 * sizeof (int16_t),                            // stride of image 0
    32 * sizeof (int16_t),                            // stride of image 1
    32 * sizeof (uint16_t),                           // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    27,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 28))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case28,                               // Input image 0
    staticRefIn1Case28,                               // Input image 1
    staticRefOutCase28,                               // Output image
    VXLIB_INT16,                                      // Input data type
    VXLIB_UINT16,                                     // Output data type
    64,                                               // width of image
    64,                                               // height of image
    64 * sizeof (int16_t),                            // stride of image 0
    64 * sizeof (int16_t),                            // stride of image 1
    64 * sizeof (uint16_t),                           // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    28,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 29))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case29,                               // Input image 0
    staticRefIn1Case29,                               // Input image 1
    staticRefOutCase29,                               // Output image
    VXLIB_INT16,                                      // Input data type
    VXLIB_UINT16,                                     // Output data type
    128,                                              // width of image
    128,                                              // height of image
    128 * sizeof (int16_t),                           // stride of image 0
    128 * sizeof (int16_t),                           // stride of image 1
    128 * sizeof (uint16_t),                          // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    29,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 30))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case30,                               // Input image 0
    staticRefIn1Case30,                               // Input image 1
    staticRefOutCase30,                               // Output image
    VXLIB_INT16,                                      // Input data type
    VXLIB_UINT16,                                     // Output data type
    256,                                              // width of image
    256,                                              // height of image
    256 * sizeof (int16_t),                           // stride of image 0
    256 * sizeof (int16_t),                           // stride of image 1
    256 * sizeof (uint16_t),                          // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    30,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 31))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case31,                               // Input image 0
    staticRefIn1Case31,                               // Input image 1
    staticRefOutCase31,                               // Output image
    VXLIB_INT16,                                      // Input data type
    VXLIB_UINT16,                                     // Output data type
    3,                                                // width of image
    3,                                                // height of image
    64 * sizeof (int16_t),                            // stride of image 0
    64 * sizeof (int16_t),                            // stride of image 1
    64 * sizeof (uint16_t),                           // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    31,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 32))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case32,                               // Input image 0
    staticRefIn1Case32,                               // Input image 1
    staticRefOutCase32,                               // Output image
    VXLIB_INT16,                                      // Input data type
    VXLIB_UINT16,                                     // Output data type
    8,                                                // width of image
    8,                                                // height of image
    64 * sizeof (int16_t),                            // stride of image 0
    64 * sizeof (int16_t),                            // stride of image 1
    64 * sizeof (uint16_t),                           // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    32,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 33))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case33,                               // Input image 0
    staticRefIn1Case33,                               // Input image 1
    staticRefOutCase33,                               // Output image
    VXLIB_INT16,                                      // Input data type
    VXLIB_UINT16,                                     // Output data type
    16,                                               // width of image
    16,                                               // height of image
    64 * sizeof (int16_t),                            // stride of image 0
    64 * sizeof (int16_t),                            // stride of image 1
    64 * sizeof (uint16_t),                           // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    33,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 34))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case34,                               // Input image 0
    staticRefIn1Case34,                               // Input image 1
    staticRefOutCase34,                               // Output image
    VXLIB_INT16,                                      // Input data type
    VXLIB_UINT16,                                     // Output data type
    32,                                               // width of image
    32,                                               // height of image
    64 * sizeof (int16_t),                            // stride of image 0
    64 * sizeof (int16_t),                            // stride of image 1
    64 * sizeof (uint16_t),                           // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    34,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 35))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case35,                               // Input image 0
    staticRefIn1Case35,                               // Input image 1
    staticRefOutCase35,                               // Output image
    VXLIB_INT16,                                      // Input data type
    VXLIB_UINT16,                                     // Output data type
    64,                                               // width of image
    64,                                               // height of image
    128 * sizeof (int16_t),                           // stride of image 0
    128 * sizeof (int16_t),                           // stride of image 1
    128 * sizeof (uint16_t),                          // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    35,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 36))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case36,                               // Input image 0
    staticRefIn1Case36,                               // Input image 1
    staticRefOutCase36,                               // Output image
    VXLIB_INT16,                                      // Input data type
    VXLIB_UINT16,                                     // Output data type
    128,                                              // width of image
    128,                                              // height of image
    192 * sizeof (int16_t),                           // stride of image 0
    192 * sizeof (int16_t),                           // stride of image 1
    192 * sizeof (uint16_t),                          // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    36,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 37))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case37,                               // Input image 0
    staticRefIn1Case37,                               // Input image 1
    staticRefOutCase37,                               // Output image
    VXLIB_INT16,                                      // Input data type
    VXLIB_UINT16,                                     // Output data type
    256,                                              // width of image
    256,                                              // height of image
    320 * sizeof (int16_t),                           // stride of image 0
    320 * sizeof (int16_t),                           // stride of image 1
    320 * sizeof (uint16_t),                          // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    37,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 38))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case38,                               // Input image 0
    staticRefIn1Case38,                               // Input image 1
    staticRefOutCase38,                               // Output image
    VXLIB_INT16,                                      // Input data type
    VXLIB_UINT16,                                     // Output data type
    4,                                                // width of image
    2,                                                // height of image
    64 * sizeof (int16_t),                            // stride of image 0
    64 * sizeof (int16_t),                            // stride of image 1
    64 * sizeof (uint16_t),                           // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    38,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 39))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case39,                               // Input image 0
    staticRefIn1Case39,                               // Input image 1
    staticRefOutCase39,                               // Output image
    VXLIB_INT16,                                      // Input data type
    VXLIB_UINT16,                                     // Output data type
    3,                                                // width of image
    33,                                               // height of image
    48 * sizeof (int16_t),                            // stride of image 0
    48 * sizeof (int16_t),                            // stride of image 1
    48 * sizeof (uint16_t),                           // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    39,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 40))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case40,                               // Input image 0
    staticRefIn1Case40,                               // Input image 1
    staticRefOutCase40,                               // Output image
    VXLIB_INT16,                                      // Input data type
    VXLIB_UINT16,                                     // Output data type
    65,                                               // width of image
    33,                                               // height of image
    65 * sizeof (int16_t),                            // stride of image 0
    65 * sizeof (int16_t),                            // stride of image 1
    65 * sizeof (uint16_t),                           // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    40,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 41))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case41,                               // Input image 0
    staticRefIn1Case41,                               // Input image 1
    staticRefOutCase41,                               // Output image
    VXLIB_INT16,                                      // Input data type
    VXLIB_UINT16,                                     // Output data type
    31,                                               // width of image
    31,                                               // height of image
    31 * sizeof (int16_t),                            // stride of image 0
    128 * sizeof (int16_t),                           // stride of image 1
    128 * sizeof (uint16_t),                          // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    41,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 42))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case42,                               // Input image 0
    staticRefIn1Case42,                               // Input image 1
    staticRefOutCase42,                               // Output image
    VXLIB_INT16,                                      // Input data type
    VXLIB_UINT16,                                     // Output data type
    65,                                               // width of image
    65,                                               // height of image
    65 * sizeof (int16_t),                            // stride of image 0
    128 * sizeof (int16_t),                           // stride of image 1
    65 * sizeof (uint16_t),                           // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    42,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 43))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case43,                               // Input image 0
    staticRefIn1Case43,                               // Input image 1
    staticRefOutCase43,                               // Output image
    VXLIB_INT16,                                      // Input data type
    VXLIB_UINT16,                                     // Output data type
    128,                                              // width of image
    128,                                              // height of image
    192 * sizeof (int16_t),                           // stride of image 0
    192 * sizeof (int16_t),                           // stride of image 1
    256 * sizeof (uint16_t),                          // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    43,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 44))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case44,                               // Input image 0
    staticRefIn1Case44,                               // Input image 1
    staticRefOutCase44,                               // Output image
    VXLIB_INT16,                                      // Input data type
    VXLIB_UINT16,                                     // Output data type
    144,                                              // width of image
    128,                                              // height of image
    144 * sizeof (int16_t),                           // stride of image 0
    192 * sizeof (int16_t),                           // stride of image 1
    256 * sizeof (uint16_t),                          // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    44,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 45))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case45,                               // Input image 0
    staticRefIn1Case45,                               // Input image 1
    staticRefOutCase45,                               // Output image
    VXLIB_INT16,                                      // Input data type
    VXLIB_UINT16,                                     // Output data type
    10,                                               // width of image
    120,                                              // height of image
    10 * sizeof (int16_t),                            // stride of image 0
    10 * sizeof (int16_t),                            // stride of image 1
    10 * sizeof (uint16_t),                           // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    45,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 46))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case46,                               // Input image 0
    staticRefIn1Case46,                               // Input image 1
    staticRefOutCase46,                               // Output image
    VXLIB_INT16,                                      // Input data type
    VXLIB_UINT16,                                     // Output data type
    1,                                                // width of image
    1200,                                             // height of image
    10 * sizeof (int16_t),                            // stride of image 0
    10 * sizeof (int16_t),                            // stride of image 1
    10 * sizeof (uint16_t),                           // stride of output image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    46,                                               // test ID
    },
#endif

};

/*
 *  Sends the test parameter structure and number of tests
 */
void
VXLIB_normL1_getTestParams (VXLIB_normL1_testParams_t ** params, int32_t * numTests)
{
   *params = testParams;
   *numTests = sizeof (testParams) / sizeof (VXLIB_normL1_testParams_t);
}
