syntax = "proto2";

package tidl_quant_params;

// Top level configuration for the message storing TIDL Network Quantization Parameters
message TIDLNetQuantParams {
  optional int32 num_layers = 1;
  optional TidlQuantType quant_type = 2 [default = SYMMETRIC];
  optional TidlCalibType calib_type = 3 [default = PERTENSOR];
  repeated TidlLayerQuantParams layers = 4;
}

// Quantization Type
enum TidlQuantType {
SYMMETRIC = 1;
ASYMMETRIC = 2;
}

// Calibration Type
enum TidlCalibType {
PERTENSOR = 1;
PERCHANNEL = 2;
}

// Configuration for storing TIDL Layer Quantization Parameters
message TidlLayerQuantParams {
  optional string layer_name = 1; 
  optional string layer_type = 2;
  optional uint32 bit_depth = 3 [default = 8];
  repeated TidlTensorQuantParams outputs = 4;
  repeated TidlTensorQuantParams weights = 5;
  repeated TidlTensorQuantParams bias = 6;
  repeated TidlTensorQuantParams slope = 7;
}

// Configuration for storing TIDL Tensor Quantization Parameters
message TidlTensorQuantParams {
  optional float min = 1 [default = -3.4028234664e+38]; 
  optional float max = 2 [default = 3.4028234664e+38]; 
  optional uint32 size = 3;
  optional uint32 element_type = 4;
  repeated double scale = 5 [packed=true];
  repeated uint32 zero_point = 6 [packed=true];  
  repeated double value = 7 [packed=true];
}
