/******************************************************************************/
/* Copyright (C) 2023 Texas Instruments Incorporated - http://www.ti.com/
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 ******************************************************************************/
#include "DSPLIB_w_vec_idat.h"
/*This file is autogenerated*/
/*Please do not edit*/

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
#include "test_data/staticRefCase1.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2) || defined(DEMO_CASE))
#include "test_data/staticRefCase2.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
#include "test_data/staticRefCase3.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
#include "test_data/staticRefCase4.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
#include "test_data/staticRefCase5.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
#include "test_data/staticRefCase6.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7) || defined(DEMO_CASE))
#include "test_data/staticRefCase7.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
#include "test_data/staticRefCase8.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
#include "test_data/staticRefCase9.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
#include "test_data/staticRefCase10.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
#include "test_data/staticRefCase11.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12) || defined(DEMO_CASE))
#include "test_data/staticRefCase12.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 13))
#include "test_data/staticRefCase13.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 14))
#include "test_data/staticRefCase14.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 15))
#include "test_data/staticRefCase15.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 16))
#include "test_data/staticRefCase16.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 17) || defined(DEMO_CASE))
#include "test_data/staticRefCase17.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 18))
#include "test_data/staticRefCase18.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 19))
#include "test_data/staticRefCase19.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 20))
#include "test_data/staticRefCase20.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 21))
#include "test_data/staticRefCase21.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 22) || defined(DEMO_CASE))
#include "test_data/staticRefCase22.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 23))
#include "test_data/staticRefCase23.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 24))
#include "test_data/staticRefCase24.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 25))
#include "test_data/staticRefCase25.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 26))
#include "test_data/staticRefCase26.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 27) || defined(DEMO_CASE))
#include "test_data/staticRefCase27.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 28))
#include "test_data/staticRefCase28.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 29))
#include "test_data/staticRefCase29.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 30))
#include "test_data/staticRefCase30.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 31))
#include "test_data/staticRefCase31.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 32) || defined(DEMO_CASE))
#include "test_data/staticRefCase32.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 33))
#include "test_data/staticRefCase33.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 34))
#include "test_data/staticRefCase34.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 35))
#include "test_data/staticRefCase35.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 36))
#include "test_data/staticRefCase36.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 37) || defined(DEMO_CASE))
#include "test_data/staticRefCase37.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 38))
#include "test_data/staticRefCase38.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 39))
#include "test_data/staticRefCase39.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 40))
#include "test_data/staticRefCase40.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 41))
#include "test_data/staticRefCase41.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 42) || defined(DEMO_CASE))
#include "test_data/staticRefCase42.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 43))
#include "test_data/staticRefCase43.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 44))
#include "test_data/staticRefCase44.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 45))
#include "test_data/staticRefCase45.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 46))
#include "test_data/staticRefCase46.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 47) || defined(DEMO_CASE))
#include "test_data/staticRefCase47.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 48))
#include "test_data/staticRefCase48.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 49))
#include "test_data/staticRefCase49.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 50))
#include "test_data/staticRefCase50.h"
#endif

static DSPLIB_w_vec_testParams_t testParams[] = {
#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case1,                                // Input vector 0
    staticRefIn1Case1,                                // Input vector 1
    staticRefmCase1,                                  // Input weight factor
    staticRefOutCase1,                                // Output vector
    DSPLIB_FLOAT32,                                   // precision
    256,                                              // length of vector
    (DSPLIB_w_vec_weightStyle) 0,                     // Input weight style
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    1,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2) || defined(DEMO_CASE))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case2,                                // Input vector 0
    staticRefIn1Case2,                                // Input vector 1
    staticRefmCase2,                                  // Input weight factor
    staticRefOutCase2,                                // Output vector
    DSPLIB_FLOAT32,                                   // precision
    512,                                              // length of vector
    (DSPLIB_w_vec_weightStyle) 0,                     // Input weight style
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    2,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case3,                                // Input vector 0
    staticRefIn1Case3,                                // Input vector 1
    staticRefmCase3,                                  // Input weight factor
    staticRefOutCase3,                                // Output vector
    DSPLIB_FLOAT32,                                   // precision
    1024,                                             // length of vector
    (DSPLIB_w_vec_weightStyle) 0,                     // Input weight style
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    3,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case4,                                // Input vector 0
    staticRefIn1Case4,                                // Input vector 1
    staticRefmCase4,                                  // Input weight factor
    staticRefOutCase4,                                // Output vector
    DSPLIB_FLOAT32,                                   // precision
    2048,                                             // length of vector
    (DSPLIB_w_vec_weightStyle) 0,                     // Input weight style
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    4,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case5,                                // Input vector 0
    staticRefIn1Case5,                                // Input vector 1
    staticRefmCase5,                                  // Input weight factor
    staticRefOutCase5,                                // Output vector
    DSPLIB_FLOAT32,                                   // precision
    10240,                                            // length of vector
    (DSPLIB_w_vec_weightStyle) 0,                     // Input weight style
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    5,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case6,                                // Input vector 0
    staticRefIn1Case6,                                // Input vector 1
    staticRefmCase6,                                  // Input weight factor
    staticRefOutCase6,                                // Output vector
    DSPLIB_INT32,                                     // precision
    256,                                              // length of vector
    (DSPLIB_w_vec_weightStyle) 0,                     // Input weight style
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    6,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7) || defined(DEMO_CASE))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case7,                                // Input vector 0
    staticRefIn1Case7,                                // Input vector 1
    staticRefmCase7,                                  // Input weight factor
    staticRefOutCase7,                                // Output vector
    DSPLIB_INT32,                                     // precision
    512,                                              // length of vector
    (DSPLIB_w_vec_weightStyle) 0,                     // Input weight style
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    7,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case8,                                // Input vector 0
    staticRefIn1Case8,                                // Input vector 1
    staticRefmCase8,                                  // Input weight factor
    staticRefOutCase8,                                // Output vector
    DSPLIB_INT32,                                     // precision
    1024,                                             // length of vector
    (DSPLIB_w_vec_weightStyle) 0,                     // Input weight style
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    8,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case9,                                // Input vector 0
    staticRefIn1Case9,                                // Input vector 1
    staticRefmCase9,                                  // Input weight factor
    staticRefOutCase9,                                // Output vector
    DSPLIB_UINT32,                                    // precision
    2048,                                             // length of vector
    (DSPLIB_w_vec_weightStyle) 0,                     // Input weight style
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    9,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case10,                               // Input vector 0
    staticRefIn1Case10,                               // Input vector 1
    staticRefmCase10,                                 // Input weight factor
    staticRefOutCase10,                               // Output vector
    DSPLIB_UINT32,                                    // precision
    10240,                                            // length of vector
    (DSPLIB_w_vec_weightStyle) 0,                     // Input weight style
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    10,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case11,                               // Input vector 0
    staticRefIn1Case11,                               // Input vector 1
    staticRefmCase11,                                 // Input weight factor
    staticRefOutCase11,                               // Output vector
    DSPLIB_INT16,                                     // precision
    256,                                              // length of vector
    (DSPLIB_w_vec_weightStyle) 0,                     // Input weight style
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    11,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12) || defined(DEMO_CASE))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case12,                               // Input vector 0
    staticRefIn1Case12,                               // Input vector 1
    staticRefmCase12,                                 // Input weight factor
    staticRefOutCase12,                               // Output vector
    DSPLIB_INT16,                                     // precision
    512,                                              // length of vector
    (DSPLIB_w_vec_weightStyle) 0,                     // Input weight style
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    12,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 13))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case13,                               // Input vector 0
    staticRefIn1Case13,                               // Input vector 1
    staticRefmCase13,                                 // Input weight factor
    staticRefOutCase13,                               // Output vector
    DSPLIB_INT16,                                     // precision
    1024,                                             // length of vector
    (DSPLIB_w_vec_weightStyle) 0,                     // Input weight style
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    13,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 14))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case14,                               // Input vector 0
    staticRefIn1Case14,                               // Input vector 1
    staticRefmCase14,                                 // Input weight factor
    staticRefOutCase14,                               // Output vector
    DSPLIB_UINT16,                                    // precision
    2048,                                             // length of vector
    (DSPLIB_w_vec_weightStyle) 0,                     // Input weight style
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    14,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 15))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case15,                               // Input vector 0
    staticRefIn1Case15,                               // Input vector 1
    staticRefmCase15,                                 // Input weight factor
    staticRefOutCase15,                               // Output vector
    DSPLIB_UINT16,                                    // precision
    10240,                                            // length of vector
    (DSPLIB_w_vec_weightStyle) 0,                     // Input weight style
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    15,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 16))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case16,                               // Input vector 0
    staticRefIn1Case16,                               // Input vector 1
    staticRefmCase16,                                 // Input weight factor
    staticRefOutCase16,                               // Output vector
    DSPLIB_INT8,                                      // precision
    256,                                              // length of vector
    (DSPLIB_w_vec_weightStyle) 0,                     // Input weight style
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    16,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 17) || defined(DEMO_CASE))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case17,                               // Input vector 0
    staticRefIn1Case17,                               // Input vector 1
    staticRefmCase17,                                 // Input weight factor
    staticRefOutCase17,                               // Output vector
    DSPLIB_INT8,                                      // precision
    512,                                              // length of vector
    (DSPLIB_w_vec_weightStyle) 0,                     // Input weight style
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    17,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 18))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case18,                               // Input vector 0
    staticRefIn1Case18,                               // Input vector 1
    staticRefmCase18,                                 // Input weight factor
    staticRefOutCase18,                               // Output vector
    DSPLIB_INT8,                                      // precision
    1024,                                             // length of vector
    (DSPLIB_w_vec_weightStyle) 0,                     // Input weight style
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    18,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 19))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case19,                               // Input vector 0
    staticRefIn1Case19,                               // Input vector 1
    staticRefmCase19,                                 // Input weight factor
    staticRefOutCase19,                               // Output vector
    DSPLIB_UINT8,                                     // precision
    2048,                                             // length of vector
    (DSPLIB_w_vec_weightStyle) 0,                     // Input weight style
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    19,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 20))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case20,                               // Input vector 0
    staticRefIn1Case20,                               // Input vector 1
    staticRefmCase20,                                 // Input weight factor
    staticRefOutCase20,                               // Output vector
    DSPLIB_UINT8,                                     // precision
    10240,                                            // length of vector
    (DSPLIB_w_vec_weightStyle) 0,                     // Input weight style
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    20,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 21))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case21,                               // Input vector 0
    staticRefIn1Case21,                               // Input vector 1
    staticRefmCase21,                                 // Input weight factor
    staticRefOutCase21,                               // Output vector
    DSPLIB_FLOAT64,                                   // precision
    256,                                              // length of vector
    (DSPLIB_w_vec_weightStyle) 0,                     // Input weight style
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    21,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 22) || defined(DEMO_CASE))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case22,                               // Input vector 0
    staticRefIn1Case22,                               // Input vector 1
    staticRefmCase22,                                 // Input weight factor
    staticRefOutCase22,                               // Output vector
    DSPLIB_FLOAT64,                                   // precision
    512,                                              // length of vector
    (DSPLIB_w_vec_weightStyle) 0,                     // Input weight style
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    22,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 23))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case23,                               // Input vector 0
    staticRefIn1Case23,                               // Input vector 1
    staticRefmCase23,                                 // Input weight factor
    staticRefOutCase23,                               // Output vector
    DSPLIB_FLOAT64,                                   // precision
    1024,                                             // length of vector
    (DSPLIB_w_vec_weightStyle) 0,                     // Input weight style
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    23,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 24))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case24,                               // Input vector 0
    staticRefIn1Case24,                               // Input vector 1
    staticRefmCase24,                                 // Input weight factor
    staticRefOutCase24,                               // Output vector
    DSPLIB_FLOAT64,                                   // precision
    2048,                                             // length of vector
    (DSPLIB_w_vec_weightStyle) 0,                     // Input weight style
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    24,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 25))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case25,                               // Input vector 0
    staticRefIn1Case25,                               // Input vector 1
    staticRefmCase25,                                 // Input weight factor
    staticRefOutCase25,                               // Output vector
    DSPLIB_FLOAT64,                                   // precision
    10240,                                            // length of vector
    (DSPLIB_w_vec_weightStyle) 0,                     // Input weight style
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    25,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 26))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case26,                               // Input vector 0
    staticRefIn1Case26,                               // Input vector 1
    staticRefmCase26,                                 // Input weight factor
    staticRefOutCase26,                               // Output vector
    DSPLIB_FLOAT32,                                   // precision
    256,                                              // length of vector
    (DSPLIB_w_vec_weightStyle) 1,                     // Input weight style
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    26,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 27) || defined(DEMO_CASE))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case27,                               // Input vector 0
    staticRefIn1Case27,                               // Input vector 1
    staticRefmCase27,                                 // Input weight factor
    staticRefOutCase27,                               // Output vector
    DSPLIB_FLOAT32,                                   // precision
    512,                                              // length of vector
    (DSPLIB_w_vec_weightStyle) 1,                     // Input weight style
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    27,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 28))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case28,                               // Input vector 0
    staticRefIn1Case28,                               // Input vector 1
    staticRefmCase28,                                 // Input weight factor
    staticRefOutCase28,                               // Output vector
    DSPLIB_FLOAT32,                                   // precision
    1024,                                             // length of vector
    (DSPLIB_w_vec_weightStyle) 1,                     // Input weight style
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    28,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 29))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case29,                               // Input vector 0
    staticRefIn1Case29,                               // Input vector 1
    staticRefmCase29,                                 // Input weight factor
    staticRefOutCase29,                               // Output vector
    DSPLIB_FLOAT32,                                   // precision
    2048,                                             // length of vector
    (DSPLIB_w_vec_weightStyle) 1,                     // Input weight style
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    29,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 30))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case30,                               // Input vector 0
    staticRefIn1Case30,                               // Input vector 1
    staticRefmCase30,                                 // Input weight factor
    staticRefOutCase30,                               // Output vector
    DSPLIB_FLOAT32,                                   // precision
    10240,                                            // length of vector
    (DSPLIB_w_vec_weightStyle) 1,                     // Input weight style
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    30,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 31))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case31,                               // Input vector 0
    staticRefIn1Case31,                               // Input vector 1
    staticRefmCase31,                                 // Input weight factor
    staticRefOutCase31,                               // Output vector
    DSPLIB_INT32,                                     // precision
    256,                                              // length of vector
    (DSPLIB_w_vec_weightStyle) 1,                     // Input weight style
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    31,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 32) || defined(DEMO_CASE))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case32,                               // Input vector 0
    staticRefIn1Case32,                               // Input vector 1
    staticRefmCase32,                                 // Input weight factor
    staticRefOutCase32,                               // Output vector
    DSPLIB_INT32,                                     // precision
    512,                                              // length of vector
    (DSPLIB_w_vec_weightStyle) 1,                     // Input weight style
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    32,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 33))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case33,                               // Input vector 0
    staticRefIn1Case33,                               // Input vector 1
    staticRefmCase33,                                 // Input weight factor
    staticRefOutCase33,                               // Output vector
    DSPLIB_INT32,                                     // precision
    1024,                                             // length of vector
    (DSPLIB_w_vec_weightStyle) 1,                     // Input weight style
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    33,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 34))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case34,                               // Input vector 0
    staticRefIn1Case34,                               // Input vector 1
    staticRefmCase34,                                 // Input weight factor
    staticRefOutCase34,                               // Output vector
    DSPLIB_UINT32,                                    // precision
    2048,                                             // length of vector
    (DSPLIB_w_vec_weightStyle) 1,                     // Input weight style
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    34,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 35))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case35,                               // Input vector 0
    staticRefIn1Case35,                               // Input vector 1
    staticRefmCase35,                                 // Input weight factor
    staticRefOutCase35,                               // Output vector
    DSPLIB_UINT32,                                    // precision
    10240,                                            // length of vector
    (DSPLIB_w_vec_weightStyle) 1,                     // Input weight style
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    35,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 36))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case36,                               // Input vector 0
    staticRefIn1Case36,                               // Input vector 1
    staticRefmCase36,                                 // Input weight factor
    staticRefOutCase36,                               // Output vector
    DSPLIB_INT16,                                     // precision
    256,                                              // length of vector
    (DSPLIB_w_vec_weightStyle) 1,                     // Input weight style
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    36,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 37) || defined(DEMO_CASE))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case37,                               // Input vector 0
    staticRefIn1Case37,                               // Input vector 1
    staticRefmCase37,                                 // Input weight factor
    staticRefOutCase37,                               // Output vector
    DSPLIB_INT16,                                     // precision
    512,                                              // length of vector
    (DSPLIB_w_vec_weightStyle) 1,                     // Input weight style
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    37,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 38))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case38,                               // Input vector 0
    staticRefIn1Case38,                               // Input vector 1
    staticRefmCase38,                                 // Input weight factor
    staticRefOutCase38,                               // Output vector
    DSPLIB_INT16,                                     // precision
    1024,                                             // length of vector
    (DSPLIB_w_vec_weightStyle) 1,                     // Input weight style
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    38,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 39))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case39,                               // Input vector 0
    staticRefIn1Case39,                               // Input vector 1
    staticRefmCase39,                                 // Input weight factor
    staticRefOutCase39,                               // Output vector
    DSPLIB_UINT16,                                    // precision
    2048,                                             // length of vector
    (DSPLIB_w_vec_weightStyle) 1,                     // Input weight style
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    39,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 40))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case40,                               // Input vector 0
    staticRefIn1Case40,                               // Input vector 1
    staticRefmCase40,                                 // Input weight factor
    staticRefOutCase40,                               // Output vector
    DSPLIB_UINT16,                                    // precision
    10240,                                            // length of vector
    (DSPLIB_w_vec_weightStyle) 1,                     // Input weight style
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    40,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 41))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case41,                               // Input vector 0
    staticRefIn1Case41,                               // Input vector 1
    staticRefmCase41,                                 // Input weight factor
    staticRefOutCase41,                               // Output vector
    DSPLIB_INT8,                                      // precision
    256,                                              // length of vector
    (DSPLIB_w_vec_weightStyle) 1,                     // Input weight style
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    41,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 42) || defined(DEMO_CASE))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case42,                               // Input vector 0
    staticRefIn1Case42,                               // Input vector 1
    staticRefmCase42,                                 // Input weight factor
    staticRefOutCase42,                               // Output vector
    DSPLIB_INT8,                                      // precision
    512,                                              // length of vector
    (DSPLIB_w_vec_weightStyle) 1,                     // Input weight style
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    42,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 43))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case43,                               // Input vector 0
    staticRefIn1Case43,                               // Input vector 1
    staticRefmCase43,                                 // Input weight factor
    staticRefOutCase43,                               // Output vector
    DSPLIB_INT8,                                      // precision
    1024,                                             // length of vector
    (DSPLIB_w_vec_weightStyle) 1,                     // Input weight style
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    43,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 44))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case44,                               // Input vector 0
    staticRefIn1Case44,                               // Input vector 1
    staticRefmCase44,                                 // Input weight factor
    staticRefOutCase44,                               // Output vector
    DSPLIB_UINT8,                                     // precision
    2048,                                             // length of vector
    (DSPLIB_w_vec_weightStyle) 1,                     // Input weight style
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    44,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 45))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case45,                               // Input vector 0
    staticRefIn1Case45,                               // Input vector 1
    staticRefmCase45,                                 // Input weight factor
    staticRefOutCase45,                               // Output vector
    DSPLIB_UINT8,                                     // precision
    10240,                                            // length of vector
    (DSPLIB_w_vec_weightStyle) 1,                     // Input weight style
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    45,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 46))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case46,                               // Input vector 0
    staticRefIn1Case46,                               // Input vector 1
    staticRefmCase46,                                 // Input weight factor
    staticRefOutCase46,                               // Output vector
    DSPLIB_FLOAT64,                                   // precision
    256,                                              // length of vector
    (DSPLIB_w_vec_weightStyle) 1,                     // Input weight style
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    46,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 47) || defined(DEMO_CASE))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case47,                               // Input vector 0
    staticRefIn1Case47,                               // Input vector 1
    staticRefmCase47,                                 // Input weight factor
    staticRefOutCase47,                               // Output vector
    DSPLIB_FLOAT64,                                   // precision
    512,                                              // length of vector
    (DSPLIB_w_vec_weightStyle) 1,                     // Input weight style
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    47,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 48))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case48,                               // Input vector 0
    staticRefIn1Case48,                               // Input vector 1
    staticRefmCase48,                                 // Input weight factor
    staticRefOutCase48,                               // Output vector
    DSPLIB_FLOAT64,                                   // precision
    1024,                                             // length of vector
    (DSPLIB_w_vec_weightStyle) 1,                     // Input weight style
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    48,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 49))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case49,                               // Input vector 0
    staticRefIn1Case49,                               // Input vector 1
    staticRefmCase49,                                 // Input weight factor
    staticRefOutCase49,                               // Output vector
    DSPLIB_FLOAT64,                                   // precision
    2048,                                             // length of vector
    (DSPLIB_w_vec_weightStyle) 1,                     // Input weight style
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    49,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 50))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case50,                               // Input vector 0
    staticRefIn1Case50,                               // Input vector 1
    staticRefmCase50,                                 // Input weight factor
    staticRefOutCase50,                               // Output vector
    DSPLIB_FLOAT64,                                   // precision
    10240,                                            // length of vector
    (DSPLIB_w_vec_weightStyle) 1,                     // Input weight style
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    50,                                               // test ID
    },
#endif

};

/*
 *  Sends the test parameter structure and number of tests
 */
void
DSPLIB_w_vec_getTestParams (DSPLIB_w_vec_testParams_t ** params, int32_t * numTests)
{
   *params = testParams;
   *numTests = sizeof (testParams) / sizeof (DSPLIB_w_vec_testParams_t);
}
