/******************************************************************************/
/* Copyright (C) 2023 Texas Instruments Incorporated - http://www.ti.com/
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 ******************************************************************************/
#include "DSPLIB_matMul_idat.h"
/*This file is autogenerated*/
/*Please do not edit*/

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
#include "test_data/staticRefCase1.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
#include "test_data/staticRefCase2.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
#include "test_data/staticRefCase8.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
#include "test_data/staticRefCase10.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12))
#include "test_data/staticRefCase12.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 13))
#include "test_data/staticRefCase13.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 26))
#include "test_data/staticRefCase26.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 27))
#include "test_data/staticRefCase27.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 33))
#include "test_data/staticRefCase33.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 35))
#include "test_data/staticRefCase35.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 37))
#include "test_data/staticRefCase37.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 38))
#include "test_data/staticRefCase38.h"
#endif

static DSPLIB_matMul_testParams_t testParams[] = {
#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case1,                                // Input matrix A
    staticRefIn1Case1,                                // Input matrix B
    staticRefOutCase1,                                // Output matrix C
    1,                                                // M
    256,                                              // N
    16,                                               // K
    16 * sizeof (float),                              // stride of A matrix
    256 * sizeof (float),                             // stride of B matrix
    256 * sizeof (float),                             // stride of C matrix
    0,                                                // shift value for output
    DSPLIB_FLOAT32,                                   // precision
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    1,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case2,                                // Input matrix A
    staticRefIn1Case2,                                // Input matrix B
    staticRefOutCase2,                                // Output matrix C
    1,                                                // M
    16,                                               // N
    256,                                              // K
    256 * sizeof (float),                             // stride of A matrix
    16 * sizeof (float),                              // stride of B matrix
    16 * sizeof (float),                              // stride of C matrix
    0,                                                // shift value for output
    DSPLIB_FLOAT32,                                   // precision
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    2,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input matrix B
    NULL,                                             // Output matrix C
    128,                                              // M
    256,                                              // N
    128,                                              // K
    128 * sizeof (float),                             // stride of A matrix
    256 * sizeof (float),                             // stride of B matrix
    256 * sizeof (float),                             // stride of C matrix
    0,                                                // shift value for output
    DSPLIB_FLOAT32,                                   // precision
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    3,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input matrix B
    NULL,                                             // Output matrix C
    64,                                               // M
    512,                                              // N
    64,                                               // K
    64 * sizeof (float),                              // stride of A matrix
    512 * sizeof (float),                             // stride of B matrix
    512 * sizeof (float),                             // stride of C matrix
    0,                                                // shift value for output
    DSPLIB_FLOAT32,                                   // precision
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    4,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input matrix B
    NULL,                                             // Output matrix C
    128,                                              // M
    128,                                              // N
    128,                                              // K
    128 * sizeof (float),                             // stride of A matrix
    128 * sizeof (float),                             // stride of B matrix
    128 * sizeof (float),                             // stride of C matrix
    0,                                                // shift value for output
    DSPLIB_FLOAT32,                                   // precision
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    5,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input matrix B
    NULL,                                             // Output matrix C
    64,                                               // M
    256,                                              // N
    64,                                               // K
    64 * sizeof (float),                              // stride of A matrix
    256 * sizeof (float),                             // stride of B matrix
    256 * sizeof (float),                             // stride of C matrix
    0,                                                // shift value for output
    DSPLIB_FLOAT32,                                   // precision
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    6,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input matrix B
    NULL,                                             // Output matrix C
    16,                                               // M
    16,                                               // N
    1024,                                             // K
    1024 * sizeof (float),                            // stride of A matrix
    16 * sizeof (float),                              // stride of B matrix
    16 * sizeof (float),                              // stride of C matrix
    0,                                                // shift value for output
    DSPLIB_FLOAT32,                                   // precision
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    7,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case8,                                // Input matrix A
    staticRefIn1Case8,                                // Input matrix B
    staticRefOutCase8,                                // Output matrix C
    3,                                                // M
    3,                                                // N
    3,                                                // K
    3 * sizeof (float),                               // stride of A matrix
    3 * sizeof (float),                               // stride of B matrix
    3 * sizeof (float),                               // stride of C matrix
    0,                                                // shift value for output
    DSPLIB_FLOAT32,                                   // precision
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    8,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input matrix B
    NULL,                                             // Output matrix C
    31,                                               // M
    31,                                               // N
    31,                                               // K
    31 * sizeof (float),                              // stride of A matrix
    31 * sizeof (float),                              // stride of B matrix
    31 * sizeof (float),                              // stride of C matrix
    0,                                                // shift value for output
    DSPLIB_FLOAT32,                                   // precision
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    9,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case10,                               // Input matrix A
    staticRefIn1Case10,                               // Input matrix B
    staticRefOutCase10,                               // Output matrix C
    64,                                               // M
    64,                                               // N
    64,                                               // K
    64 * sizeof (float),                              // stride of A matrix
    64 * sizeof (float),                              // stride of B matrix
    64 * sizeof (float),                              // stride of C matrix
    0,                                                // shift value for output
    DSPLIB_FLOAT32,                                   // precision
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    10,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input matrix B
    NULL,                                             // Output matrix C
    51,                                               // M
    51,                                               // N
    51,                                               // K
    64 * sizeof (float),                              // stride of A matrix
    64 * sizeof (float),                              // stride of B matrix
    64 * sizeof (float),                              // stride of C matrix
    0,                                                // shift value for output
    DSPLIB_FLOAT32,                                   // precision
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    11,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case12,                               // Input matrix A
    staticRefIn1Case12,                               // Input matrix B
    staticRefOutCase12,                               // Output matrix C
    4,                                                // M
    4,                                                // N
    4,                                                // K
    4 * sizeof (float),                               // stride of A matrix
    4 * sizeof (float),                               // stride of B matrix
    4 * sizeof (float),                               // stride of C matrix
    0,                                                // shift value for output
    DSPLIB_FLOAT32,                                   // precision
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    12,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 13))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case13,                               // Input matrix A
    staticRefIn1Case13,                               // Input matrix B
    staticRefOutCase13,                               // Output matrix C
    1,                                                // M
    256,                                              // N
    16,                                               // K
    16 * sizeof (float),                              // stride of A matrix
    256 * sizeof (float),                             // stride of B matrix
    256 * sizeof (float),                             // stride of C matrix
    0,                                                // shift value for output
    DSPLIB_FLOAT32,                                   // precision
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    13,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 14))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input matrix B
    NULL,                                             // Output matrix C
    128,                                              // M
    256,                                              // N
    128,                                              // K
    128 * sizeof (float),                             // stride of A matrix
    256 * sizeof (float),                             // stride of B matrix
    256 * sizeof (float),                             // stride of C matrix
    0,                                                // shift value for output
    DSPLIB_FLOAT32,                                   // precision
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    14,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 15))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input matrix B
    NULL,                                             // Output matrix C
    64,                                               // M
    512,                                              // N
    64,                                               // K
    64 * sizeof (float),                              // stride of A matrix
    512 * sizeof (float),                             // stride of B matrix
    512 * sizeof (float),                             // stride of C matrix
    0,                                                // shift value for output
    DSPLIB_FLOAT32,                                   // precision
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    15,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 16))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input matrix B
    NULL,                                             // Output matrix C
    64,                                               // M
    256,                                              // N
    64,                                               // K
    64 * sizeof (float),                              // stride of A matrix
    256 * sizeof (float),                             // stride of B matrix
    256 * sizeof (float),                             // stride of C matrix
    0,                                                // shift value for output
    DSPLIB_FLOAT32,                                   // precision
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    16,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 17))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input matrix B
    NULL,                                             // Output matrix C
    41,                                               // M
    64,                                               // N
    55,                                               // K
    64 * sizeof (float),                              // stride of A matrix
    64 * sizeof (float),                              // stride of B matrix
    64 * sizeof (float),                              // stride of C matrix
    0,                                                // shift value for output
    DSPLIB_FLOAT32,                                   // precision
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    17,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 18))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input matrix B
    NULL,                                             // Output matrix C
    32,                                               // M
    32,                                               // N
    32,                                               // K
    32 * sizeof (float),                              // stride of A matrix
    32 * sizeof (float),                              // stride of B matrix
    32 * sizeof (float),                              // stride of C matrix
    0,                                                // shift value for output
    DSPLIB_FLOAT32,                                   // precision
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    18,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 19))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input matrix B
    NULL,                                             // Output matrix C
    1,                                                // M
    1,                                                // N
    1,                                                // K
    1 * sizeof (float),                               // stride of A matrix
    1 * sizeof (float),                               // stride of B matrix
    1 * sizeof (float),                               // stride of C matrix
    0,                                                // shift value for output
    DSPLIB_FLOAT32,                                   // precision
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    19,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 20))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input matrix B
    NULL,                                             // Output matrix C
    1,                                                // M
    1,                                                // N
    1,                                                // K
    32 * sizeof (float),                              // stride of A matrix
    32 * sizeof (float),                              // stride of B matrix
    32 * sizeof (float),                              // stride of C matrix
    0,                                                // shift value for output
    DSPLIB_FLOAT32,                                   // precision
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    20,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 21))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input matrix B
    NULL,                                             // Output matrix C
    3,                                                // M
    1,                                                // N
    1,                                                // K
    32 * sizeof (float),                              // stride of A matrix
    32 * sizeof (float),                              // stride of B matrix
    32 * sizeof (float),                              // stride of C matrix
    0,                                                // shift value for output
    DSPLIB_FLOAT32,                                   // precision
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    21,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 22))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input matrix B
    NULL,                                             // Output matrix C
    4,                                                // M
    4,                                                // N
    1,                                                // K
    32 * sizeof (float),                              // stride of A matrix
    32 * sizeof (float),                              // stride of B matrix
    32 * sizeof (float),                              // stride of C matrix
    0,                                                // shift value for output
    DSPLIB_FLOAT32,                                   // precision
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    22,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 23))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input matrix B
    NULL,                                             // Output matrix C
    4,                                                // M
    4,                                                // N
    1,                                                // K
    1 * sizeof (float),                               // stride of A matrix
    4 * sizeof (float),                               // stride of B matrix
    4 * sizeof (float),                               // stride of C matrix
    0,                                                // shift value for output
    DSPLIB_FLOAT32,                                   // precision
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    23,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 24))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input matrix B
    NULL,                                             // Output matrix C
    5,                                                // M
    5,                                                // N
    1,                                                // K
    32 * sizeof (float),                              // stride of A matrix
    32 * sizeof (float),                              // stride of B matrix
    32 * sizeof (float),                              // stride of C matrix
    0,                                                // shift value for output
    DSPLIB_FLOAT32,                                   // precision
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    24,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 25))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input matrix B
    NULL,                                             // Output matrix C
    37,                                               // M
    37,                                               // N
    1,                                                // K
    64 * sizeof (float),                              // stride of A matrix
    64 * sizeof (float),                              // stride of B matrix
    64 * sizeof (float),                              // stride of C matrix
    0,                                                // shift value for output
    DSPLIB_FLOAT32,                                   // precision
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    25,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 26))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case26,                               // Input matrix A
    staticRefIn1Case26,                               // Input matrix B
    staticRefOutCase26,                               // Output matrix C
    1,                                                // M
    256,                                              // N
    16,                                               // K
    16 * sizeof (double),                             // stride of A matrix
    256 * sizeof (double),                            // stride of B matrix
    256 * sizeof (double),                            // stride of C matrix
    0,                                                // shift value for output
    DSPLIB_FLOAT64,                                   // precision
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    26,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 27))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case27,                               // Input matrix A
    staticRefIn1Case27,                               // Input matrix B
    staticRefOutCase27,                               // Output matrix C
    1,                                                // M
    16,                                               // N
    256,                                              // K
    256 * sizeof (double),                            // stride of A matrix
    16 * sizeof (double),                             // stride of B matrix
    16 * sizeof (double),                             // stride of C matrix
    0,                                                // shift value for output
    DSPLIB_FLOAT64,                                   // precision
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    27,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 28))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input matrix B
    NULL,                                             // Output matrix C
    128,                                              // M
    256,                                              // N
    128,                                              // K
    128 * sizeof (double),                            // stride of A matrix
    256 * sizeof (double),                            // stride of B matrix
    256 * sizeof (double),                            // stride of C matrix
    0,                                                // shift value for output
    DSPLIB_FLOAT64,                                   // precision
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    28,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 29))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input matrix B
    NULL,                                             // Output matrix C
    64,                                               // M
    512,                                              // N
    64,                                               // K
    64 * sizeof (double),                             // stride of A matrix
    512 * sizeof (double),                            // stride of B matrix
    512 * sizeof (double),                            // stride of C matrix
    0,                                                // shift value for output
    DSPLIB_FLOAT64,                                   // precision
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    29,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 30))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input matrix B
    NULL,                                             // Output matrix C
    128,                                              // M
    128,                                              // N
    128,                                              // K
    128 * sizeof (double),                            // stride of A matrix
    128 * sizeof (double),                            // stride of B matrix
    128 * sizeof (double),                            // stride of C matrix
    0,                                                // shift value for output
    DSPLIB_FLOAT64,                                   // precision
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    30,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 31))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input matrix B
    NULL,                                             // Output matrix C
    64,                                               // M
    256,                                              // N
    64,                                               // K
    64 * sizeof (double),                             // stride of A matrix
    256 * sizeof (double),                            // stride of B matrix
    256 * sizeof (double),                            // stride of C matrix
    0,                                                // shift value for output
    DSPLIB_FLOAT64,                                   // precision
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    31,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 32))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input matrix B
    NULL,                                             // Output matrix C
    16,                                               // M
    16,                                               // N
    1024,                                             // K
    1024 * sizeof (double),                           // stride of A matrix
    16 * sizeof (double),                             // stride of B matrix
    16 * sizeof (double),                             // stride of C matrix
    0,                                                // shift value for output
    DSPLIB_FLOAT64,                                   // precision
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    32,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 33))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case33,                               // Input matrix A
    staticRefIn1Case33,                               // Input matrix B
    staticRefOutCase33,                               // Output matrix C
    3,                                                // M
    3,                                                // N
    3,                                                // K
    3 * sizeof (double),                              // stride of A matrix
    3 * sizeof (double),                              // stride of B matrix
    3 * sizeof (double),                              // stride of C matrix
    0,                                                // shift value for output
    DSPLIB_FLOAT64,                                   // precision
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    33,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 34))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input matrix B
    NULL,                                             // Output matrix C
    31,                                               // M
    31,                                               // N
    31,                                               // K
    31 * sizeof (double),                             // stride of A matrix
    31 * sizeof (double),                             // stride of B matrix
    31 * sizeof (double),                             // stride of C matrix
    0,                                                // shift value for output
    DSPLIB_FLOAT64,                                   // precision
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    34,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 35))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case35,                               // Input matrix A
    staticRefIn1Case35,                               // Input matrix B
    staticRefOutCase35,                               // Output matrix C
    64,                                               // M
    64,                                               // N
    64,                                               // K
    64 * sizeof (double),                             // stride of A matrix
    64 * sizeof (double),                             // stride of B matrix
    64 * sizeof (double),                             // stride of C matrix
    0,                                                // shift value for output
    DSPLIB_FLOAT64,                                   // precision
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    35,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 36))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input matrix B
    NULL,                                             // Output matrix C
    51,                                               // M
    51,                                               // N
    51,                                               // K
    64 * sizeof (double),                             // stride of A matrix
    64 * sizeof (double),                             // stride of B matrix
    64 * sizeof (double),                             // stride of C matrix
    0,                                                // shift value for output
    DSPLIB_FLOAT64,                                   // precision
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    36,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 37))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case37,                               // Input matrix A
    staticRefIn1Case37,                               // Input matrix B
    staticRefOutCase37,                               // Output matrix C
    4,                                                // M
    4,                                                // N
    4,                                                // K
    4 * sizeof (double),                              // stride of A matrix
    4 * sizeof (double),                              // stride of B matrix
    4 * sizeof (double),                              // stride of C matrix
    0,                                                // shift value for output
    DSPLIB_FLOAT64,                                   // precision
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    37,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 38))
   {
    STATIC,                                           // Test pattern
    staticRefIn0Case38,                               // Input matrix A
    staticRefIn1Case38,                               // Input matrix B
    staticRefOutCase38,                               // Output matrix C
    1,                                                // M
    256,                                              // N
    16,                                               // K
    16 * sizeof (double),                             // stride of A matrix
    256 * sizeof (double),                            // stride of B matrix
    256 * sizeof (double),                            // stride of C matrix
    0,                                                // shift value for output
    DSPLIB_FLOAT64,                                   // precision
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    38,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 39))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input matrix B
    NULL,                                             // Output matrix C
    128,                                              // M
    256,                                              // N
    128,                                              // K
    128 * sizeof (double),                            // stride of A matrix
    256 * sizeof (double),                            // stride of B matrix
    256 * sizeof (double),                            // stride of C matrix
    0,                                                // shift value for output
    DSPLIB_FLOAT64,                                   // precision
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    39,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 40))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input matrix B
    NULL,                                             // Output matrix C
    64,                                               // M
    512,                                              // N
    64,                                               // K
    64 * sizeof (double),                             // stride of A matrix
    512 * sizeof (double),                            // stride of B matrix
    512 * sizeof (double),                            // stride of C matrix
    0,                                                // shift value for output
    DSPLIB_FLOAT64,                                   // precision
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    40,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 41))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input matrix B
    NULL,                                             // Output matrix C
    64,                                               // M
    256,                                              // N
    64,                                               // K
    64 * sizeof (double),                             // stride of A matrix
    256 * sizeof (double),                            // stride of B matrix
    256 * sizeof (double),                            // stride of C matrix
    0,                                                // shift value for output
    DSPLIB_FLOAT64,                                   // precision
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    41,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 42))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input matrix B
    NULL,                                             // Output matrix C
    41,                                               // M
    64,                                               // N
    55,                                               // K
    64 * sizeof (double),                             // stride of A matrix
    64 * sizeof (double),                             // stride of B matrix
    64 * sizeof (double),                             // stride of C matrix
    0,                                                // shift value for output
    DSPLIB_FLOAT64,                                   // precision
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    42,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 43))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input matrix B
    NULL,                                             // Output matrix C
    32,                                               // M
    32,                                               // N
    32,                                               // K
    32 * sizeof (double),                             // stride of A matrix
    32 * sizeof (double),                             // stride of B matrix
    32 * sizeof (double),                             // stride of C matrix
    0,                                                // shift value for output
    DSPLIB_FLOAT64,                                   // precision
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    43,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 44))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input matrix B
    NULL,                                             // Output matrix C
    1,                                                // M
    1,                                                // N
    1,                                                // K
    1 * sizeof (double),                              // stride of A matrix
    1 * sizeof (double),                              // stride of B matrix
    1 * sizeof (double),                              // stride of C matrix
    0,                                                // shift value for output
    DSPLIB_FLOAT64,                                   // precision
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    44,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 45))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input matrix B
    NULL,                                             // Output matrix C
    1,                                                // M
    1,                                                // N
    1,                                                // K
    32 * sizeof (double),                             // stride of A matrix
    32 * sizeof (double),                             // stride of B matrix
    32 * sizeof (double),                             // stride of C matrix
    0,                                                // shift value for output
    DSPLIB_FLOAT64,                                   // precision
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    45,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 46))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input matrix B
    NULL,                                             // Output matrix C
    3,                                                // M
    1,                                                // N
    1,                                                // K
    32 * sizeof (double),                             // stride of A matrix
    32 * sizeof (double),                             // stride of B matrix
    32 * sizeof (double),                             // stride of C matrix
    0,                                                // shift value for output
    DSPLIB_FLOAT64,                                   // precision
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    46,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 47))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input matrix B
    NULL,                                             // Output matrix C
    4,                                                // M
    4,                                                // N
    1,                                                // K
    32 * sizeof (double),                             // stride of A matrix
    32 * sizeof (double),                             // stride of B matrix
    32 * sizeof (double),                             // stride of C matrix
    0,                                                // shift value for output
    DSPLIB_FLOAT64,                                   // precision
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    47,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 48))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input matrix B
    NULL,                                             // Output matrix C
    4,                                                // M
    4,                                                // N
    1,                                                // K
    1 * sizeof (double),                              // stride of A matrix
    4 * sizeof (double),                              // stride of B matrix
    4 * sizeof (double),                              // stride of C matrix
    0,                                                // shift value for output
    DSPLIB_FLOAT64,                                   // precision
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    48,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 49))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input matrix B
    NULL,                                             // Output matrix C
    5,                                                // M
    5,                                                // N
    1,                                                // K
    32 * sizeof (double),                             // stride of A matrix
    32 * sizeof (double),                             // stride of B matrix
    32 * sizeof (double),                             // stride of C matrix
    0,                                                // shift value for output
    DSPLIB_FLOAT64,                                   // precision
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    49,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 50))
   {
    RANDOM,                                           // Test pattern
    NULL,                                             // Input matrix A
    NULL,                                             // Input matrix B
    NULL,                                             // Output matrix C
    37,                                               // M
    37,                                               // N
    1,                                                // K
    64 * sizeof (double),                             // stride of A matrix
    64 * sizeof (double),                             // stride of B matrix
    64 * sizeof (double),                             // stride of C matrix
    0,                                                // shift value for output
    DSPLIB_FLOAT64,                                   // precision
    DSPLIB_TEST_OUTPUT_MSMC,                          // Output data location
    1,                                                // number of reps.
    50,                                               // test ID
    },
#endif

};

/*
 *  Sends the test parameter structure and number of tests
 */
void
DSPLIB_matMul_getTestParams (DSPLIB_matMul_testParams_t ** params, int32_t * numTests)
{
   *params = testParams;
   *numTests = sizeof (testParams) / sizeof (DSPLIB_matMul_testParams_t);
}
