/*******************************************************************************
 **+--------------------------------------------------------------------------+**
 **|                            ****                                          |**
 **|                            ****                                          |**
 **|                            ******o***                                    |**
 **|                      ********_///_****                                   |**
 **|                      ***** /_//_/ ****                                   |**
 **|                       ** ** (__/ ****                                    |**
 **|                           *********                                      |**
 **|                            ****                                          |**
 **|                            ***                                           |**
 **|                                                                          |**
 **|         Copyright (c) 2016 Texas Instruments Incorporated                |**
 **|                        ALL RIGHTS RESERVED                               |**
 **|                                                                          |**
 **| Permission to use, copy, modify, or distribute this software,            |**
 **| whether in part or in whole, for any purpose is forbidden without        |**
 **| a signed licensing agreement and NDA from Texas Instruments              |**
 **| Incorporated (TI).                                                       |**
 **|                                                                          |**
 **| TI makes no representation or warranties with respect to the             |**
 **| performance of this computer program, and specifically disclaims         |**
 **| any responsibility for any damages, special or consequential,            |**
 **| connected with the use of this program.                                  |**
 **|                                                                          |**
 **+--------------------------------------------------------------------------+**
 *******************************************************************************/

/*This file is autogenerated*/
/*Please do not edit*/


__attribute__((section(".staticData"))) static float staticRefInputCase136[]=
{
39.126, -6.482, 21.061, -10.65, -25.659, 44.759, -39.774, -30.302, -21.867, 5.413, 28.096, -25.141, 1.109, 47.719, -35.034, -16.618,  

};

__attribute__((section(".staticData"))) static int32_t staticRefOutputCase136[]=
{
39, -6, 21, -11, -26, 45, -40, -30, -22,  5, 28, -25,  1, 48, -35, -17,  0,  0,  

};

__attribute__((section(".staticData"))) static float staticRefInputScaleCase136[]=
{
1.00,  

};

__attribute__((section(".staticData"))) static uint8_t staticRefInputShiftCase136[]=
{
 1,  

};

__attribute__((section(".staticData"))) static float staticRefInputQ1Case136[]=
{
1.00,  

};

__attribute__((section(".staticData"))) static float staticRefInputQ2Case136[]=
{
0.00,  

};

