/******************************************************************************/
/* Copyright (C) 2023 Texas Instruments Incorporated - http://www.ti.com/
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 ******************************************************************************/

#include "VXLIB_histogram_idat.h"
/*This file is autogenerated*/
/*Please do not edit*/

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
#include "test_data/staticRefCase1.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
#include "test_data/staticRefCase2.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
#include "test_data/staticRefCase3.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
#include "test_data/staticRefCase4.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
#include "test_data/staticRefCase5.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
#include "test_data/staticRefCase6.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
#include "test_data/staticRefCase7.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
#include "test_data/staticRefCase8.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
#include "test_data/staticRefCase9.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
#include "test_data/staticRefCase10.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
#include "test_data/staticRefCase11.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12))
#include "test_data/staticRefCase12.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 13))
#include "test_data/staticRefCase13.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 14))
#include "test_data/staticRefCase14.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 15))
#include "test_data/staticRefCase15.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 16))
#include "test_data/staticRefCase16.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 17))
#include "test_data/staticRefCase17.h"
#endif

static VXLIB_histogram_testParams_t testParams[] = {
#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
   {
    STATIC,                                           // Test pattern
    staticRefInCase1,                                 // Input vector
    VXLIB_UINT8,                                      // data type in
    staticRefOutCase1,                                // Output vector
    VXLIB_UINT32,                                     // data type out
    8,                                                // width of image
    2,                                                // height of image
    10 * sizeof (uint8_t),                            // strideIn
    2,                                                // offset
    254,                                              // range
    16,                                               // numBins
    1,                                                // final call to image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    1,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
   {
    STATIC,                                           // Test pattern
    staticRefInCase2,                                 // Input vector
    VXLIB_UINT8,                                      // data type in
    staticRefOutCase2,                                // Output vector
    VXLIB_UINT32,                                     // data type out
    16,                                               // width of image
    2,                                                // height of image
    16 * sizeof (uint8_t),                            // strideIn
    2,                                                // offset
    254,                                              // range
    16,                                               // numBins
    1,                                                // final call to image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    2,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
   {
    STATIC,                                           // Test pattern
    staticRefInCase3,                                 // Input vector
    VXLIB_UINT8,                                      // data type in
    staticRefOutCase3,                                // Output vector
    VXLIB_UINT32,                                     // data type out
    16,                                               // width of image
    16,                                               // height of image
    16 * sizeof (uint8_t),                            // strideIn
    0,                                                // offset
    256,                                              // range
    100,                                              // numBins
    1,                                                // final call to image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    3,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
   {
    STATIC,                                           // Test pattern
    staticRefInCase4,                                 // Input vector
    VXLIB_UINT8,                                      // data type in
    staticRefOutCase4,                                // Output vector
    VXLIB_UINT32,                                     // data type out
    32,                                               // width of image
    32,                                               // height of image
    32 * sizeof (uint8_t),                            // strideIn
    0,                                                // offset
    256,                                              // range
    100,                                              // numBins
    1,                                                // final call to image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    4,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
   {
    STATIC,                                           // Test pattern
    staticRefInCase5,                                 // Input vector
    VXLIB_UINT8,                                      // data type in
    staticRefOutCase5,                                // Output vector
    VXLIB_UINT32,                                     // data type out
    64,                                               // width of image
    64,                                               // height of image
    64 * sizeof (uint8_t),                            // strideIn
    0,                                                // offset
    256,                                              // range
    100,                                              // numBins
    1,                                                // final call to image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    5,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
   {
    STATIC,                                           // Test pattern
    staticRefInCase6,                                 // Input vector
    VXLIB_UINT8,                                      // data type in
    staticRefOutCase6,                                // Output vector
    VXLIB_UINT32,                                     // data type out
    128,                                              // width of image
    128,                                              // height of image
    128 * sizeof (uint8_t),                           // strideIn
    0,                                                // offset
    256,                                              // range
    100,                                              // numBins
    1,                                                // final call to image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    6,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
   {
    STATIC,                                           // Test pattern
    staticRefInCase7,                                 // Input vector
    VXLIB_UINT8,                                      // data type in
    staticRefOutCase7,                                // Output vector
    VXLIB_UINT32,                                     // data type out
    256,                                              // width of image
    256,                                              // height of image
    256 * sizeof (uint8_t),                           // strideIn
    0,                                                // offset
    256,                                              // range
    100,                                              // numBins
    1,                                                // final call to image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    7,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
   {
    STATIC,                                           // Test pattern
    staticRefInCase8,                                 // Input vector
    VXLIB_UINT8,                                      // data type in
    staticRefOutCase8,                                // Output vector
    VXLIB_UINT32,                                     // data type out
    512,                                              // width of image
    512,                                              // height of image
    512 * sizeof (uint8_t),                           // strideIn
    0,                                                // offset
    256,                                              // range
    100,                                              // numBins
    1,                                                // final call to image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    8,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
   {
    STATIC,                                           // Test pattern
    staticRefInCase9,                                 // Input vector
    VXLIB_UINT8,                                      // data type in
    staticRefOutCase9,                                // Output vector
    VXLIB_UINT32,                                     // data type out
    15,                                               // width of image
    16,                                               // height of image
    60 * sizeof (uint8_t),                            // strideIn
    0,                                                // offset
    256,                                              // range
    100,                                              // numBins
    1,                                                // final call to image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    9,                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
   {
    STATIC,                                           // Test pattern
    staticRefInCase10,                                // Input vector
    VXLIB_UINT8,                                      // data type in
    staticRefOutCase10,                               // Output vector
    VXLIB_UINT32,                                     // data type out
    33,                                               // width of image
    40,                                               // height of image
    60 * sizeof (uint8_t),                            // strideIn
    0,                                                // offset
    256,                                              // range
    100,                                              // numBins
    1,                                                // final call to image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    10,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
   {
    STATIC,                                           // Test pattern
    staticRefInCase11,                                // Input vector
    VXLIB_UINT8,                                      // data type in
    staticRefOutCase11,                               // Output vector
    VXLIB_UINT32,                                     // data type out
    26,                                               // width of image
    77,                                               // height of image
    120 * sizeof (uint8_t),                           // strideIn
    0,                                                // offset
    256,                                              // range
    100,                                              // numBins
    1,                                                // final call to image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    11,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12))
   {
    STATIC,                                           // Test pattern
    staticRefInCase12,                                // Input vector
    VXLIB_UINT8,                                      // data type in
    staticRefOutCase12,                               // Output vector
    VXLIB_UINT32,                                     // data type out
    122,                                              // width of image
    150,                                              // height of image
    225 * sizeof (uint8_t),                           // strideIn
    0,                                                // offset
    256,                                              // range
    100,                                              // numBins
    1,                                                // final call to image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    12,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 13))
   {
    STATIC,                                           // Test pattern
    staticRefInCase13,                                // Input vector
    VXLIB_UINT8,                                      // data type in
    staticRefOutCase13,                               // Output vector
    VXLIB_UINT32,                                     // data type out
    232,                                              // width of image
    15,                                               // height of image
    256 * sizeof (uint8_t),                           // strideIn
    0,                                                // offset
    256,                                              // range
    100,                                              // numBins
    1,                                                // final call to image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    13,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 14))
   {
    STATIC,                                           // Test pattern
    staticRefInCase14,                                // Input vector
    VXLIB_UINT8,                                      // data type in
    staticRefOutCase14,                               // Output vector
    VXLIB_UINT32,                                     // data type out
    505,                                              // width of image
    465,                                              // height of image
    512 * sizeof (uint8_t),                           // strideIn
    0,                                                // offset
    256,                                              // range
    100,                                              // numBins
    1,                                                // final call to image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    14,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 15))
   {
    STATIC,                                           // Test pattern
    staticRefInCase15,                                // Input vector
    VXLIB_UINT8,                                      // data type in
    staticRefOutCase15,                               // Output vector
    VXLIB_UINT32,                                     // data type out
    15,                                               // width of image
    16,                                               // height of image
    15 * sizeof (uint8_t),                            // strideIn
    0,                                                // offset
    256,                                              // range
    100,                                              // numBins
    1,                                                // final call to image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    15,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 16))
   {
    STATIC,                                           // Test pattern
    staticRefInCase16,                                // Input vector
    VXLIB_UINT8,                                      // data type in
    staticRefOutCase16,                               // Output vector
    VXLIB_UINT32,                                     // data type out
    17,                                               // width of image
    15,                                               // height of image
    17 * sizeof (uint8_t),                            // strideIn
    0,                                                // offset
    256,                                              // range
    100,                                              // numBins
    1,                                                // final call to image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    16,                                               // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 17))
   {
    STATIC,                                           // Test pattern
    staticRefInCase17,                                // Input vector
    VXLIB_UINT8,                                      // data type in
    staticRefOutCase17,                               // Output vector
    VXLIB_UINT32,                                     // data type out
    31,                                               // width of image
    14,                                               // height of image
    31 * sizeof (uint8_t),                            // strideIn
    0,                                                // offset
    256,                                              // range
    150,                                              // numBins
    1,                                                // final call to image
    VXLIB_TEST_OUTPUT_MSMC,                           // Output data location
    1,                                                // number of reps.
    17,                                               // test ID
    },
#endif

};

/*
 *  Sends the test parameter structure and number of tests
 */
void
VXLIB_histogram_getTestParams (VXLIB_histogram_testParams_t ** params, int32_t * numTests)
{
   *params = testParams;
   *numTests = sizeof (testParams) / sizeof (VXLIB_histogram_testParams_t);
}
